/* Generated by tools/gen_cartridges.py; Do not edit. */

#define MMO_CARTRIDGE_COUNT 9
#define MMO_CARTRIDGE_LANG_COUNT 9

static const MmoCartridge MMO_CARTRIDGES[MMO_CARTRIDGE_COUNT] = {
    { "CPUE", "platinum", "Platinum", MMO_CART_HOST, "", "POKEMON PL", "read 2026-08-16; the client's own image", 2 }, /* host */
    { "IPKE", "heartgold", "Heart Gold", MMO_CART_READ, "pokemon,item_icon,trainer,region", "POKEMON HG", "read 2026-08-16; a/0/0/4 six a species, a/0/1/8 two an item, a/0/5/8 five a class; gs_sound_data read 2026-08-25 (2379 sequences), serves the soundtrack switch; the whole of Johto crosses as a region 2026-08-30 (339 maps, 413 land members, 440 prop models)", 2 }, /* read */
    { "ADAE", "diamond", "Diamond", MMO_CART_READ, "pokemon", "POKEMON D", "read 2026-08-16; its sheets scramble back-to-front and are re-encoded on the way in (2026-08-21)", 1 }, /* read */
    { "IPGE", "soulsilver", "SoulSilver", MMO_CART_READ, "pokemon,item_icon,trainer,region", "POKEMON SS", "read 2026-08-21; the HeartGold twin, and all three archives are byte-identical to it, a second way to own the same art, not new art; the soundtrack door takes it as the twin, gated by the audio lab, and its map archives are the twin's too", 2 }, /* read */
    { "APAE", "pearl", "Pearl", MMO_CART_READ, "pokemon", "POKEMON P", "read 2026-08-21; the Diamond twin, and its pokegra is byte-identical to it, a second way to own the same art, not new art", 1 }, /* read */
    { "IRBO", "black", "Black", MMO_CART_REFUSES, "", "POKEMON B", "read 2026-08-16; a/0/0/4 is 14285 members, LZ-compressed; wb_sound_data read 2026-08-25 (2076 sequences, one bank per track) and serves the soundtrack switch through its own door, tools/soundtrack.py; a/0/1/6, a/0/2/1, a/0/1/8, a/0/1/9 and a/0/0/2 read 2026-08-30 and serve the SERVER's species and move tables through a third door, tools/gen5_tables.py; a/0/0/7 read 2026-08-30 too and its icons DO port, 493 of 494 byte-identical after one header byte, and tools/portspecies.py carries the personal data, learnsets, evolutions, icons and names of all 156 species it adds through a fourth door, and since the evening of 2026-08-30 tools/portsprites.py assembles their cell-composed battle sprites into pl_pokegra sheets and height bytes through the same door, and tools/portmoves.py carries the 92 moves (table, three text banks, a borrowed animation, the battle stub) through it too. `refuses` is about the recipe porter: no port.recipe line can name a Gen 5 archive, because none of its layouts is one the engine's loaders read, and every door above rewrites on the way in", 0 }, /* refuses */
    { "IRAO", "white", "White", MMO_CART_UNREAD, "", "", "White, the Black twin; the soundtrack door takes it as one, gated by the audio lab", 0 }, /* unread */
    { "CPUJ", "platinum", "Platinum", MMO_CART_UNREAD, "", "", "Japanese Platinum", 0 }, /* unread */
    { "IPKJ", "heartgold", "Heart Gold", MMO_CART_UNREAD, "", "", "Japanese HeartGold", 0 }, /* unread */
};

static const MmoCartridgeLang MMO_CARTRIDGE_LANGS[MMO_CARTRIDGE_LANG_COUNT] = {
    { 'E', "english", 1 },
    { 'O', "english", 1 },
    { 'J', "japanese", 0 },
    { 'P', "english", 0 },
    { 'D', "german", 0 },
    { 'F', "french", 0 },
    { 'I', "italian", 0 },
    { 'S', "spanish", 0 },
    { 'K', "korean", 0 },
};

