/* Generated by tools/gen_display_types.py; Do not edit. */

#define MMO_TYPE_COUNT   18
#define MMO_TYPE_MYSTERY 9  /* the ??? slot: neutral both ways, drawn by nothing */
#define MMO_TYPE_NEUTRAL 10  /* the multiplier the engine's sparse table omits */

static const char *const MMO_TYPE_NAME[MMO_TYPE_COUNT] = {
    "NORMAL",   /* 0 */
    "FIGHTING", /* 1 */
    "FLYING",   /* 2 */
    "POISON",   /* 3 */
    "GROUND",   /* 4 */
    "ROCK",     /* 5 */
    "BUG",      /* 6 */
    "GHOST",    /* 7 */
    "STEEL",    /* 8 */
    "???",      /* 9 */
    "FIRE",     /* 10 */
    "WATER",    /* 11 */
    "GRASS",    /* 12 */
    "ELECTRIC", /* 13 */
    "PSYCHIC",  /* 14 */
    "ICE",      /* 15 */
    "DRAGON",   /* 16 */
    "DARK",     /* 17 */
};

static const u8 MMO_TYPE_MATCHUP[MMO_TYPE_COUNT][MMO_TYPE_COUNT] = {
    { 10, 10, 10, 10, 10,  5, 10,  0,  5, 10, 10, 10, 10, 10, 10, 10, 10, 10 }, /* NORMAL */
    { 20, 10,  5,  5, 10, 20,  5,  0, 20, 10, 10, 10, 10, 10,  5, 20, 10, 20 }, /* FIGHTING */
    { 10, 20, 10, 10, 10,  5, 20, 10,  5, 10, 10, 10, 20,  5, 10, 10, 10, 10 }, /* FLYING */
    { 10, 10, 10,  5,  5,  5, 10,  5,  0, 10, 10, 10, 20, 10, 10, 10, 10, 10 }, /* POISON */
    { 10, 10,  0, 20, 10, 20,  5, 10, 20, 10, 20, 10,  5, 20, 10, 10, 10, 10 }, /* GROUND */
    { 10,  5, 20, 10,  5, 10, 20, 10,  5, 10, 20, 10, 10, 10, 10, 20, 10, 10 }, /* ROCK */
    { 10,  5,  5,  5, 10, 10, 10,  5,  5, 10,  5, 10, 20, 10, 20, 10, 10, 20 }, /* BUG */
    {  0, 10, 10, 10, 10, 10, 10, 20,  5, 10, 10, 10, 10, 10, 20, 10, 10,  5 }, /* GHOST */
    { 10, 10, 10, 10, 10, 20, 10, 10,  5, 10,  5,  5, 10,  5, 10, 20, 10, 10 }, /* STEEL */
    { 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10 }, /* ??? */
    { 10, 10, 10, 10, 10,  5, 20, 10, 20, 10,  5,  5, 20, 10, 10, 20,  5, 10 }, /* FIRE */
    { 10, 10, 10, 10, 20, 20, 10, 10, 10, 10, 20,  5,  5, 10, 10, 10,  5, 10 }, /* WATER */
    { 10, 10,  5,  5, 20, 20,  5, 10,  5, 10,  5, 20,  5, 10, 10, 10,  5, 10 }, /* GRASS */
    { 10, 10, 20, 10,  0, 10, 10, 10, 10, 10, 10, 20,  5,  5, 10, 10,  5, 10 }, /* ELECTRIC */
    { 10, 20, 10, 20, 10, 10, 10, 10,  5, 10, 10, 10, 10, 10,  5, 10, 10,  0 }, /* PSYCHIC */
    { 10, 10, 20, 10, 20, 10, 10, 10,  5, 10,  5,  5, 20, 10, 10,  5, 20, 10 }, /* ICE */
    { 10, 10, 10, 10, 10, 10, 10, 10,  5, 10, 10, 10, 10, 10, 10, 10, 20, 10 }, /* DRAGON */
    { 10,  5, 10, 10, 10, 10, 10, 20,  5, 10, 10, 10, 10, 10, 20, 10, 10,  5 }, /* DARK */
};

#define MMO_TYPE_FORESIGHT_IMMUNITY_COUNT 2
static const u8 MMO_TYPE_FORESIGHT_IMMUNITY[MMO_TYPE_FORESIGHT_IMMUNITY_COUNT][2] = {
    {  0,  7 }, /* NORMAL vs GHOST */
    {  1,  7 }, /* FIGHTING vs GHOST */
};
