/* Generated by tools/gen_display_data.py; Do not edit. */

#define MMO_DISPLAY_ABILITY_COUNT 165
#define MMO_DISPLAY_MOVE_COUNT    468
#define MMO_DISPLAY_SPECIES_COUNT 494

static const char *const MMO_DISPLAY_ABILITY_NAME[MMO_DISPLAY_ABILITY_COUNT] = {
    " -", /* 0 ABILITY_NONE */
    "Stench", /* 1 ABILITY_STENCH */
    "Drizzle", /* 2 ABILITY_DRIZZLE */
    "Speed Boost", /* 3 ABILITY_SPEED_BOOST */
    "Battle Armor", /* 4 ABILITY_BATTLE_ARMOR */
    "Sturdy", /* 5 ABILITY_STURDY */
    "Damp", /* 6 ABILITY_DAMP */
    "Limber", /* 7 ABILITY_LIMBER */
    "Sand Veil", /* 8 ABILITY_SAND_VEIL */
    "Static", /* 9 ABILITY_STATIC */
    "Volt Absorb", /* 10 ABILITY_VOLT_ABSORB */
    "Water Absorb", /* 11 ABILITY_WATER_ABSORB */
    "Oblivious", /* 12 ABILITY_OBLIVIOUS */
    "Cloud Nine", /* 13 ABILITY_CLOUD_NINE */
    "Compoundeyes", /* 14 ABILITY_COMPOUND_EYES */
    "Insomnia", /* 15 ABILITY_INSOMNIA */
    "Color Change", /* 16 ABILITY_COLOR_CHANGE */
    "Immunity", /* 17 ABILITY_IMMUNITY */
    "Flash Fire", /* 18 ABILITY_FLASH_FIRE */
    "Shield Dust", /* 19 ABILITY_SHIELD_DUST */
    "Own Tempo", /* 20 ABILITY_OWN_TEMPO */
    "Suction Cups", /* 21 ABILITY_SUCTION_CUPS */
    "Intimidate", /* 22 ABILITY_INTIMIDATE */
    "Shadow Tag", /* 23 ABILITY_SHADOW_TAG */
    "Rough Skin", /* 24 ABILITY_ROUGH_SKIN */
    "Wonder Guard", /* 25 ABILITY_WONDER_GUARD */
    "Levitate", /* 26 ABILITY_LEVITATE */
    "Effect Spore", /* 27 ABILITY_EFFECT_SPORE */
    "Synchronize", /* 28 ABILITY_SYNCHRONIZE */
    "Clear Body", /* 29 ABILITY_CLEAR_BODY */
    "Natural Cure", /* 30 ABILITY_NATURAL_CURE */
    "Lightningrod", /* 31 ABILITY_LIGHTNING_ROD */
    "Serene Grace", /* 32 ABILITY_SERENE_GRACE */
    "Swift Swim", /* 33 ABILITY_SWIFT_SWIM */
    "Chlorophyll", /* 34 ABILITY_CHLOROPHYLL */
    "Illuminate", /* 35 ABILITY_ILLUMINATE */
    "Trace", /* 36 ABILITY_TRACE */
    "Huge Power", /* 37 ABILITY_HUGE_POWER */
    "Poison Point", /* 38 ABILITY_POISON_POINT */
    "Inner Focus", /* 39 ABILITY_INNER_FOCUS */
    "Magma Armor", /* 40 ABILITY_MAGMA_ARMOR */
    "Water Veil", /* 41 ABILITY_WATER_VEIL */
    "Magnet Pull", /* 42 ABILITY_MAGNET_PULL */
    "Soundproof", /* 43 ABILITY_SOUNDPROOF */
    "Rain Dish", /* 44 ABILITY_RAIN_DISH */
    "Sand Stream", /* 45 ABILITY_SAND_STREAM */
    "Pressure", /* 46 ABILITY_PRESSURE */
    "Thick Fat", /* 47 ABILITY_THICK_FAT */
    "Early Bird", /* 48 ABILITY_EARLY_BIRD */
    "Flame Body", /* 49 ABILITY_FLAME_BODY */
    "Run Away", /* 50 ABILITY_RUN_AWAY */
    "Keen Eye", /* 51 ABILITY_KEEN_EYE */
    "Hyper Cutter", /* 52 ABILITY_HYPER_CUTTER */
    "Pickup", /* 53 ABILITY_PICKUP */
    "Truant", /* 54 ABILITY_TRUANT */
    "Hustle", /* 55 ABILITY_HUSTLE */
    "Cute Charm", /* 56 ABILITY_CUTE_CHARM */
    "Plus", /* 57 ABILITY_PLUS */
    "Minus", /* 58 ABILITY_MINUS */
    "Forecast", /* 59 ABILITY_FORECAST */
    "Sticky Hold", /* 60 ABILITY_STICKY_HOLD */
    "Shed Skin", /* 61 ABILITY_SHED_SKIN */
    "Guts", /* 62 ABILITY_GUTS */
    "Marvel Scale", /* 63 ABILITY_MARVEL_SCALE */
    "Liquid Ooze", /* 64 ABILITY_LIQUID_OOZE */
    "Overgrow", /* 65 ABILITY_OVERGROW */
    "Blaze", /* 66 ABILITY_BLAZE */
    "Torrent", /* 67 ABILITY_TORRENT */
    "Swarm", /* 68 ABILITY_SWARM */
    "Rock Head", /* 69 ABILITY_ROCK_HEAD */
    "Drought", /* 70 ABILITY_DROUGHT */
    "Arena Trap", /* 71 ABILITY_ARENA_TRAP */
    "Vital Spirit", /* 72 ABILITY_VITAL_SPIRIT */
    "White Smoke", /* 73 ABILITY_WHITE_SMOKE */
    "Pure Power", /* 74 ABILITY_PURE_POWER */
    "Shell Armor", /* 75 ABILITY_SHELL_ARMOR */
    "Air Lock", /* 76 ABILITY_AIR_LOCK */
    "Tangled Feet", /* 77 ABILITY_TANGLED_FEET */
    "Motor Drive", /* 78 ABILITY_MOTOR_DRIVE */
    "Rivalry", /* 79 ABILITY_RIVALRY */
    "Steadfast", /* 80 ABILITY_STEADFAST */
    "Snow Cloak", /* 81 ABILITY_SNOW_CLOAK */
    "Gluttony", /* 82 ABILITY_GLUTTONY */
    "Anger Point", /* 83 ABILITY_ANGER_POINT */
    "Unburden", /* 84 ABILITY_UNBURDEN */
    "Heatproof", /* 85 ABILITY_HEATPROOF */
    "Simple", /* 86 ABILITY_SIMPLE */
    "Dry Skin", /* 87 ABILITY_DRY_SKIN */
    "Download", /* 88 ABILITY_DOWNLOAD */
    "Iron Fist", /* 89 ABILITY_IRON_FIST */
    "Poison Heal", /* 90 ABILITY_POISON_HEAL */
    "Adaptability", /* 91 ABILITY_ADAPTABILITY */
    "Skill Link", /* 92 ABILITY_SKILL_LINK */
    "Hydration", /* 93 ABILITY_HYDRATION */
    "Solar Power", /* 94 ABILITY_SOLAR_POWER */
    "Quick Feet", /* 95 ABILITY_QUICK_FEET */
    "Normalize", /* 96 ABILITY_NORMALIZE */
    "Sniper", /* 97 ABILITY_SNIPER */
    "Magic Guard", /* 98 ABILITY_MAGIC_GUARD */
    "No Guard", /* 99 ABILITY_NO_GUARD */
    "Stall", /* 100 ABILITY_STALL */
    "Technician", /* 101 ABILITY_TECHNICIAN */
    "Leaf Guard", /* 102 ABILITY_LEAF_GUARD */
    "Klutz", /* 103 ABILITY_KLUTZ */
    "Mold Breaker", /* 104 ABILITY_MOLD_BREAKER */
    "Super Luck", /* 105 ABILITY_SUPER_LUCK */
    "Aftermath", /* 106 ABILITY_AFTERMATH */
    "Anticipation", /* 107 ABILITY_ANTICIPATION */
    "Forewarn", /* 108 ABILITY_FOREWARN */
    "Unaware", /* 109 ABILITY_UNAWARE */
    "Tinted Lens", /* 110 ABILITY_TINTED_LENS */
    "Filter", /* 111 ABILITY_FILTER */
    "Slow Start", /* 112 ABILITY_SLOW_START */
    "Scrappy", /* 113 ABILITY_SCRAPPY */
    "Storm Drain", /* 114 ABILITY_STORM_DRAIN */
    "Ice Body", /* 115 ABILITY_ICE_BODY */
    "Solid Rock", /* 116 ABILITY_SOLID_ROCK */
    "Snow Warning", /* 117 ABILITY_SNOW_WARNING */
    "Honey Gather", /* 118 ABILITY_HONEY_GATHER */
    "Frisk", /* 119 ABILITY_FRISK */
    "Reckless", /* 120 ABILITY_RECKLESS */
    "Multitype", /* 121 ABILITY_MULTITYPE */
    "Flower Gift", /* 122 ABILITY_FLOWER_GIFT */
    "Bad Dreams", /* 123 ABILITY_BAD_DREAMS */
    "Pickpocket", /* 124 ABILITY_PICKPOCKET */
    "Sheer Force", /* 125 ABILITY_SHEER_FORCE */
    "Contrary", /* 126 ABILITY_CONTRARY */
    "Unnerve", /* 127 ABILITY_UNNERVE */
    "Defiant", /* 128 ABILITY_DEFIANT */
    "Defeatist", /* 129 ABILITY_DEFEATIST */
    "Cursed Body", /* 130 ABILITY_CURSED_BODY */
    "Healer", /* 131 ABILITY_HEALER */
    "Friend Guard", /* 132 ABILITY_FRIEND_GUARD */
    "Weak Armor", /* 133 ABILITY_WEAK_ARMOR */
    "Heavy Metal", /* 134 ABILITY_HEAVY_METAL */
    "Light Metal", /* 135 ABILITY_LIGHT_METAL */
    "Multiscale", /* 136 ABILITY_MULTISCALE */
    "Toxic Boost", /* 137 ABILITY_TOXIC_BOOST */
    "Flare Boost", /* 138 ABILITY_FLARE_BOOST */
    "Harvest", /* 139 ABILITY_HARVEST */
    "Telepathy", /* 140 ABILITY_TELEPATHY */
    "Moody", /* 141 ABILITY_MOODY */
    "Overcoat", /* 142 ABILITY_OVERCOAT */
    "Poison Touch", /* 143 ABILITY_POISON_TOUCH */
    "Regenerator", /* 144 ABILITY_REGENERATOR */
    "Big Pecks", /* 145 ABILITY_BIG_PECKS */
    "Sand Rush", /* 146 ABILITY_SAND_RUSH */
    "Wonder Skin", /* 147 ABILITY_WONDER_SKIN */
    "Analytic", /* 148 ABILITY_ANALYTIC */
    "Illusion", /* 149 ABILITY_ILLUSION */
    "Imposter", /* 150 ABILITY_IMPOSTER */
    "Infiltrator", /* 151 ABILITY_INFILTRATOR */
    "Mummy", /* 152 ABILITY_MUMMY */
    "Moxie", /* 153 ABILITY_MOXIE */
    "Justified", /* 154 ABILITY_JUSTIFIED */
    "Rattled", /* 155 ABILITY_RATTLED */
    "Magic Bounce", /* 156 ABILITY_MAGIC_BOUNCE */
    "Sap Sipper", /* 157 ABILITY_SAP_SIPPER */
    "Prankster", /* 158 ABILITY_PRANKSTER */
    "Sand Force", /* 159 ABILITY_SAND_FORCE */
    "Iron Barbs", /* 160 ABILITY_IRON_BARBS */
    "Zen Mode", /* 161 ABILITY_ZEN_MODE */
    "Victory Star", /* 162 ABILITY_VICTORY_STAR */
    "Turboblaze", /* 163 ABILITY_TURBOBLAZE */
    "Teravolt", /* 164 ABILITY_TERAVOLT */
};

static const char *const MMO_DISPLAY_ABILITY_DESC[MMO_DISPLAY_ABILITY_COUNT] = {
    " -", /* 0 */
    "The stench helps keep\nwild Pokémon away.", /* 1 */
    "The Pokémon makes it rain\nif it appears in battle.", /* 2 */
    "The Pokémon’s Speed stat\nis gradually boosted.", /* 3 */
    "The Pokémon is protected\nagainst critical hits.", /* 4 */
    "The Pokémon is protected\nagainst 1-hit KO attacks.", /* 5 */
    "Prevents combatants from\nself destructing.", /* 6 */
    "The Pokémon is protected\nfrom paralysis.", /* 7 */
    "Boosts the Pokémon’s\nevasion in a sandstorm.", /* 8 */
    "Contact with the Pokémon\nmay cause paralysis.", /* 9 */
    "Restores HP if hit by an\nElectric-type move.", /* 10 */
    "Restores HP if hit by a\nWater-type move.", /* 11 */
    "Prevents the Pokémon\nfrom becoming infatuated.", /* 12 */
    "Eliminates the effects of\nweather.", /* 13 */
    "The Pokémon’s accuracy is\nboosted.", /* 14 */
    "Prevents the Pokémon\nfrom falling asleep.", /* 15 */
    "Changes the Pokémon’s\ntype to the foe’s move.", /* 16 */
    "Prevents the Pokémon\nfrom getting poisoned.", /* 17 */
    "Powers up Fire-type moves\nif hit by a fire move.", /* 18 */
    "Blocks the added effects\nof attacks taken.", /* 19 */
    "Prevents the Pokémon\nfrom becoming confused.", /* 20 */
    "Negates moves that\nforce switching out.", /* 21 */
    "Lowers the foe’s Attack\nstat.", /* 22 */
    "Prevents the foe from\nescaping.", /* 23 */
    "Inflicts damage to the\nfoe on contact.", /* 24 */
    "Only supereffective\nmoves will hit.", /* 25 */
    "Gives full immunity to all\nGround-type moves.", /* 26 */
    "Contact may paralyze,\npoison, or cause sleep.", /* 27 */
    "Passes on a burn, poison,\nor paralysis to the foe.", /* 28 */
    "Prevents the Pokémon’s\nstats from being lowered.", /* 29 */
    "All status problems are\nhealed upon switching out.", /* 30 */
    "The Pokémon draws in all\nElectric-type moves.", /* 31 */
    "Boosts the likelihood of\nadded effects appearing.", /* 32 */
    "Boosts the Pokémon’s\nSpeed in rain.", /* 33 */
    "Boosts the Pokémon’s\nSpeed in sunshine.", /* 34 */
    "Raises the likelihood of\nmeeting wild Pokémon.", /* 35 */
    "The Pokémon copies the\nfoe’s ability.", /* 36 */
    "Raises the Pokémon’s\nAttack stat.", /* 37 */
    "Contact with the Pokémon\nmay poison the foe.", /* 38 */
    "The Pokémon is protected\nfrom flinching.", /* 39 */
    "Prevents the Pokémon\nfrom becoming frozen.", /* 40 */
    "Prevents the Pokémon\nfrom getting a burn.", /* 41 */
    "Prevents Steel-type\nPokémon from escaping.", /* 42 */
    "Gives full immunity to all\nsound-based moves.", /* 43 */
    "The Pokémon gradually\nrecovers HP in rain.", /* 44 */
    "The Pokémon summons a\nsandstorm in battle.", /* 45 */
    "The Pokémon raises the\nfoe’s PP usage.", /* 46 */
    "Raises resistance to Fire-\nand Ice-type moves.", /* 47 */
    "The Pokémon awakens\nquickly from sleep.", /* 48 */
    "Contact with the Pokémon\nmay burn the foe.", /* 49 */
    "Enables sure getaway from\nwild Pokémon.", /* 50 */
    "Prevents the Pokémon\nfrom losing accuracy.", /* 51 */
    "Prevents the Attack stat\nfrom being lowered.", /* 52 */
    "The Pokémon may pick up\nitems.", /* 53 */
    "The Pokémon can’t attack\non consecutive turns.", /* 54 */
    "Boosts the Attack stat,\nbut lowers accuracy.", /* 55 */
    "Contact with the Pokémon\nmay cause infatuation.", /* 56 */
    "Boosts Sp. Atk if another\nPokémon has Minus.", /* 57 */
    "Boosts Sp. Atk if another\nPokémon has Plus.", /* 58 */
    "CASTFORM transforms with\nthe weather.", /* 59 */
    "Protects the Pokémon\nfrom item theft.", /* 60 */
    "The Pokémon may heal its\nown status problems.", /* 61 */
    "Boosts Attack if there is\na status problem.", /* 62 */
    "Boosts Defense if there is\na status problem.", /* 63 */
    "Inflicts damage on foes\nusing any draining move.", /* 64 */
    "Powers up Grass-type\nmoves in a pinch.", /* 65 */
    "Powers up Fire-type\nmoves in a pinch.", /* 66 */
    "Powers up Water-type\nmoves in a pinch.", /* 67 */
    "Powers up Bug-type\nmoves in a pinch.", /* 68 */
    "Protects the Pokémon\nfrom recoil damage.", /* 69 */
    "The Pokémon makes it\nsunny if it is in battle.", /* 70 */
    "Prevents the foe from\nfleeing.", /* 71 */
    "Prevents the Pokémon\nfrom falling asleep.", /* 72 */
    "Prevents the Pokémon’s\nstats from being lowered.", /* 73 */
    "Boosts the power of\nphysical attacks.", /* 74 */
    "The Pokémon is protected\nagainst critical hits.", /* 75 */
    "Eliminates the effects of\nweather.", /* 76 */
    "Raises evasion if the\nPokémon is confused.", /* 77 */
    "Raises Speed if hit by an\nElectric-type move.", /* 78 */
    "Raises Attack if the foe\nis of the same gender.", /* 79 */
    "Raises Speed each time\nthe Pokémon flinches.", /* 80 */
    "Raises evasion in a\nhailstorm.", /* 81 */
    "Encourages the early use\nof a held Berry.", /* 82 */
    "Raises Attack upon taking\na critical hit.", /* 83 */
    "Raises Speed if a held\nitem is used.", /* 84 */
    "Weakens the power of\nFire-type moves.", /* 85 */
    "The Pokémon is prone to\nwild stat changes.", /* 86 */
    "Reduces HP if it is hot.\nWater restores HP.", /* 87 */
    "Adjusts power according\nto the foe’s ability.", /* 88 */
    "Boosts the power of\npunching moves.", /* 89 */
    "Restores HP if the\nPokémon is poisoned.", /* 90 */
    "Powers up moves of the\nsame type.", /* 91 */
    "Increases the frequency\nof multi-strike moves.", /* 92 */
    "Heals status problems if\nit is raining.", /* 93 */
    "Boosts Sp. Atk, but\nlowers HP in sunshine.", /* 94 */
    "Boosts Speed if there is a\nstatus problem.", /* 95 */
    "All the Pokémon’s moves\nbecome the Normal type.", /* 96 */
    "Powers up moves if they\nbecome critical hits.", /* 97 */
    "The Pokémon only takes\ndamage from attacks.", /* 98 */
    "Ensures the Pokémon and\nits foe’s attacks land.", /* 99 */
    "The Pokémon moves after\neven slower foes.", /* 100 */
    "Powers up the Pokémon’s\nweaker moves.", /* 101 */
    "Prevents status problems\nin sunny weather.", /* 102 */
    "The Pokémon can’t use\nany held items.", /* 103 */
    "Moves can be used\nregardless of abilities.", /* 104 */
    "Heightens the critical-hit\nratios of moves.", /* 105 */
    "Damages the foe landing\nthe finishing hit.", /* 106 */
    "Senses the foe’s\ndangerous moves.", /* 107 */
    "Determines what moves\nthe foe has.", /* 108 */
    "Ignores any change in\nability by the foe.", /* 109 */
    "Powers up “not very\neffective” moves.", /* 110 */
    "Powers down super-\neffective moves.", /* 111 */
    "Temporarily halves Attack\nand Speed.", /* 112 */
    "Enables moves to hit\nGhost-type foes.", /* 113 */
    "The Pokémon draws in all\nWater-type moves.", /* 114 */
    "The Pokémon regains HP in\na hailstorm.", /* 115 */
    "Powers down super-\neffective moves.", /* 116 */
    "The Pokémon summons a\nhailstorm in battle.", /* 117 */
    "The Pokémon may gather\nHoney from somewhere.", /* 118 */
    "The Pokémon can check\nthe foe’s held item.", /* 119 */
    "Powers up moves that\nhave recoil damage.", /* 120 */
    "Changes type to match\nthe held Plate.", /* 121 */
    "Powers up party Pokémon\nwhen it is sunny.", /* 122 */
    "Reduces a sleeping foe’s\nHP.", /* 123 */
    "Steals an item when hit by another Pokémon.", /* 124 */
    "Removes added effects to increase move damage.", /* 125 */
    "Makes stat changes have an opposite effect.", /* 126 */
    "Makes the foe nervous and unable to eat Berries.", /* 127 */
    "When its stats are lowered its Attack increases.", /* 128 */
    "Lowers stats when HP becomes half or less.", /* 129 */
    "May disable a move used on the Pokémon.", /* 130 */
    "May heal an ally's status conditions.", /* 131 */
    "Reduces damage done to allies.", /* 132 */
    "Physical attacks lower Defense and raise Speed.", /* 133 */
    "Doubles the Pokémon's weight.", /* 134 */
    "Halves the Pokémon's weight.", /* 135 */
    "Reduces damage when HP is full.", /* 136 */
    "Powers up physical attacks when poisoned.", /* 137 */
    "Powers up special attacks when burned.", /* 138 */
    "May create another Berry after one is used.", /* 139 */
    "Anticipates an ally's attack and dodges it.", /* 140 */
    "Raises one stat and lowers another.", /* 141 */
    "Protects the Pokémon from damage from weather.", /* 142 */
    "May poison targets when a Pokémon makes contact.", /* 143 */
    "Restores a little HP when withdrawn from battle.", /* 144 */
    "Protects the Pokémon from Defense-lowering attacks.", /* 145 */
    "Boosts the Pokémon's Speed in a sandstorm.", /* 146 */
    "Makes status-changing moves more likely to miss.", /* 147 */
    "Boosts move power when the Pokémon moves last.", /* 148 */
    "Comes out disguised as the Pokémon in back.", /* 149 */
    "It transforms itself into the Pokémon it is facing.", /* 150 */
    "Passes through the foe's barrier and strikes.", /* 151 */
    "Contact with this Pokémon spreads this Ability.", /* 152 */
    "Boosts Attack after knocking out any Pokémon.", /* 153 */
    "Raises Attack when hit by a Dark-type move.", /* 154 */
    "Some move types scare it and boost its Speed.", /* 155 */
    "Reflects status- changing moves.", /* 156 */
    "Boosts Attack when hit by a Grass-type move.", /* 157 */
    "Gives priority to a status move.", /* 158 */
    "Boosts certain moves' power in a sandstorm.", /* 159 */
    "Inflicts damage to the Pokémon on contact.", /* 160 */
    "Changes the Pokémon's shape when HP is halved.", /* 161 */
    "Boosts the accuracy of its allies and itself.", /* 162 */
    "Moves can be used regardless of Abilities.", /* 163 */
    "Moves can be used regardless of Abilities.", /* 164 */
};

static const char *const MMO_DISPLAY_MOVE_NAME[MMO_DISPLAY_MOVE_COUNT] = {
    "-", /* 0 MOVE_NONE */
    "Pound", /* 1 MOVE_POUND */
    "Karate Chop", /* 2 MOVE_KARATE_CHOP */
    "DoubleSlap", /* 3 MOVE_DOUBLE_SLAP */
    "Comet Punch", /* 4 MOVE_COMET_PUNCH */
    "Mega Punch", /* 5 MOVE_MEGA_PUNCH */
    "Pay Day", /* 6 MOVE_PAY_DAY */
    "Fire Punch", /* 7 MOVE_FIRE_PUNCH */
    "Ice Punch", /* 8 MOVE_ICE_PUNCH */
    "ThunderPunch", /* 9 MOVE_THUNDER_PUNCH */
    "Scratch", /* 10 MOVE_SCRATCH */
    "ViceGrip", /* 11 MOVE_VICE_GRIP */
    "Guillotine", /* 12 MOVE_GUILLOTINE */
    "Razor Wind", /* 13 MOVE_RAZOR_WIND */
    "Swords Dance", /* 14 MOVE_SWORDS_DANCE */
    "Cut", /* 15 MOVE_CUT */
    "Gust", /* 16 MOVE_GUST */
    "Wing Attack", /* 17 MOVE_WING_ATTACK */
    "Whirlwind", /* 18 MOVE_WHIRLWIND */
    "Fly", /* 19 MOVE_FLY */
    "Bind", /* 20 MOVE_BIND */
    "Slam", /* 21 MOVE_SLAM */
    "Vine Whip", /* 22 MOVE_VINE_WHIP */
    "Stomp", /* 23 MOVE_STOMP */
    "Double Kick", /* 24 MOVE_DOUBLE_KICK */
    "Mega Kick", /* 25 MOVE_MEGA_KICK */
    "Jump Kick", /* 26 MOVE_JUMP_KICK */
    "Rolling Kick", /* 27 MOVE_ROLLING_KICK */
    "Sand-Attack", /* 28 MOVE_SAND_ATTACK */
    "Headbutt", /* 29 MOVE_HEADBUTT */
    "Horn Attack", /* 30 MOVE_HORN_ATTACK */
    "Fury Attack", /* 31 MOVE_FURY_ATTACK */
    "Horn Drill", /* 32 MOVE_HORN_DRILL */
    "Tackle", /* 33 MOVE_TACKLE */
    "Body Slam", /* 34 MOVE_BODY_SLAM */
    "Wrap", /* 35 MOVE_WRAP */
    "Take Down", /* 36 MOVE_TAKE_DOWN */
    "Thrash", /* 37 MOVE_THRASH */
    "Double-Edge", /* 38 MOVE_DOUBLE_EDGE */
    "Tail Whip", /* 39 MOVE_TAIL_WHIP */
    "Poison Sting", /* 40 MOVE_POISON_STING */
    "Twineedle", /* 41 MOVE_TWINEEDLE */
    "Pin Missile", /* 42 MOVE_PIN_MISSILE */
    "Leer", /* 43 MOVE_LEER */
    "Bite", /* 44 MOVE_BITE */
    "Growl", /* 45 MOVE_GROWL */
    "Roar", /* 46 MOVE_ROAR */
    "Sing", /* 47 MOVE_SING */
    "Supersonic", /* 48 MOVE_SUPERSONIC */
    "SonicBoom", /* 49 MOVE_SONIC_BOOM */
    "Disable", /* 50 MOVE_DISABLE */
    "Acid", /* 51 MOVE_ACID */
    "Ember", /* 52 MOVE_EMBER */
    "Flamethrower", /* 53 MOVE_FLAMETHROWER */
    "Mist", /* 54 MOVE_MIST */
    "Water Gun", /* 55 MOVE_WATER_GUN */
    "Hydro Pump", /* 56 MOVE_HYDRO_PUMP */
    "Surf", /* 57 MOVE_SURF */
    "Ice Beam", /* 58 MOVE_ICE_BEAM */
    "Blizzard", /* 59 MOVE_BLIZZARD */
    "Psybeam", /* 60 MOVE_PSYBEAM */
    "BubbleBeam", /* 61 MOVE_BUBBLE_BEAM */
    "Aurora Beam", /* 62 MOVE_AURORA_BEAM */
    "Hyper Beam", /* 63 MOVE_HYPER_BEAM */
    "Peck", /* 64 MOVE_PECK */
    "Drill Peck", /* 65 MOVE_DRILL_PECK */
    "Submission", /* 66 MOVE_SUBMISSION */
    "Low Kick", /* 67 MOVE_LOW_KICK */
    "Counter", /* 68 MOVE_COUNTER */
    "Seismic Toss", /* 69 MOVE_SEISMIC_TOSS */
    "Strength", /* 70 MOVE_STRENGTH */
    "Absorb", /* 71 MOVE_ABSORB */
    "Mega Drain", /* 72 MOVE_MEGA_DRAIN */
    "Leech Seed", /* 73 MOVE_LEECH_SEED */
    "Growth", /* 74 MOVE_GROWTH */
    "Razor Leaf", /* 75 MOVE_RAZOR_LEAF */
    "SolarBeam", /* 76 MOVE_SOLAR_BEAM */
    "PoisonPowder", /* 77 MOVE_POISON_POWDER */
    "Stun Spore", /* 78 MOVE_STUN_SPORE */
    "Sleep Powder", /* 79 MOVE_SLEEP_POWDER */
    "Petal Dance", /* 80 MOVE_PETAL_DANCE */
    "String Shot", /* 81 MOVE_STRING_SHOT */
    "Dragon Rage", /* 82 MOVE_DRAGON_RAGE */
    "Fire Spin", /* 83 MOVE_FIRE_SPIN */
    "ThunderShock", /* 84 MOVE_THUNDER_SHOCK */
    "Thunderbolt", /* 85 MOVE_THUNDERBOLT */
    "Thunder Wave", /* 86 MOVE_THUNDER_WAVE */
    "Thunder", /* 87 MOVE_THUNDER */
    "Rock Throw", /* 88 MOVE_ROCK_THROW */
    "Earthquake", /* 89 MOVE_EARTHQUAKE */
    "Fissure", /* 90 MOVE_FISSURE */
    "Dig", /* 91 MOVE_DIG */
    "Toxic", /* 92 MOVE_TOXIC */
    "Confusion", /* 93 MOVE_CONFUSION */
    "Psychic", /* 94 MOVE_PSYCHIC */
    "Hypnosis", /* 95 MOVE_HYPNOSIS */
    "Meditate", /* 96 MOVE_MEDITATE */
    "Agility", /* 97 MOVE_AGILITY */
    "Quick Attack", /* 98 MOVE_QUICK_ATTACK */
    "Rage", /* 99 MOVE_RAGE */
    "Teleport", /* 100 MOVE_TELEPORT */
    "Night Shade", /* 101 MOVE_NIGHT_SHADE */
    "Mimic", /* 102 MOVE_MIMIC */
    "Screech", /* 103 MOVE_SCREECH */
    "Double Team", /* 104 MOVE_DOUBLE_TEAM */
    "Recover", /* 105 MOVE_RECOVER */
    "Harden", /* 106 MOVE_HARDEN */
    "Minimize", /* 107 MOVE_MINIMIZE */
    "SmokeScreen", /* 108 MOVE_SMOKE_SCREEN */
    "Confuse Ray", /* 109 MOVE_CONFUSE_RAY */
    "Withdraw", /* 110 MOVE_WITHDRAW */
    "Defense Curl", /* 111 MOVE_DEFENSE_CURL */
    "Barrier", /* 112 MOVE_BARRIER */
    "Light Screen", /* 113 MOVE_LIGHT_SCREEN */
    "Haze", /* 114 MOVE_HAZE */
    "Reflect", /* 115 MOVE_REFLECT */
    "Focus Energy", /* 116 MOVE_FOCUS_ENERGY */
    "Bide", /* 117 MOVE_BIDE */
    "Metronome", /* 118 MOVE_METRONOME */
    "Mirror Move", /* 119 MOVE_MIRROR_MOVE */
    "Selfdestruct", /* 120 MOVE_SELFDESTRUCT */
    "Egg Bomb", /* 121 MOVE_EGG_BOMB */
    "Lick", /* 122 MOVE_LICK */
    "Smog", /* 123 MOVE_SMOG */
    "Sludge", /* 124 MOVE_SLUDGE */
    "Bone Club", /* 125 MOVE_BONE_CLUB */
    "Fire Blast", /* 126 MOVE_FIRE_BLAST */
    "Waterfall", /* 127 MOVE_WATERFALL */
    "Clamp", /* 128 MOVE_CLAMP */
    "Swift", /* 129 MOVE_SWIFT */
    "Skull Bash", /* 130 MOVE_SKULL_BASH */
    "Spike Cannon", /* 131 MOVE_SPIKE_CANNON */
    "Constrict", /* 132 MOVE_CONSTRICT */
    "Amnesia", /* 133 MOVE_AMNESIA */
    "Kinesis", /* 134 MOVE_KINESIS */
    "Softboiled", /* 135 MOVE_SOFTBOILED */
    "Hi Jump Kick", /* 136 MOVE_HI_JUMP_KICK */
    "Glare", /* 137 MOVE_GLARE */
    "Dream Eater", /* 138 MOVE_DREAM_EATER */
    "Poison Gas", /* 139 MOVE_POISON_GAS */
    "Barrage", /* 140 MOVE_BARRAGE */
    "Leech Life", /* 141 MOVE_LEECH_LIFE */
    "Lovely Kiss", /* 142 MOVE_LOVELY_KISS */
    "Sky Attack", /* 143 MOVE_SKY_ATTACK */
    "Transform", /* 144 MOVE_TRANSFORM */
    "Bubble", /* 145 MOVE_BUBBLE */
    "Dizzy Punch", /* 146 MOVE_DIZZY_PUNCH */
    "Spore", /* 147 MOVE_SPORE */
    "Flash", /* 148 MOVE_FLASH */
    "Psywave", /* 149 MOVE_PSYWAVE */
    "Splash", /* 150 MOVE_SPLASH */
    "Acid Armor", /* 151 MOVE_ACID_ARMOR */
    "Crabhammer", /* 152 MOVE_CRABHAMMER */
    "Explosion", /* 153 MOVE_EXPLOSION */
    "Fury Swipes", /* 154 MOVE_FURY_SWIPES */
    "Bonemerang", /* 155 MOVE_BONEMERANG */
    "Rest", /* 156 MOVE_REST */
    "Rock Slide", /* 157 MOVE_ROCK_SLIDE */
    "Hyper Fang", /* 158 MOVE_HYPER_FANG */
    "Sharpen", /* 159 MOVE_SHARPEN */
    "Conversion", /* 160 MOVE_CONVERSION */
    "Tri Attack", /* 161 MOVE_TRI_ATTACK */
    "Super Fang", /* 162 MOVE_SUPER_FANG */
    "Slash", /* 163 MOVE_SLASH */
    "Substitute", /* 164 MOVE_SUBSTITUTE */
    "Struggle", /* 165 MOVE_STRUGGLE */
    "Sketch", /* 166 MOVE_SKETCH */
    "Triple Kick", /* 167 MOVE_TRIPLE_KICK */
    "Thief", /* 168 MOVE_THIEF */
    "Spider Web", /* 169 MOVE_SPIDER_WEB */
    "Mind Reader", /* 170 MOVE_MIND_READER */
    "Nightmare", /* 171 MOVE_NIGHTMARE */
    "Flame Wheel", /* 172 MOVE_FLAME_WHEEL */
    "Snore", /* 173 MOVE_SNORE */
    "Curse", /* 174 MOVE_CURSE */
    "Flail", /* 175 MOVE_FLAIL */
    "Conversion 2", /* 176 MOVE_CONVERSION_2 */
    "Aeroblast", /* 177 MOVE_AEROBLAST */
    "Cotton Spore", /* 178 MOVE_COTTON_SPORE */
    "Reversal", /* 179 MOVE_REVERSAL */
    "Spite", /* 180 MOVE_SPITE */
    "Powder Snow", /* 181 MOVE_POWDER_SNOW */
    "Protect", /* 182 MOVE_PROTECT */
    "Mach Punch", /* 183 MOVE_MACH_PUNCH */
    "Scary Face", /* 184 MOVE_SCARY_FACE */
    "Faint Attack", /* 185 MOVE_FAINT_ATTACK */
    "Sweet Kiss", /* 186 MOVE_SWEET_KISS */
    "Belly Drum", /* 187 MOVE_BELLY_DRUM */
    "Sludge Bomb", /* 188 MOVE_SLUDGE_BOMB */
    "Mud-Slap", /* 189 MOVE_MUD_SLAP */
    "Octazooka", /* 190 MOVE_OCTAZOOKA */
    "Spikes", /* 191 MOVE_SPIKES */
    "Zap Cannon", /* 192 MOVE_ZAP_CANNON */
    "Foresight", /* 193 MOVE_FORESIGHT */
    "Destiny Bond", /* 194 MOVE_DESTINY_BOND */
    "Perish Song", /* 195 MOVE_PERISH_SONG */
    "Icy Wind", /* 196 MOVE_ICY_WIND */
    "Detect", /* 197 MOVE_DETECT */
    "Bone Rush", /* 198 MOVE_BONE_RUSH */
    "Lock-On", /* 199 MOVE_LOCK_ON */
    "Outrage", /* 200 MOVE_OUTRAGE */
    "Sandstorm", /* 201 MOVE_SANDSTORM */
    "Giga Drain", /* 202 MOVE_GIGA_DRAIN */
    "Endure", /* 203 MOVE_ENDURE */
    "Charm", /* 204 MOVE_CHARM */
    "Rollout", /* 205 MOVE_ROLLOUT */
    "False Swipe", /* 206 MOVE_FALSE_SWIPE */
    "Swagger", /* 207 MOVE_SWAGGER */
    "Milk Drink", /* 208 MOVE_MILK_DRINK */
    "Spark", /* 209 MOVE_SPARK */
    "Fury Cutter", /* 210 MOVE_FURY_CUTTER */
    "Steel Wing", /* 211 MOVE_STEEL_WING */
    "Mean Look", /* 212 MOVE_MEAN_LOOK */
    "Attract", /* 213 MOVE_ATTRACT */
    "Sleep Talk", /* 214 MOVE_SLEEP_TALK */
    "Heal Bell", /* 215 MOVE_HEAL_BELL */
    "Return", /* 216 MOVE_RETURN */
    "Present", /* 217 MOVE_PRESENT */
    "Frustration", /* 218 MOVE_FRUSTRATION */
    "Safeguard", /* 219 MOVE_SAFEGUARD */
    "Pain Split", /* 220 MOVE_PAIN_SPLIT */
    "Sacred Fire", /* 221 MOVE_SACRED_FIRE */
    "Magnitude", /* 222 MOVE_MAGNITUDE */
    "DynamicPunch", /* 223 MOVE_DYNAMIC_PUNCH */
    "Megahorn", /* 224 MOVE_MEGAHORN */
    "DragonBreath", /* 225 MOVE_DRAGON_BREATH */
    "Baton Pass", /* 226 MOVE_BATON_PASS */
    "Encore", /* 227 MOVE_ENCORE */
    "Pursuit", /* 228 MOVE_PURSUIT */
    "Rapid Spin", /* 229 MOVE_RAPID_SPIN */
    "Sweet Scent", /* 230 MOVE_SWEET_SCENT */
    "Iron Tail", /* 231 MOVE_IRON_TAIL */
    "Metal Claw", /* 232 MOVE_METAL_CLAW */
    "Vital Throw", /* 233 MOVE_VITAL_THROW */
    "Morning Sun", /* 234 MOVE_MORNING_SUN */
    "Synthesis", /* 235 MOVE_SYNTHESIS */
    "Moonlight", /* 236 MOVE_MOONLIGHT */
    "Hidden Power", /* 237 MOVE_HIDDEN_POWER */
    "Cross Chop", /* 238 MOVE_CROSS_CHOP */
    "Twister", /* 239 MOVE_TWISTER */
    "Rain Dance", /* 240 MOVE_RAIN_DANCE */
    "Sunny Day", /* 241 MOVE_SUNNY_DAY */
    "Crunch", /* 242 MOVE_CRUNCH */
    "Mirror Coat", /* 243 MOVE_MIRROR_COAT */
    "Psych Up", /* 244 MOVE_PSYCH_UP */
    "ExtremeSpeed", /* 245 MOVE_EXTREME_SPEED */
    "AncientPower", /* 246 MOVE_ANCIENT_POWER */
    "Shadow Ball", /* 247 MOVE_SHADOW_BALL */
    "Future Sight", /* 248 MOVE_FUTURE_SIGHT */
    "Rock Smash", /* 249 MOVE_ROCK_SMASH */
    "Whirlpool", /* 250 MOVE_WHIRLPOOL */
    "Beat Up", /* 251 MOVE_BEAT_UP */
    "Fake Out", /* 252 MOVE_FAKE_OUT */
    "Uproar", /* 253 MOVE_UPROAR */
    "Stockpile", /* 254 MOVE_STOCKPILE */
    "Spit Up", /* 255 MOVE_SPIT_UP */
    "Swallow", /* 256 MOVE_SWALLOW */
    "Heat Wave", /* 257 MOVE_HEAT_WAVE */
    "Hail", /* 258 MOVE_HAIL */
    "Torment", /* 259 MOVE_TORMENT */
    "Flatter", /* 260 MOVE_FLATTER */
    "Will-O-Wisp", /* 261 MOVE_WILL_O_WISP */
    "Memento", /* 262 MOVE_MEMENTO */
    "Facade", /* 263 MOVE_FACADE */
    "Focus Punch", /* 264 MOVE_FOCUS_PUNCH */
    "SmellingSalt", /* 265 MOVE_SMELLING_SALT */
    "Follow Me", /* 266 MOVE_FOLLOW_ME */
    "Nature Power", /* 267 MOVE_NATURE_POWER */
    "Charge", /* 268 MOVE_CHARGE */
    "Taunt", /* 269 MOVE_TAUNT */
    "Helping Hand", /* 270 MOVE_HELPING_HAND */
    "Trick", /* 271 MOVE_TRICK */
    "Role Play", /* 272 MOVE_ROLE_PLAY */
    "Wish", /* 273 MOVE_WISH */
    "Assist", /* 274 MOVE_ASSIST */
    "Ingrain", /* 275 MOVE_INGRAIN */
    "Superpower", /* 276 MOVE_SUPERPOWER */
    "Magic Coat", /* 277 MOVE_MAGIC_COAT */
    "Recycle", /* 278 MOVE_RECYCLE */
    "Revenge", /* 279 MOVE_REVENGE */
    "Brick Break", /* 280 MOVE_BRICK_BREAK */
    "Yawn", /* 281 MOVE_YAWN */
    "Knock Off", /* 282 MOVE_KNOCK_OFF */
    "Endeavor", /* 283 MOVE_ENDEAVOR */
    "Eruption", /* 284 MOVE_ERUPTION */
    "Skill Swap", /* 285 MOVE_SKILL_SWAP */
    "Imprison", /* 286 MOVE_IMPRISON */
    "Refresh", /* 287 MOVE_REFRESH */
    "Grudge", /* 288 MOVE_GRUDGE */
    "Snatch", /* 289 MOVE_SNATCH */
    "Secret Power", /* 290 MOVE_SECRET_POWER */
    "Dive", /* 291 MOVE_DIVE */
    "Arm Thrust", /* 292 MOVE_ARM_THRUST */
    "Camouflage", /* 293 MOVE_CAMOUFLAGE */
    "Tail Glow", /* 294 MOVE_TAIL_GLOW */
    "Luster Purge", /* 295 MOVE_LUSTER_PURGE */
    "Mist Ball", /* 296 MOVE_MIST_BALL */
    "FeatherDance", /* 297 MOVE_FEATHER_DANCE */
    "Teeter Dance", /* 298 MOVE_TEETER_DANCE */
    "Blaze Kick", /* 299 MOVE_BLAZE_KICK */
    "Mud Sport", /* 300 MOVE_MUD_SPORT */
    "Ice Ball", /* 301 MOVE_ICE_BALL */
    "Needle Arm", /* 302 MOVE_NEEDLE_ARM */
    "Slack Off", /* 303 MOVE_SLACK_OFF */
    "Hyper Voice", /* 304 MOVE_HYPER_VOICE */
    "Poison Fang", /* 305 MOVE_POISON_FANG */
    "Crush Claw", /* 306 MOVE_CRUSH_CLAW */
    "Blast Burn", /* 307 MOVE_BLAST_BURN */
    "Hydro Cannon", /* 308 MOVE_HYDRO_CANNON */
    "Meteor Mash", /* 309 MOVE_METEOR_MASH */
    "Astonish", /* 310 MOVE_ASTONISH */
    "Weather Ball", /* 311 MOVE_WEATHER_BALL */
    "Aromatherapy", /* 312 MOVE_AROMATHERAPY */
    "Fake Tears", /* 313 MOVE_FAKE_TEARS */
    "Air Cutter", /* 314 MOVE_AIR_CUTTER */
    "Overheat", /* 315 MOVE_OVERHEAT */
    "Odor Sleuth", /* 316 MOVE_ODOR_SLEUTH */
    "Rock Tomb", /* 317 MOVE_ROCK_TOMB */
    "Silver Wind", /* 318 MOVE_SILVER_WIND */
    "Metal Sound", /* 319 MOVE_METAL_SOUND */
    "GrassWhistle", /* 320 MOVE_GRASS_WHISTLE */
    "Tickle", /* 321 MOVE_TICKLE */
    "Cosmic Power", /* 322 MOVE_COSMIC_POWER */
    "Water Spout", /* 323 MOVE_WATER_SPOUT */
    "Signal Beam", /* 324 MOVE_SIGNAL_BEAM */
    "Shadow Punch", /* 325 MOVE_SHADOW_PUNCH */
    "Extrasensory", /* 326 MOVE_EXTRASENSORY */
    "Sky Uppercut", /* 327 MOVE_SKY_UPPERCUT */
    "Sand Tomb", /* 328 MOVE_SAND_TOMB */
    "Sheer Cold", /* 329 MOVE_SHEER_COLD */
    "Muddy Water", /* 330 MOVE_MUDDY_WATER */
    "Bullet Seed", /* 331 MOVE_BULLET_SEED */
    "Aerial Ace", /* 332 MOVE_AERIAL_ACE */
    "Icicle Spear", /* 333 MOVE_ICICLE_SPEAR */
    "Iron Defense", /* 334 MOVE_IRON_DEFENSE */
    "Block", /* 335 MOVE_BLOCK */
    "Howl", /* 336 MOVE_HOWL */
    "Dragon Claw", /* 337 MOVE_DRAGON_CLAW */
    "Frenzy Plant", /* 338 MOVE_FRENZY_PLANT */
    "Bulk Up", /* 339 MOVE_BULK_UP */
    "Bounce", /* 340 MOVE_BOUNCE */
    "Mud Shot", /* 341 MOVE_MUD_SHOT */
    "Poison Tail", /* 342 MOVE_POISON_TAIL */
    "Covet", /* 343 MOVE_COVET */
    "Volt Tackle", /* 344 MOVE_VOLT_TACKLE */
    "Magical Leaf", /* 345 MOVE_MAGICAL_LEAF */
    "Water Sport", /* 346 MOVE_WATER_SPORT */
    "Calm Mind", /* 347 MOVE_CALM_MIND */
    "Leaf Blade", /* 348 MOVE_LEAF_BLADE */
    "Dragon Dance", /* 349 MOVE_DRAGON_DANCE */
    "Rock Blast", /* 350 MOVE_ROCK_BLAST */
    "Shock Wave", /* 351 MOVE_SHOCK_WAVE */
    "Water Pulse", /* 352 MOVE_WATER_PULSE */
    "Doom Desire", /* 353 MOVE_DOOM_DESIRE */
    "Psycho Boost", /* 354 MOVE_PSYCHO_BOOST */
    "Roost", /* 355 MOVE_ROOST */
    "Gravity", /* 356 MOVE_GRAVITY */
    "Miracle Eye", /* 357 MOVE_MIRACLE_EYE */
    "Wake-Up Slap", /* 358 MOVE_WAKE_UP_SLAP */
    "Hammer Arm", /* 359 MOVE_HAMMER_ARM */
    "Gyro Ball", /* 360 MOVE_GYRO_BALL */
    "Healing Wish", /* 361 MOVE_HEALING_WISH */
    "Brine", /* 362 MOVE_BRINE */
    "Natural Gift", /* 363 MOVE_NATURAL_GIFT */
    "Feint", /* 364 MOVE_FEINT */
    "Pluck", /* 365 MOVE_PLUCK */
    "Tailwind", /* 366 MOVE_TAILWIND */
    "Acupressure", /* 367 MOVE_ACUPRESSURE */
    "Metal Burst", /* 368 MOVE_METAL_BURST */
    "U-turn", /* 369 MOVE_U_TURN */
    "Close Combat", /* 370 MOVE_CLOSE_COMBAT */
    "Payback", /* 371 MOVE_PAYBACK */
    "Assurance", /* 372 MOVE_ASSURANCE */
    "Embargo", /* 373 MOVE_EMBARGO */
    "Fling", /* 374 MOVE_FLING */
    "Psycho Shift", /* 375 MOVE_PSYCHO_SHIFT */
    "Trump Card", /* 376 MOVE_TRUMP_CARD */
    "Heal Block", /* 377 MOVE_HEAL_BLOCK */
    "Wring Out", /* 378 MOVE_WRING_OUT */
    "Power Trick", /* 379 MOVE_POWER_TRICK */
    "Gastro Acid", /* 380 MOVE_GASTRO_ACID */
    "Lucky Chant", /* 381 MOVE_LUCKY_CHANT */
    "Me First", /* 382 MOVE_ME_FIRST */
    "Copycat", /* 383 MOVE_COPYCAT */
    "Power Swap", /* 384 MOVE_POWER_SWAP */
    "Guard Swap", /* 385 MOVE_GUARD_SWAP */
    "Punishment", /* 386 MOVE_PUNISHMENT */
    "Last Resort", /* 387 MOVE_LAST_RESORT */
    "Worry Seed", /* 388 MOVE_WORRY_SEED */
    "Sucker Punch", /* 389 MOVE_SUCKER_PUNCH */
    "Toxic Spikes", /* 390 MOVE_TOXIC_SPIKES */
    "Heart Swap", /* 391 MOVE_HEART_SWAP */
    "Aqua Ring", /* 392 MOVE_AQUA_RING */
    "Magnet Rise", /* 393 MOVE_MAGNET_RISE */
    "Flare Blitz", /* 394 MOVE_FLARE_BLITZ */
    "Force Palm", /* 395 MOVE_FORCE_PALM */
    "Aura Sphere", /* 396 MOVE_AURA_SPHERE */
    "Rock Polish", /* 397 MOVE_ROCK_POLISH */
    "Poison Jab", /* 398 MOVE_POISON_JAB */
    "Dark Pulse", /* 399 MOVE_DARK_PULSE */
    "Night Slash", /* 400 MOVE_NIGHT_SLASH */
    "Aqua Tail", /* 401 MOVE_AQUA_TAIL */
    "Seed Bomb", /* 402 MOVE_SEED_BOMB */
    "Air Slash", /* 403 MOVE_AIR_SLASH */
    "X-Scissor", /* 404 MOVE_X_SCISSOR */
    "Bug Buzz", /* 405 MOVE_BUG_BUZZ */
    "Dragon Pulse", /* 406 MOVE_DRAGON_PULSE */
    "Dragon Rush", /* 407 MOVE_DRAGON_RUSH */
    "Power Gem", /* 408 MOVE_POWER_GEM */
    "Drain Punch", /* 409 MOVE_DRAIN_PUNCH */
    "Vacuum Wave", /* 410 MOVE_VACUUM_WAVE */
    "Focus Blast", /* 411 MOVE_FOCUS_BLAST */
    "Energy Ball", /* 412 MOVE_ENERGY_BALL */
    "Brave Bird", /* 413 MOVE_BRAVE_BIRD */
    "Earth Power", /* 414 MOVE_EARTH_POWER */
    "Switcheroo", /* 415 MOVE_SWITCHEROO */
    "Giga Impact", /* 416 MOVE_GIGA_IMPACT */
    "Nasty Plot", /* 417 MOVE_NASTY_PLOT */
    "Bullet Punch", /* 418 MOVE_BULLET_PUNCH */
    "Avalanche", /* 419 MOVE_AVALANCHE */
    "Ice Shard", /* 420 MOVE_ICE_SHARD */
    "Shadow Claw", /* 421 MOVE_SHADOW_CLAW */
    "Thunder Fang", /* 422 MOVE_THUNDER_FANG */
    "Ice Fang", /* 423 MOVE_ICE_FANG */
    "Fire Fang", /* 424 MOVE_FIRE_FANG */
    "Shadow Sneak", /* 425 MOVE_SHADOW_SNEAK */
    "Mud Bomb", /* 426 MOVE_MUD_BOMB */
    "Psycho Cut", /* 427 MOVE_PSYCHO_CUT */
    "Zen Headbutt", /* 428 MOVE_ZEN_HEADBUTT */
    "Mirror Shot", /* 429 MOVE_MIRROR_SHOT */
    "Flash Cannon", /* 430 MOVE_FLASH_CANNON */
    "Rock Climb", /* 431 MOVE_ROCK_CLIMB */
    "Defog", /* 432 MOVE_DEFOG */
    "Trick Room", /* 433 MOVE_TRICK_ROOM */
    "Draco Meteor", /* 434 MOVE_DRACO_METEOR */
    "Discharge", /* 435 MOVE_DISCHARGE */
    "Lava Plume", /* 436 MOVE_LAVA_PLUME */
    "Leaf Storm", /* 437 MOVE_LEAF_STORM */
    "Power Whip", /* 438 MOVE_POWER_WHIP */
    "Rock Wrecker", /* 439 MOVE_ROCK_WRECKER */
    "Cross Poison", /* 440 MOVE_CROSS_POISON */
    "Gunk Shot", /* 441 MOVE_GUNK_SHOT */
    "Iron Head", /* 442 MOVE_IRON_HEAD */
    "Magnet Bomb", /* 443 MOVE_MAGNET_BOMB */
    "Stone Edge", /* 444 MOVE_STONE_EDGE */
    "Captivate", /* 445 MOVE_CAPTIVATE */
    "Stealth Rock", /* 446 MOVE_STEALTH_ROCK */
    "Grass Knot", /* 447 MOVE_GRASS_KNOT */
    "Chatter", /* 448 MOVE_CHATTER */
    "Judgment", /* 449 MOVE_JUDGMENT */
    "Bug Bite", /* 450 MOVE_BUG_BITE */
    "Charge Beam", /* 451 MOVE_CHARGE_BEAM */
    "Wood Hammer", /* 452 MOVE_WOOD_HAMMER */
    "Aqua Jet", /* 453 MOVE_AQUA_JET */
    "Attack Order", /* 454 MOVE_ATTACK_ORDER */
    "Defend Order", /* 455 MOVE_DEFEND_ORDER */
    "Heal Order", /* 456 MOVE_HEAL_ORDER */
    "Head Smash", /* 457 MOVE_HEAD_SMASH */
    "Double Hit", /* 458 MOVE_DOUBLE_HIT */
    "Roar of Time", /* 459 MOVE_ROAR_OF_TIME */
    "Spacial Rend", /* 460 MOVE_SPACIAL_REND */
    "Lunar Dance", /* 461 MOVE_LUNAR_DANCE */
    "Crush Grip", /* 462 MOVE_CRUSH_GRIP */
    "Magma Storm", /* 463 MOVE_MAGMA_STORM */
    "Dark Void", /* 464 MOVE_DARK_VOID */
    "Seed Flare", /* 465 MOVE_SEED_FLARE */
    "Ominous Wind", /* 466 MOVE_OMINOUS_WIND */
    "Shadow Force", /* 467 MOVE_SHADOW_FORCE */
};

static const char *const MMO_DISPLAY_MOVE_DESC[MMO_DISPLAY_MOVE_COUNT] = {
    "\n\n\n\n", /* 0 */
    "The foe is physically\npounded with a long\ntail or a foreleg,\netc.\n", /* 1 */
    "The foe is attacked\nwith a sharp chop.\nIt has a high\ncritical-hit ratio.\n", /* 2 */
    "The foe is slapped\nrepeatedly, back\nand forth, two to\nfive times in a row.\n", /* 3 */
    "The foe is hit with\na flurry of punches\nthat strike two to\nfive times in a row.\n", /* 4 */
    "The foe is slugged\nby a punch thrown\nwith muscle-packed\npower.\n", /* 5 */
    "Numerous coins are\nhurled at the foe to\ninflict damage.\nMoney is earned\nafter battle.", /* 6 */
    "The foe is punched\nwith a fiery fist.\nIt may leave the\ntarget with a burn.\n", /* 7 */
    "The foe is punched\nwith an icy fist.\nIt may leave the\ntarget frozen.\n", /* 8 */
    "The foe is punched\nwith an electrified\nfist. It may leave\nthe target with\nparalysis.", /* 9 */
    "Hard, pointed, and\nsharp claws rake the\nfoe to inflict damage.\n\n", /* 10 */
    "Huge, impressive\npincers grip and\nsqueeze the foe.\n\n", /* 11 */
    "A vicious, tearing\nattack with pincers.\nThe foe will faint\ninstantly if this\nattack hits.", /* 12 */
    "A two-turn attack.\nBlades of wind hit the\nfoe on the second\nturn. It has a high\ncritical-hit ratio.", /* 13 */
    "A frenetic dance to\nuplift the fighting\nspirit. It sharply\nraises the user’s\nAttack stat.", /* 14 */
    "The foe is cut with a\nscythe or a claw.\nIt can also be used\nto cut down thin\ntrees.", /* 15 */
    "A gust of wind is\nwhipped up by wings\nand launched at the\nfoe to inflict damage.\n", /* 16 */
    "The foe is struck\nwith large, imposing\nwings spread wide\nto inflict damage.\n", /* 17 */
    "The foe is blown away,\nto be replaced by\nanother Pokémon\nin its party. In the\nwild, the battle ends.", /* 18 */
    "The user soars, then\nstrikes on the second\nturn. It can also be\nused for flying to\nany familiar town.", /* 19 */
    "A long body or\ntentacles are used\nto bind and squeeze\nthe foe for two to\nfive turns.", /* 20 */
    "The foe is slammed\nwith a long tail,\nvines, etc., to inflict\ndamage.\n", /* 21 */
    "The foe is struck\nwith slender, whiplike\nvines to inflict\ndamage.\n", /* 22 */
    "The foe is stomped\nwith a big foot.\nIt may also make the\ntarget flinch.\n", /* 23 */
    "The foe is quickly\nkicked twice in\nsuccession using both\nfeet.\n", /* 24 */
    "The foe is attacked\nby a kick launched\nwith muscle-packed\npower.\n", /* 25 */
    "The user jumps up\nhigh, then strikes\nwith a kick. If the\nkick misses, the\nuser hurts itself.", /* 26 */
    "The user cuts a\nquick spin and lashes\nout with a sharp\nkick.\n", /* 27 */
    "Sand is hurled in the\nfoe’s face, reducing\nits accuracy.\n\n", /* 28 */
    "The user sticks its\nhead out and rams\nstraight forward.\nIt may make the\nfoe flinch.", /* 29 */
    "The foe is jabbed\nwith a sharply\npointed horn to\ninflict damage.\n", /* 30 */
    "The foe is jabbed\nrepeatedly with a\nhorn or beak two to\nfive times in a row.\n", /* 31 */
    "The foe is stabbed\nwith a horn rotating\nlike a drill.\nThe foe instantly\nfaints if it hits.", /* 32 */
    "A physical attack\nin which the user\ncharges and slams\ninto the foe with\nits whole body.", /* 33 */
    "The user drops onto\nthe foe with its full\nbody weight.\nIt may leave the foe\nparalyzed.", /* 34 */
    "A long body or vines\nare used to wrap and\nsqueeze the foe for\ntwo to five turns.\n", /* 35 */
    "A reckless, full-body\ncharge attack for\nslamming into the foe.\nIt also damages the\nuser a little.", /* 36 */
    "The user rampages\nand attacks for two\nto three turns.\nIt then becomes\nconfused, however.", /* 37 */
    "A reckless, life-\nrisking tackle.\nIt also damages the\nuser by a fairly large\namount, however.", /* 38 */
    "The user wags its tail\ncutely, making the\nfoe less wary.\nThe target’s Defense\nstat is lowered.", /* 39 */
    "The foe is stabbed\nwith a poisonous\nbarb of some sort.\nIt may also poison\nthe target.", /* 40 */
    "The foe is stabbed\ntwice by a pair of\nstingers.\nIt may also poison\nthe target.", /* 41 */
    "Sharp pins are shot\nat the foe in rapid\nsuccession.\nThey hit two to five\ntimes in a row.", /* 42 */
    "The foe is given an\nintimidating leer with\nsharp eyes.\nThe target’s Defense\nstat is reduced.", /* 43 */
    "The foe is bitten with\nviciously sharp fangs.\nIt may make the\ntarget flinch.\n", /* 44 */
    "The user growls in an\nendearing way, making\nthe foe less wary.\nThe target’s Attack\nstat is lowered.", /* 45 */
    "The foe is scared off,\nto be replaced by\nanother Pokémon in\nits party. In the\nwild, the battle ends.", /* 46 */
    "A soothing lullaby is\nsung in a calming\nvoice that puts the\nfoe into a deep\nslumber.", /* 47 */
    "The user generates\nodd sound waves from\nits body.\nIt may confuse the\ntarget.", /* 48 */
    "The foe is hit with a\ndestructive shock\nwave that always\ninflicts 20 HP damage.\n", /* 49 */
    "For several turns,\nthis move prevents\nthe foe from using\nthe move it last\nused.", /* 50 */
    "The foe is attacked\nwith a spray of harsh\nacid. It may also\nlower the target’s\nSp. Def stat.", /* 51 */
    "The foe is attacked\nwith small flames.\nThe target may also\nbe left with a burn.\n", /* 52 */
    "The foe is scorched\nwith an intense blast\nof fire. The target\nmay also be left with\na burn.", /* 53 */
    "The user cloaks its\nbody with a white mist\nthat prevents any of\nits stats from being\ncut for five turns.", /* 54 */
    "The foe is blasted\nwith a forceful shot\nof water.\n\n", /* 55 */
    "The foe is blasted by\na huge volume of\nwater launched under\ngreat pressure.\n", /* 56 */
    "It swamps the entire\nbattlefield with a\ngiant wave.\nIt can also be used\nfor crossing water.", /* 57 */
    "The foe is struck\nwith an icy-cold\nbeam of energy.\nIt may also freeze\nthe target solid.", /* 58 */
    "A howling blizzard is\nsummoned to strike\nthe foe.\nIt may also freeze\nthe target solid.", /* 59 */
    "The foe is attacked\nwith a peculiar ray.\nIt may also leave the\ntarget confused.\n", /* 60 */
    "A spray of bubbles is\nforcefully ejected\nat the foe.\nIt may also lower the\ntarget’s Speed stat.", /* 61 */
    "The foe is hit with a\nrainbow-colored beam.\nIt may also lower the\ntarget’s Attack\nstat.", /* 62 */
    "The foe is attacked\nwith a powerful beam.\nThe user must rest\non the next turn to\nregain its energy.", /* 63 */
    "The foe is jabbed\nwith a sharply\npointed beak or\nhorn.\n", /* 64 */
    "A corkscrewing\nattack with the\nsharp beak acting\nas a drill.\n", /* 65 */
    "The user grabs the\nfoe and recklessly\ndives for the ground.\nIt also hurts the\nuser slightly.", /* 66 */
    "A powerful low kick\nthat makes the foe\nfall over. It inflicts\ngreater damage on\nheavier foes.", /* 67 */
    "A retaliation move\nthat counters any\nphysical attack,\ninflicting double the\ndamage taken.", /* 68 */
    "The foe is thrown\nusing the power of\ngravity. It inflicts\ndamage equal to\nthe user’s level.", /* 69 */
    "The foe is slugged\nwith a punch thrown\nat maximum power.\nIt can also be used\nto move boulders.", /* 70 */
    "A nutrient-draining\nattack. The user’s\nHP is restored by\nhalf the damage taken\nby the target.", /* 71 */
    "A nutrient-draining\nattack. The user’s\nHP is restored by\nhalf the damage taken\nby the target.", /* 72 */
    "A seed is planted on\nthe foe. It steals\nsome HP from the foe\nto heal the user on\nevery turn.", /* 73 */
    "The user’s body is\nforced to grow all at\nonce. It raises the\nSp. Atk stat.\n", /* 74 */
    "Sharp-edged leaves\nare launched to slash\nat the foe. It has a\nhigh critical-hit\nratio.", /* 75 */
    "A two-turn attack.\nThe user gathers\nlight, then blasts a\nbundled beam on the\nsecond turn.", /* 76 */
    "A cloud of poisonous\ndust is scattered on\nthe foe.\nIt may poison the\ntarget.", /* 77 */
    "The user scatters a\ncloud of paralyzing\npowder.\nIt may paralyze the\ntarget.", /* 78 */
    "The user scatters a\nbig cloud of sleep-\ninducing dust around\nthe foe.\n", /* 79 */
    "The user attacks by\nscattering petals for\ntwo to three turns.\nThe user then\nbecomes confused.", /* 80 */
    "The foe is bound with\nsilk blown from the\nuser’s mouth.\nIt reduces the\ntarget’s Speed stat.", /* 81 */
    "The foe is stricken\nby a shock wave.\nThis attack always\ninflicts 40 HP\ndamage.", /* 82 */
    "The foe becomes\ntrapped within a\nfierce vortex of fire\nthat rages for two\nto five turns.", /* 83 */
    "A jolt of electricity\nis hurled at the foe\nto inflict damage.\nIt may also leave the\nfoe paralyzed.", /* 84 */
    "A strong electric\nblast is loosed at\nthe foe.\nIt may also leave the\nfoe paralyzed.", /* 85 */
    "A weak electric\ncharge is launched at\nthe foe.\nIt causes paralysis if\nit hits.", /* 86 */
    "A wicked thunderbolt\nis dropped on the foe\nto inflict damage.\nIt may also leave the\ntarget paralyzed.", /* 87 */
    "The user picks up\nand throws a small\nrock at the foe to\nattack.\n", /* 88 */
    "The user sets off an\nearthquake that hits\nall the Pokémon in\nthe battle.\n", /* 89 */
    "The user opens up a\nfissure in the ground\nand drops the foe in.\nThe target instantly\nfaints if it hits.", /* 90 */
    "The user burrows,\nthen attacks on the\nsecond turn.\nIt can also be used\nto exit dungeons.", /* 91 */
    "A move that leaves\nthe target badly\npoisoned.\nIts poison damage\nworsens every turn.", /* 92 */
    "The foe is hit by a\nweak telekinetic\nforce. It may also\nleave the foe\nconfused.", /* 93 */
    "The foe is hit by a\nstrong telekinetic\nforce. It may also\nreduce the foe’s\nSp. Def stat.", /* 94 */
    "The user employs\nhypnotic suggestion\nto make the target\nfall into a deep\nsleep.", /* 95 */
    "The user meditates\nto awaken the power\ndeep within its body\nand raise its Attack\nstat.", /* 96 */
    "The user relaxes and\nlightens its body to\nmove faster.\nIt sharply boosts\nthe Speed stat.", /* 97 */
    "The user lunges at\nthe foe at a speed\nthat makes it almost\ninvisible. It is sure\nto strike first.", /* 98 */
    "While this move is in\nuse, it gains attack\npower each time the\nuser is hit in battle.\n", /* 99 */
    "Use it to flee from\nany wild Pokémon.\nIt may also be used\nto warp to the last\nPoké Center visited.", /* 100 */
    "The user makes the\nfoe see a mirage.\nIt inflicts damage\nmatching the user’s\nlevel.", /* 101 */
    "The user copies the\nmove last used by\nthe foe. The move can\nbe used for the rest\nof the battle.", /* 102 */
    "An earsplitting\nscreech is emitted to\nsharply reduce the\nfoe’s Defense stat.\n", /* 103 */
    "By moving rapidly, the\nuser makes illusory\ncopies of itself to\nraise its evasiveness.\n", /* 104 */
    "A self-healing move.\nThe user restores its\nown HP by up to half\nof its max HP.\n", /* 105 */
    "The user stiffens all\nthe muscles in its\nbody to raise its\nDefense stat.\n", /* 106 */
    "The user compresses\nits body to make\nitself look smaller.\nThe user’s evasion\nstat is boosted.", /* 107 */
    "The user releases an\nobscuring cloud of\nsmoke or ink.\nIt reduces the foe’s\naccuracy.", /* 108 */
    "The foe is exposed\nto a sinister ray\nthat triggers\nconfusion.\n", /* 109 */
    "The user withdraws\nits body into its hard\nshell, raising its\nDefense stat.\n", /* 110 */
    "The user curls up to\nconceal weak spots\nand raise its Defense\nstat.\n", /* 111 */
    "The user throws up a\nsturdy wall that\nsharply raises its\nDefense stat.\n", /* 112 */
    "A wondrous wall of\nlight is put up to\nsuppress damage from\nspecial attacks for\nfive turns.", /* 113 */
    "The user creates a\nhaze that eliminates\nevery stat change\namong all the Pokémon\nengaged in battle.", /* 114 */
    "A wondrous wall of\nlight is put up to\nsuppress damage from\nphysical attacks for\nfive turns.", /* 115 */
    "The user takes a\ndeep breath and\nfocuses to raise the\ncritical-hit ratio of\nits attacks.", /* 116 */
    "The user endures\nattacks for two\nturns, then strikes\nback to cause double\nthe damage taken.", /* 117 */
    "The user waggles a\nfinger and stimulates\nthe brain into\nrandomly using nearly\nany move.", /* 118 */
    "The user counters\nthe foe by mimicking\nthe move last used\nby the foe.", /* 119 */
    "The user blows up to\ninflict damage on all\nPokémon in battle.\nThe user faints upon\nusing this move.", /* 120 */
    "A large egg is hurled\nwith maximum force at\nthe foe to inflict\ndamage.\n", /* 121 */
    "The foe is licked with\na long tongue, causing\ndamage.\nIt may also paralyze\nthe target.", /* 122 */
    "The foe is attacked\nwith a discharge of\nfilthy gases.\nIt may also poison\nthe target.", /* 123 */
    "Unsanitary sludge is\nhurled at the foe.\nIt may also poison\nthe target.\n", /* 124 */
    "The user clubs the\nfoe with a bone.\nIt may also make the\ntarget flinch.\n", /* 125 */
    "The foe is attacked\nwith an intense blast\nof all-consuming fire.\nIt may also leave the\ntarget with a burn.", /* 126 */
    "The user charges the\nfoe at an awesome\nspeed.\nIt can also be used\nto climb a waterfall.", /* 127 */
    "The foe is clamped\nand squeezed by\nthe user’s very thick\nand sturdy shell for\ntwo to five turns.", /* 128 */
    "Star-shaped rays are\nshot at the foe.\nThis attack never\nmisses.\n", /* 129 */
    "The user tucks in its\nhead to raise its\nDefense in the first\nturn, then rams the\nfoe on the next turn.", /* 130 */
    "Sharp spikes are\nfired at the foe to\nstrike two to five\ntimes in rapid\nsuccession.", /* 131 */
    "The foe is attacked\nwith long, creeping\ntentacles or vines.\nIt may also lower the\ntarget’s Speed.", /* 132 */
    "The user temporarily\nempties its mind to\nforget its concerns.\nIt sharply raises the\nuser’s Sp. Def stat.", /* 133 */
    "The user distracts\nthe foe by bending a\nspoon.\nIt may lower the\ntarget’s accuracy.", /* 134 */
    "The user restores its\nown HP by up to half\nof its maximum HP.\nIt may also be used\nto heal an ally’s HP.", /* 135 */
    "The foe is attacked\nwith a knee kick from\na jump. If it misses,\nthe user is hurt\ninstead.", /* 136 */
    "The user intimidates\nthe foe with the\npattern on its belly\nto cause paralysis.\n", /* 137 */
    "An attack that works\nonly on a sleeping\nfoe. It absorbs half\nthe damage caused to\nheal the user’s HP.", /* 138 */
    "A cloud of poison gas\nis sprayed in the\nfoe’s face.\nIt may poison the\ntarget.", /* 139 */
    "Round objects are\nhurled at the foe to\nstrike two to five\ntimes in a row.\n", /* 140 */
    "A blood-draining\nattack. The user’s\nHP is restored by\nhalf the damage taken\nby the target.", /* 141 */
    "With a scary face,\nthe user forces a\nkiss on the foe.\nIt may make the\ntarget fall asleep.", /* 142 */
    "A second-turn attack\nmove with a high\ncritical-hit ratio.\nIt may also make the\ntarget flinch.", /* 143 */
    "The user transforms\ninto a copy of the\nfoe right down to\nhaving the same move\nset.", /* 144 */
    "A spray of countless\nbubbles is jetted at\nthe foe.\nIt may also lower the\ntarget’s Speed stat.", /* 145 */
    "The foe is hit with\nrhythmically launched\npunches that may also\nleave it confused.\n", /* 146 */
    "The user scatters\nbursts of spores\nthat induce sleep.\n\n", /* 147 */
    "The user flashes a\nlight that cuts the\nfoe’s accuracy.\nIt can also be used\nto illuminate caves.", /* 148 */
    "The foe is attacked\nwith an odd, hot\nenergy wave.\nThe attack varies in\nintensity.", /* 149 */
    "The user just flops\nand splashes around\nto no effect at all...\n\n", /* 150 */
    "The user alters its\ncellular structure to\nliquefy itself,\nsharply raising its\nDefense stat.", /* 151 */
    "The foe is hammered\nwith a large pincer.\nThis move has a high\ncritical-hit ratio.\n", /* 152 */
    "The user explodes to\ninflict damage on all\nPokémon in battle.\nThe user faints upon\nusing this move.", /* 153 */
    "The foe is raked with\nsharp claws or\nscythes for two to\nfive times in quick\nsuccession.", /* 154 */
    "The user throws the\nbone it holds. The\nbone loops to hit the\nfoe twice, coming and\ngoing.", /* 155 */
    "The user goes to\nsleep for two turns.\nIt fully restores the\nuser’s HP and heals\nany status problem.", /* 156 */
    "Large boulders are\nhurled at the foe to\ninflict damage.\nIt may also make the\ntarget flinch.", /* 157 */
    "The user bites hard\non the foe with its\nsharp front fangs.\nIt may also make the\ntarget flinch.", /* 158 */
    "The user reduces its\npolygon count to\nmake itself more\njagged, raising the\nAttack stat.", /* 159 */
    "The user changes its\ntype to become the\nsame type as one of\nits moves.\n", /* 160 */
    "The user strikes with\na simultaneous three-\nbeam attack. May also\nparalyze, burn, or\nfreeze the target.", /* 161 */
    "The user chomps hard\non the foe with its\nsharp front fangs.\nIt cuts the target’s\nHP to half.", /* 162 */
    "The foe is attacked\nwith a slash of\nclaws, etc.\nIt has a high\ncritical-hit ratio.", /* 163 */
    "The user makes a\ncopy of itself using\nsome of its HP.\nThe copy serves as\nthe user’s decoy.", /* 164 */
    "An attack that is\nused in desperation\nonly if the user has\nno PP. It also hurts\nthe user slightly.", /* 165 */
    "It enables the user\nto learn a move used\nby the foe.\nOnce used, the move\nSketch disappears.", /* 166 */
    "A consecutive three-\nkick attack that\nbecomes more\npowerful with each \nsuccessive hit.", /* 167 */
    "The user attacks and\nsteals the foe’s held\nitem simultaneously.\nIt can’t steal if the\nuser holds an item.", /* 168 */
    "The user ensnares\nthe foe with a thin,\ngooey silk so it can’t\nflee from battle.\n", /* 169 */
    "The user senses the\nfoe’s movements\nwith its mind to\nensure its next\nattack does not miss.", /* 170 */
    "A sleeping foe is\nshown a nightmare\nthat inflicts some\ndamage every turn.\n", /* 171 */
    "The user cloaks\nitself in fire and\ncharges at the foe.\nIt may also leave the\ntarget with a burn.", /* 172 */
    "An attack that can\nbe used only if the\nuser is asleep. The\nharsh noise may also\nmake the foe flinch.", /* 173 */
    "A move that works\ndifferently for the\nGhost type than for\nall the other types.\n", /* 174 */
    "The user flails about\naimlessly to attack.\nIt becomes more\npowerful the less HP\nthe user has.", /* 175 */
    "The user changes its\ntype to make itself\nresistant to the type\nof the attack it\nlast took.", /* 176 */
    "A vortex of air is\nshot at the foe to\ninflict damage.\nIt has a high\ncritical-hit ratio.", /* 177 */
    "The user releases\ncottonlike spores\nthat cling to the\nfoe, sharply reducing\nits Speed stat.", /* 178 */
    "An all-out attack\nthat becomes more\npowerful the less\nHP the user has.\n", /* 179 */
    "The user looses its\ngrudge on the move\nlast used by the foe\nby cutting 4 PP from\nit.", /* 180 */
    "The user attacks with\na chilling gust of\npowdery snow.\nIt may also freeze\nthe target.", /* 181 */
    "It enables the user\nto evade all attacks.\nIts chance of failing\nrises if it is used in\nsuccession.", /* 182 */
    "The user throws a\npunch at blinding\nspeed.\nIt is certain to\nstrike first.", /* 183 */
    "The user frightens\nthe foe with a scary\nface to sharply\nreduce its Speed\nstat.", /* 184 */
    "The user draws up to\nthe foe disarmingly,\nthen throws a sucker\npunch.\nIt hits without fail.", /* 185 */
    "The user kisses the\nfoe with a sweet,\nangelic cuteness that\ncauses confusion.\n", /* 186 */
    "The user maximizes\nits Attack stat in\nexchange for HP\nequal to half its max\nHP.", /* 187 */
    "The user attacks by\nhurling filthy sludge\nat the foe.\nIt may also poison\nthe target.", /* 188 */
    "The user hurls mud in\nthe foe’s face to\ninflict damage and\nlower its accuracy.\n", /* 189 */
    "The user attacks by\nspraying ink in the\nfoe’s face or eyes.\nIt may also lower the\ntarget’s accuracy.", /* 190 */
    "The user lays a trap\nof spikes at the\nfoe’s feet. The trap\nhurts foes that\nswitch into battle.", /* 191 */
    "The user fires an\nelectric blast like a\ncannon to inflict\ndamage and cause\nparalysis.", /* 192 */
    "Enables the user to\nhit a Ghost type with\nany type of move. It\nalso enables the user\nto hit an evasive foe.", /* 193 */
    "When this move is\nused, if the user\nfaints, the foe that\nlanded the knockout\nhit also faints.", /* 194 */
    "Any Pokémon that\nhears this song\nfaints in three turns\nunless it switches\nout of battle.", /* 195 */
    "The user attacks with\na gust of chilled air.\nIt also lowers the\ntarget’s Speed stat.\n", /* 196 */
    "It enables the user\nto evade all attacks.\nIts chance of failing\nrises if it is used in\nsuccession.", /* 197 */
    "The user strikes at\nthe foe with a hard\nbone two to five\ntimes in a row.\n", /* 198 */
    "The user takes sure\naim at the foe.\nIt ensures the next\nattack does not fail\nto hit the target.", /* 199 */
    "The user rampages\nand attacks for two\nto three turns.\nHowever, it then\nbecomes confused.", /* 200 */
    "A five-turn sand-\nstorm is summoned\nto hurt all combatant\ntypes except Rock, \nGround, and Steel.", /* 201 */
    "A nutrient-draining\nattack. The user’s\nHP is restored by\nhalf the damage taken\nby the target.", /* 202 */
    "The user endures any\nattack, leaving 1 HP.\nIts chance of failing\nrises if it is used in\nsuccession.", /* 203 */
    "The user charmingly\nstares at the foe,\nmaking it less wary.\nThe target’s Attack\nis sharply lowered.", /* 204 */
    "The user continually\nrolls into the foe\nover five turns. It\nbecomes stronger\neach time it hits.", /* 205 */
    "A restrained attack\nthat prevents the\nfoe from fainting.\nThe target is left\nwith at least 1 HP.", /* 206 */
    "The user enrages the\nfoe into confusion.\nHowever, it also\nsharply raises the\nfoe’s Attack stat.", /* 207 */
    "The user restores its\nown HP by up to half\nof its maximum HP.\nIt may also be used\nto heal an ally’s HP.", /* 208 */
    "The user throws an\nelectrically charged\ntackle at the foe.\nIt may also leave the\ntarget paralyzed.", /* 209 */
    "The foe is slashed\nwith scythes or\nclaws. Its power\nincreases if it hits\nin succession.", /* 210 */
    "The foe is hit with\nwings of steel.\nIt may also raise the\nuser’s Defense stat.\n", /* 211 */
    "The user affixes the\nfoe with a dark,\narresting look.\nThe target becomes\nunable to flee.", /* 212 */
    "If it is the opposite\ngender of the user,\nthe foe becomes\ninfatuated and less\nlikely to attack.", /* 213 */
    "While it is asleep, the\nuser randomly uses\none of the moves it\nknows.\n", /* 214 */
    "The user makes a\nsoothing bell chime\nto heal the status\nproblems of all the\nparty Pokémon.", /* 215 */
    "A full-power attack\nthat grows more\npowerful the more\nthe user likes its\nTrainer.", /* 216 */
    "The user attacks by\ngiving the foe a\nbooby-trapped gift.\nIt restores HP\nsometimes, however.", /* 217 */
    "A full-power attack\nthat grows more\npowerful the less\nthe user likes its\nTrainer.", /* 218 */
    "The user creates a\nprotective field that\nprevents status\nproblems for five\nturns.", /* 219 */
    "The user adds its HP\nto the foe’s HP, then\nequally shares the\ncombined HP with the\nfoe.", /* 220 */
    "The foe is razed with\na mystical fire of\ngreat intensity.\nIt may also leave the\ntarget with a burn.", /* 221 */
    "The user looses a\nground-shaking quake\naffecting everyone in\nbattle. Its power\nvaries.", /* 222 */
    "The foe is punched\nwith the user’s full,\nconcentrated power.\nIt confuses the foe\nif it hits.", /* 223 */
    "Utilizing its tough\nand impressive\nhorn, the user\nrams into the foe \nwith no letup.\n", /* 224 */
    "The user exhales\na mighty gust that\ninflicts damage.\nIt may also paralyze\nthe target.", /* 225 */
    "The user switches\nplaces with a party\nPokémon in waiting,\npassing along any\nstat changes.", /* 226 */
    "The user compels the\nfoe to keep using\nonly the move it last\nused for three to\nseven turns.", /* 227 */
    "An attack move that\ninflicts double damage\nif used on a foe that\nis switching out of\nbattle.", /* 228 */
    "A spin attack that\ncan also eliminate\nsuch moves as Bind,\nWrap, Leech Seed,\nand Spikes.", /* 229 */
    "A sweet scent that\nlowers the foe’s\nevasiveness. It also\nlures wild Pokémon\nif used in grass, etc.", /* 230 */
    "The foe is slammed\nwith a steel-hard\ntail. It may also\nlower the target’s\nDefense stat.", /* 231 */
    "The foe is raked\nwith steel claws.\nIt may also raise the\nuser’s Attack stat.\n", /* 232 */
    "The user allows the\nfoe to attack first.\nIn return, this throw\nmove is guaranteed\nnot to miss.", /* 233 */
    "The user restores its\nown HP.\nThe amount of HP\nregained varies with\nthe weather.", /* 234 */
    "The user restores its\nown HP.\nThe amount of HP\nregained varies with\nthe weather.", /* 235 */
    "The user restores its\nown HP.\nThe amount of HP\nregained varies with\nthe weather.", /* 236 */
    "A unique attack that\nvaries in type and\nintensity depending\non the Pokémon using\nit.", /* 237 */
    "The user delivers a\ndouble chop with its\nforearms crossed.\nIt has a high\ncritical-hit ratio.", /* 238 */
    "The user whips up a\nvicious twister to\ntear at the foe.\nIt may also make the\nfoe flinch.", /* 239 */
    "The user summons a\nheavy rain that falls\nfor five turns,\npowering up Water-\ntype moves.", /* 240 */
    "The user intensifies\nthe sun for five\nturns, powering up\nFire-type moves.\n", /* 241 */
    "The user crunches up\nthe foe with sharp\nfangs. It may also\nlower the target’s\nDefense stat.", /* 242 */
    "A retaliation move\nthat counters any\nspecial attack,\ninflicting double the\ndamage taken.", /* 243 */
    "The user hypnotizes\nitself into copying\nany stat change\nmade by the foe.\n", /* 244 */
    "The user charges the\nfoe at blinding speed.\nThis attack always\ngoes before any\nother move.", /* 245 */
    "The user attacks with\na prehistoric power.\nIt may also raise all\nthe user’s stats at\nonce.", /* 246 */
    "The user hurls a\nshadowy blob at the\nfoe. It may also\nlower the foe’s\nSp. Def stat.", /* 247 */
    "Two turns after this\nmove is used, the foe\nis attacked with a\nhunk of psychic\nenergy.", /* 248 */
    "The user slugs the\nfoe with a shattering\npunch.\nIt can also smash\ncracked boulders.", /* 249 */
    "The user traps the\nfoe inside a fast,\nvicious whirlpool that\nlasts for two to five\nturns.", /* 250 */
    "The user gets all the\nparty Pokémon to\nattack the foe. The\nmore party Pokémon,\nthe more damage.", /* 251 */
    "An attack that hits\nfirst and makes the\ntarget flinch.\nThis move works only\non the first turn.", /* 252 */
    "The user attacks in\nan uproar for two to\nfive turns. Over that\ntime, no one can fall\nasleep.", /* 253 */
    "The user charges\nup power, and raises\nboth its Defense and\nSp. Def. The move can\nbe used three times.", /* 254 */
    "The power stored\nusing the move\nStockpile is released\nat once in an attack.\n", /* 255 */
    "The power stored\nusing the move\nStockpile is absorbed\nby the user to heal\nits HP.", /* 256 */
    "The user exhales a\nheated breath on the\nfoe to attack. It may\nalso leave the target\nwith a burn.", /* 257 */
    "The user summons a\nhailstorm lasting five\nturns. It damages all\nPokémon except the\nIce type.", /* 258 */
    "The user torments\nand enrages the foe,\nmaking it incapable of\nusing the same move\ntwice in a row.", /* 259 */
    "Flattery is used to\nconfuse the foe.\nHowever, it also\nraises the target’s\nSp. Atk stat.", /* 260 */
    "The user shoots a\nsinister, bluish white\nflame at the foe to\ninflict a burn.\n", /* 261 */
    "The user faints upon\nusing this move.\nIn return, it sharply\nlowers the target’s\nAttack and Sp. Atk.", /* 262 */
    "An attack move that\ndoubles its power if\nthe user is poisoned,\nparalyzed, or has a\nburn.", /* 263 */
    "The user focuses its\nmind before launching\na punch. It will fail\nif the user is hit\nbefore it is used.", /* 264 */
    "This attack inflicts\ndouble damage on a\nparalyzed foe. It\nalso cures the foe’s\nparalysis, however.", /* 265 */
    "The user draws\nattention to itself,\nmaking all foes take\naim only at the user.\n", /* 266 */
    "An attack that makes\nuse of nature’s\npower. Its effects\nvary depending on the\nuser’s environment.", /* 267 */
    "The user boosts the\npower of the Electric\nmove it uses next.\nIt also raises the\nuser’s Sp. Def stat.", /* 268 */
    "The foe is taunted\ninto a rage that\nallows it to use only\nattack moves for two\nto four turns.", /* 269 */
    "A move that boosts\nthe power of the\nally’s attack in a\nDouble Battle.\n", /* 270 */
    "The user catches the\nfoe off guard and\nswaps the foe’s held\nitem with its own.\n", /* 271 */
    "The user mimics the\nfoe completely,\ncopying the foe’s\nnatural ability.\n", /* 272 */
    "A self-healing move.\nThe user restores its\nown HP by up to half\nof its maximum HP\nin the next turn.", /* 273 */
    "The user hurriedly\nand randomly uses a\nmove among those\nknown by other\nPokémon in the party.", /* 274 */
    "The user lays roots\nthat restore HP on\nevery turn.\nBecause it is rooted,\nit can’t switch out.", /* 275 */
    "The user attacks the\nfoe with great power.\nHowever, it also\nlowers the user’s\nAttack and Defense.", /* 276 */
    "A barrier reflects\nback to the foe\nmoves like Leech\nSeed and moves\nthat damage status.", /* 277 */
    "The user recycles a\nsingle-use item that\nhas been used in\nbattle so it can be\nused again.", /* 278 */
    "An attack move that\ninflicts double the\ndamage if the user\nhas been hurt by the\nfoe in the same turn.", /* 279 */
    "The user attacks with\ntough fists, etc. It\ncan also break any\nbarrier such as Light\nScreen and Reflect.", /* 280 */
    "The user lets loose a\nhuge yawn that lulls\nthe foe into falling\nasleep on the next\nturn.", /* 281 */
    "The user slaps down\nthe foe’s held item,\npreventing the item\nfrom being used\nduring the battle.", /* 282 */
    "An attack move that\ncuts down the foe’s\nHP to equal the\nuser’s HP.\n", /* 283 */
    "The user attacks in\nan explosive fury.\nThe lower the user’s\nHP, the less powerful\nthis attack becomes.", /* 284 */
    "The user employs its\npsychic power to\nexchange abilities\nwith the foe.\n", /* 285 */
    "If the foe knows any\nmove also known by\nthe user, the foe\nis prevented\nfrom using it.", /* 286 */
    "The user rests\nto cure itself of a\npoisoning, burn, or\nparalysis.\n", /* 287 */
    "If the user faints,\nthe user’s grudge\nfully depletes the PP\nof the foe’s move\nthat knocked it out.", /* 288 */
    "The user steals the\neffects of any\nhealing or stat-\nchanging move the foe\nattempts to use.", /* 289 */
    "The user attacks with\na secret power. Its\nadded effects vary\ndepending on the\nuser’s environment.", /* 290 */
    "A two-turn attack.\nThe user dives\nunderwater on the\nfirst turn, then hits\non the next turn.", /* 291 */
    "The user looses a\nflurry of open-palmed\narm thrusts that hit\ntwo to five times in a\nrow.", /* 292 */
    "The user’s type is\nchanged depending on\nits environment, such\nas at water’s edge, in\ngrass, or in a cave.", /* 293 */
    "The user stares at\nflashing lights to\nfocus its mind,\nsharply raising its\nSp. Atk stat.", /* 294 */
    "The user looses a\ndamaging burst of\nlight. It may also\nreduce the target’s\nSp. Def stat.", /* 295 */
    "A mistlike flurry of\ndown envelops and\ndamages the foe. It\nmay also lower the\ntarget’s Sp. Atk.", /* 296 */
    "The user covers the\nfoe with a mass of\ndown that sharply\nlowers the Attack\nstat.", /* 297 */
    "The user performs a\nwobbly dance that\nconfuses all the\nPokémon in battle.\n", /* 298 */
    "The user launches a\nkick with a high\ncritical-hit ratio.\nIt may also leave the\ntarget with a burn.", /* 299 */
    "The user covers\nitself with mud. It\nweakens Electric-\ntype moves while the\nuser is in the battle.", /* 300 */
    "The user continually\nrolls into the foe\nover five turns. It\nbecomes stronger\neach time it hits.", /* 301 */
    "The user attacks by\nwildly swinging its\nthorny arms.\nIt may also make the\ntarget flinch.", /* 302 */
    "The user slacks off,\nrestoring its own HP\nby up to half of its\nmaximum HP.\n", /* 303 */
    "The user lets loose\na horribly echoing\nshout with the\npower to inflict\ndamage.", /* 304 */
    "The user bites the\nfoe with toxic fangs.\nIt may also leave the\nfoe badly poisoned.\n", /* 305 */
    "The user slashes the\nfoe with hard and\nsharp claws.\nIt may also lower the\ntarget’s Defense.", /* 306 */
    "The foe is razed by\na fiery explosion.\nThe user must rest\non the next turn,\nhowever.", /* 307 */
    "The foe is hit with\na watery blast.\nThe user must rest\non the next turn,\nhowever.", /* 308 */
    "The foe is hit with a\nhard punch fired\nlike a meteor.\nIt may also raise\nthe user’s Attack.", /* 309 */
    "The user attacks the\nfoe while shouting in\na startling fashion.\nIt may also make the\ntarget flinch.", /* 310 */
    "An attack move that\nvaries in power and\ntype depending on\nthe weather.\n", /* 311 */
    "The user releases a\nsoothing scent that\nheals all status\nproblems affecting\nthe user’s party.", /* 312 */
    "The user feigns\ncrying to make the\nfoe feel flustered,\nsharply lowering its\nSp. Def stat.", /* 313 */
    "The user launches\nrazorlike wind to\nslash the foe.\nIt has a high\ncritical-hit ratio.", /* 314 */
    "The user attacks the\nfoe at full power.\nThe attack’s recoil\nsharply reduces the\nuser’s Sp. Atk stat.", /* 315 */
    "Enables the user to\nhit a Ghost type with\nany type of move. It\nalso enables the user\nto hit an evasive foe.", /* 316 */
    "Boulders are hurled\nat the foe. It also\nlowers the foe’s\nSpeed by preventing\nits movement.", /* 317 */
    "The foe is attacked\nwith powdery scales\nblown by wind.\nIt may also raise all\nthe user’s stats.", /* 318 */
    "A horrible sound like\nscraping metal is\nemitted to sharply\nreduce the foe’s\nSp. Def stat.", /* 319 */
    "The user plays a\npleasant melody that\nlulls the foe into a\ndeep sleep.\n", /* 320 */
    "The user tickles the\nfoe into laughing,\nreducing its Attack\nand Defense stats.\n", /* 321 */
    "The user absorbs a\nmystical power from\nspace to raise its\nDefense and Sp. Def\nstats.", /* 322 */
    "The user spouts\nwater to damage the\nfoe. The lower the\nuser’s HP, the less\npowerful it becomes.", /* 323 */
    "The user attacks with\na sinister beam of\nlight. It may also\nconfuse the target.\n", /* 324 */
    "The user throws a\npunch at the foe from\nthe shadows.\nThe punch lands\nwithout fail.", /* 325 */
    "The user attacks with\nan odd, unseeable\npower.\nIt may also make the\nfoe flinch.", /* 326 */
    "The user attacks the\nfoe with an uppercut\nthrown skyward\nwith force.\n", /* 327 */
    "The user traps the\nfoe inside a harshly\nraging sandstorm for\ntwo to five turns.\n", /* 328 */
    "The foe is attacked\nwith a blast of\nabsolute-zero cold.\nThe foe instantly\nfaints if it hits.", /* 329 */
    "The user attacks by\nshooting out muddy\nwater.\nIt may also lower the\nfoe’s accuracy.", /* 330 */
    "The user forcefully\nshoots seeds at the\nfoe. Two to five\nseeds are shot in\nrapid succession.", /* 331 */
    "The user confounds\nthe foe with speed,\nthen slashes.\nThe attack lands\nwithout fail.", /* 332 */
    "The user launches\nsharp icicles at the\nfoe. It strikes two\nto five times in a\nrow.", /* 333 */
    "The user hardens\nits body’s surface\nlike iron, sharply\nraising its Defense\nstat.", /* 334 */
    "The user blocks the\nfoe’s way with arms\nspread wide to\nprevent escape.\n", /* 335 */
    "The user howls loudly\nto raise its spirit,\nboosting its Attack\nstat.\n", /* 336 */
    "The user slashes the\nfoe with huge, sharp\nclaws.\n\n", /* 337 */
    "The foe is slammed\nwith an enormous\ntree.\nThe user can’t move\non the next turn.", /* 338 */
    "The user tenses its\nmuscles to bulk up\nits body, boosting\nboth its Attack and\nDefense stats.", /* 339 */
    "The user bounces up\nhigh, then drops on\nthe foe on the second\nturn. It may also\nparalyze the foe.", /* 340 */
    "The user attacks by\nhurling a blob of mud\nat the foe.\nIt also reduces the\ntarget’s Speed.", /* 341 */
    "An attack with a\nhigh critical-hit\nratio. This tail \nattack may also \npoison the foe.", /* 342 */
    "The user endearingly\napproaches the foe,\nthen steals the item\nthe foe is holding.\n", /* 343 */
    "The user electrifies\nitself, then charges\nat the foe. It causes\nconsiderable damage\nto the user as well.", /* 344 */
    "The user scatters\ncurious leaves that\nchase the foe.\nThis attack will not\nmiss.", /* 345 */
    "The user soaks itself\nwith water. The move\nweakens Fire-type\nmoves while the user\nis in the battle.", /* 346 */
    "The user quietly\nfocuses its mind and\ncalms its spirit to\nraise its Sp. Atk and\nSp. Def stats.", /* 347 */
    "The foe is slashed\nwith a sharp leaf.\nIt has a high\ncritical-hit ratio.\n", /* 348 */
    "The user vigorously\nperforms a mystic,\npowerful dance that\nboosts its Attack and\nSpeed stats.", /* 349 */
    "The user hurls hard\nrocks at the foe.\nTwo to five rocks are\nlaunched in quick\nsuccession.", /* 350 */
    "The user strikes the\nfoe with a quick jolt\nof electricity.\nThis attack cannot be\nevaded.", /* 351 */
    "The user attacks the\nfoe with a pulsing\nblast of water.\nIt may also confuse\nthe foe.", /* 352 */
    "Two turns after this\nmove is used, the\nuser blasts the foe\nwith a concentrated\nbundle of light.", /* 353 */
    "The user attacks the\nfoe at full power.\nThe attack’s recoil\nsharply reduces the\nuser’s Sp. Atk stat.", /* 354 */
    "The user lands and\nrests its body.\nIt restores the\nuser’s HP by up to\nhalf of its max HP.", /* 355 */
    "Gravity is intensified\nfor five turns, making\nmoves involving flying\nunusable and\nnegating Levitation.", /* 356 */
    "Enables the user to\nhit a Dark type with\nany type of move. It\nalso enables the user\nto hit an evasive foe.", /* 357 */
    "This attack inflicts\nhigh damage on a\nsleeping foe. It\nalso wakes the foe\nup, however.", /* 358 */
    "The user swings and\nhits with its strong\nand heavy fist.\nIt lowers the user’s\nSpeed, however.", /* 359 */
    "The user tackles the\nfoe with a high-speed\nspin. The slower the\nuser, the greater\nthe damage.", /* 360 */
    "The user faints. In\nreturn, the Pokémon\ntaking its place will\nhave its HP restored\nand status cured.", /* 361 */
    "If the foe’s HP is\ndown to about half,\nthis attack will hit\nwith double the\npower.", /* 362 */
    "The user draws power\nto attack by using\nits held Berry.\nThe Berry determines\nits type and power.", /* 363 */
    "An attack that hits a\nfoe using Protect or\nDetect. It also lifts\nthe effects of those\nmoves.", /* 364 */
    "The user pecks the\nfoe. If the foe is\nholding a Berry, the\nuser plucks it and\ngains its effect.", /* 365 */
    "The user whips up a\nturbulent whirlwind\nthat ups the Speed\nof all party Pokémon\nfor three turns.", /* 366 */
    "The user applies\npressure to stress\npoints, sharply\nboosting one of its\nstats.", /* 367 */
    "The user retaliates\nagainst the foe that\nlast inflicted damage\non it with much\ngreater power.", /* 368 */
    "After making its\nattack, the user\nrushes back to switch\nplaces with a party\nPokémon in waiting.", /* 369 */
    "The user fights the\nfoe in close without\nguarding itself. It\nalso cuts the user’s\nDefense and Sp. Def.", /* 370 */
    "If the user can use\nthis attack after the\nfoe attacks, its\npower is doubled.\n", /* 371 */
    "If the foe has\nalready taken some\ndamage in the same\nturn, this attack’s\npower is doubled.", /* 372 */
    "It prevents the foe\nfrom using its held\nitem. Its Trainer is\nalso prevented from\nusing items on it.", /* 373 */
    "The user flings its\nheld item at the foe\nto attack. Its power\nand effects depend\non the item.", /* 374 */
    "Using its psychic\npower of suggestion,\nthe user transfers\nits status problems\nto the target.", /* 375 */
    "The fewer PP this\nmove has, the more\npower it has for\nattack.\n", /* 376 */
    "The user prevents\nthe foe from using\nany HP-recovery\nmoves for five turns.\n", /* 377 */
    "The user powerfully\nwrings the foe.\nThe more HP the foe\nhas, the greater this\nattack’s power.", /* 378 */
    "The user employs its\npsychic power to\nswitch its Attack\nwith its Defense\nstat.", /* 379 */
    "The user hurls up its\nstomach acids on\nthe foe. The fluid\neliminates the effect\nof the foe’s ability.", /* 380 */
    "The user chants an\nincantation toward\nthe sky, preventing\nthe foe from landing\ncritical hits.", /* 381 */
    "The user tries to cut\nahead of the foe to\nsteal and use the\nfoe’s intended move\nwith greater power.", /* 382 */
    "The user mimics the\nmove used immediately\nbefore it. The move\nfails if no other move\nhas been used yet.", /* 383 */
    "The user employs its\npsychic power to\nswitch changes to\nits Attack and\nSp. Atk with the foe.", /* 384 */
    "The user employs its\npsychic power to\nswitch changes to\nits Defense and\nSp. Def with the foe.", /* 385 */
    "This attack’s power\nincreases the more\nthe foe has powered\nup with stat changes.\n", /* 386 */
    "This move can be used\nonly after the user\nhas used all the\nother moves it knows\nin the battle.", /* 387 */
    "A seed that causes\nworry is planted on\nthe foe. It prevents\nsleep by making its\nability Insomnia.", /* 388 */
    "This move enables the\nuser to attack first.\nIt fails if the foe is\nnot readying an\nattack, however.", /* 389 */
    "The user lays a trap\nof poison spikes at\nthe foe’s feet. They\npoison foes that\nswitch into battle.", /* 390 */
    "The user employs its\npsychic power to\nswitch stat changes\nwith the foe.\n", /* 391 */
    "The user envelops\nitself in a veil made\nof water. It regains\nsome HP on every\nturn.", /* 392 */
    "The user levitates\nusing electrically\ngenerated magnetism\nfor five turns.\n", /* 393 */
    "The user cloaks\nitself in fire and\ncharges at the foe.\nThe user sustains\nserious damage, too.", /* 394 */
    "The foe is attacked\nwith a shock wave.\nIt may also leave the\ntarget paralyzed.\n", /* 395 */
    "The user looses a\nblast of aura power\nfrom deep within its\nbody. This move is\ncertain to hit.", /* 396 */
    "The user polishes its\nbody to reduce drag.\nIt can sharply raise\nthe Speed stat.\n", /* 397 */
    "The foe is stabbed\nwith a tentacle or\narm steeped in\npoison. It may also\npoison the foe.", /* 398 */
    "The user releases a\nhorrible aura imbued\nwith dark thoughts.\nIt may also make the\ntarget flinch.", /* 399 */
    "The user slashes the\nfoe the instant an\nopportunity arises.\nIt has a high\ncritical-hit ratio.", /* 400 */
    "The user attacks by\nswinging its tail as if\nit were a vicious wave\nin a raging storm.\n", /* 401 */
    "The user slams a\nbarrage of hard-\nshelled seeds\ndown on the foe\nfrom above.", /* 402 */
    "The user attacks with\na blade of air that\nslices even the sky.\nIt may also make the\ntarget flinch.", /* 403 */
    "The user slashes at\nthe foe by crossing\nits scythes or claws\nas if they were a pair\nof scissors.", /* 404 */
    "The user vibrates its\nwings to generate a\ndamaging sound wave.\nIt may also lower the\nfoe’s Sp. Def stat.", /* 405 */
    "The foe is attacked\nwith a shock wave\ngenerated by the\nuser’s gaping mouth.\n", /* 406 */
    "The user tackles the\nfoe while exhibiting\noverwhelming menace.\nIt may also make the\ntarget flinch.", /* 407 */
    "The user attacks with\na ray of light that\nsparkles as if it were\nmade of gemstones.\n", /* 408 */
    "An energy-draining\npunch. The user’s\nHP is restored by\nhalf the damage taken\nby the target.", /* 409 */
    "The user whirls its\nfists to send a wave\nof pure vacuum at\nthe foe. This move\nalways goes first.", /* 410 */
    "The user heightens\nits mental focus and\nunleashes its power.\nIt may also lower the\ntarget’s Sp. Def.", /* 411 */
    "The user draws power\nfrom nature and\nfires it at the foe.\nIt may also lower the\ntarget’s Sp. Def.", /* 412 */
    "The user tucks in\nits wings and charges\nfrom a low altitude.\nThe user also takes\nserious damage.", /* 413 */
    "The user makes the\nground under the foe\nerupt with power.\nIt may also lower the\ntarget’s Sp. Def.", /* 414 */
    "The user trades held\nitems with the foe\nfaster than the eye\ncan follow.\n", /* 415 */
    "The user charges at\nthe foe using every\nbit of its power.\nThe user must rest\non the next turn.", /* 416 */
    "The user stimulates\nits brain by thinking\nbad thoughts.\nIt sharply raises the\nuser’s Sp. Atk.", /* 417 */
    "The user strikes\nwith a tough punch as\nfast as a bullet.\nThis move always goes\nfirst.", /* 418 */
    "An attack move that\ninflicts double the\ndamage if the user\nhas been hurt by the\nfoe in the same turn.", /* 419 */
    "The user flash\nfreezes chunks of\nice and hurls them.\nThis move always goes\nfirst.", /* 420 */
    "The user slashes with\na sharp claw made\nfrom shadows.\nIt has a high\ncritical-hit ratio.", /* 421 */
    "The user bites with\nelectrified fangs.\nIt may also make the\nfoe flinch or become\nparalyzed.", /* 422 */
    "The user bites with\ncold-infused fangs.\nIt may also make the\nfoe flinch or freeze.\n", /* 423 */
    "The user bites with\nflame-cloaked fangs.\nIt may also make the\nfoe flinch or sustain\na burn.", /* 424 */
    "The user extends its\nshadow and attacks\nthe foe from behind.\nThis move always goes\nfirst.", /* 425 */
    "The user launches a\nhard-packed mud ball\nto attack.\nIt may also lower the\ntarget’s accuracy.", /* 426 */
    "The user tears at\nthe foe with blades\nformed by psychic\npower. It has a high\ncritical-hit ratio.", /* 427 */
    "The user focuses its\nwillpower to its head\nand rams the foe.\nIt may also make the\ntarget flinch.", /* 428 */
    "The user looses a\nflash of energy from\nits polished body.\nIt may also lower the\ntarget’s accuracy.", /* 429 */
    "The user gathers all\nits light energy and\nreleases it at once.\nIt may also lower the\nfoe’s Sp. Def stat.", /* 430 */
    "A charging attack\nthat may also leave\nthe foe confused.\nIt can also be used\nto scale rocky walls.", /* 431 */
    "Obstacles are moved,\nreducing the foe’s\nevasion stat. It can\nalso be used to\nclear deep fog, etc.", /* 432 */
    "The user creates a\nbizarre area in which\nslower Pokémon get\nto move first for five\nturns.", /* 433 */
    "Comets are summoned\ndown from the sky.\nThe attack’s recoil\nsharply reduces the\nuser’s Sp. Atk stat.", /* 434 */
    "A flare of electricity\nis loosed to strike\nall Pokémon in battle.\nIt may also cause\nparalysis.", /* 435 */
    "An inferno of scarlet\nflames washes over\nall Pokémon in battle.\nIt may also inflict\nburns.", /* 436 */
    "A storm of sharp\nleaves is whipped up.\nThe attack’s recoil\nsharply reduces the\nuser’s Sp. Atk stat.", /* 437 */
    "The user violently\nwhirls its vines or\ntentacles to harshly\nlash the foe.\n", /* 438 */
    "The user launches a\nhuge boulder at the\nfoe to attack.\nIt must rest on the\nnext turn, however.", /* 439 */
    "A slashing attack\nthat may also leave\nthe target poisoned.\nIt has a high\ncritical-hit ratio.", /* 440 */
    "The user shoots\nfilthy garbage at the\nfoe to attack.\nIt may also poison\nthe target.", /* 441 */
    "The foe slams the\ntarget with its\nsteel-hard head.\nIt may also make the\ntarget flinch.", /* 442 */
    "The user launches a\nsteel bomb that\nsticks to the target.\nThis attack will not\nmiss.", /* 443 */
    "The user stabs the\nfoe with a sharpened\nstone. It has a high\ncritical-hit ratio.\n", /* 444 */
    "If it is the opposite\ngender of the user,\nthe foe is charmed\ninto sharply lowering\nits Sp. Atk stat.", /* 445 */
    "The user lays a trap\nof levitating stones\naround the foe. The\ntrap hurts foes that\nswitch into battle.", /* 446 */
    "The user snares the\nfoe with grass and\ntrips it. The heavier\nthe foe, the greater\nthe damage.", /* 447 */
    "The user attacks\nusing a sound wave\nbased on words it has\nlearned. It may also\nconfuse the foe.", /* 448 */
    "The user releases\ncountless shots of\nlight. Its type varies\nwith the kind of Plate\nthe user is holding.", /* 449 */
    "The user bites the\nfoe. If the foe is\nholding a Berry, the\nuser eats it and\ngains its effect.", /* 450 */
    "The user fires a\nconcentrated bundle\nof electricity. It may\nalso raise the user’s\nSp. Atk stat.", /* 451 */
    "The user slams its\nrugged body into the\nfoe to attack. The\nuser also sustains\nserious damage.", /* 452 */
    "The user lunges at\nthe foe at a speed\nthat makes it almost\ninvisible. It is sure\nto strike first.", /* 453 */
    "The user calls out\nits underlings to\npummel the foe.\nIt has a high\ncritical-hit ratio.", /* 454 */
    "The user calls out\nits underlings to\nshield its body,\nraising its Defense\nand Sp. Def stats.", /* 455 */
    "The user calls out\nits underlings to heal\nit. The user regains\nup to half of its\nmax HP.", /* 456 */
    "The user delivers a\nlife-endangering head\nbutt at full power.\nThe user also takes\nterrible damage.", /* 457 */
    "The user slams the\nfoe with a tail, etc.\nThe target is hit\ntwice in a row.\n", /* 458 */
    "The user blasts the\nfoe with power that\ndistorts even time.\nThe user must rest\non the next turn.", /* 459 */
    "The user tears the\nfoe along with the\nspace around it.\nThis move has a high\ncritical-hit ratio.", /* 460 */
    "The user faints. In\nreturn, the Pokémon\ntaking its place will\nhave its status and\nHP fully restored.", /* 461 */
    "The foe is crushed\nwith great force.\nThe attack is more\npowerful the more HP\nthe foe has left.", /* 462 */
    "The foe becomes\ntrapped within a\nmaelstrom of fire\nthat rages for two\nto five turns.", /* 463 */
    "The foe is dragged\ninto a world of total\ndarkness that puts it\nto sleep.\n", /* 464 */
    "The user generates\na shock wave from\nwithin its body.\nIt may also lower the\ntarget’s Sp. Def.", /* 465 */
    "The user creates a\ngust of repulsive\nwind. It may also\nraise all the user’s\nstats at once.", /* 466 */
    "The user disappears,\nthen strikes the foe\non the second turn.\nIt hits even if the\nfoe used Protect.", /* 467 */
};

static const s8 MMO_DISPLAY_MOVE_TYPE[MMO_DISPLAY_MOVE_COUNT] = {
     0,  0,  1,  0,  0,  0,  0, 10, 15, 13,  0,  0,  0,  0,  0,  0,
     2,  2,  0,  2,  0,  0, 12,  0,  1,  0,  1,  1,  4,  0,  0,  0,
     0,  0,  0,  0,  0,  0,  0,  0,  3,  6,  6,  0, 17,  0,  0,  0,
     0,  0,  0,  3, 10, 10, 15, 11, 11, 11, 15, 15, 14, 11, 15,  0,
     2,  2,  1,  1,  1,  1,  0, 12, 12, 12,  0, 12, 12,  3, 12, 12,
    12,  6, 16, 10, 13, 13, 13, 13,  5,  4,  4,  4,  3, 14, 14, 14,
    14, 14,  0,  0, 14,  7,  0,  0,  0,  0,  0,  0,  0,  7, 11,  0,
    14, 14, 15, 14,  0,  0,  0,  2,  0,  0,  7,  3,  3,  4, 10, 11,
    11,  0,  0,  0,  0, 14, 14,  0,  1,  0, 14,  3,  0,  6,  0,  2,
     0, 11,  0, 12,  0, 14,  0,  3, 11,  0,  0,  4, 14,  5,  0,  0,
     0,  0,  0,  0,  0,  0,  0,  1, 17,  6,  0,  7, 10,  0,  9,  0,
     0,  2, 12,  1,  7, 15,  0,  1,  0, 17,  0,  0,  3,  4, 11,  4,
    13,  0,  7,  0, 15,  1,  4,  0, 16,  5, 12,  0,  0,  5,  0,  0,
     0, 13,  6,  8,  0,  0,  0,  0,  0,  0,  0,  0,  0, 10,  4,  1,
     6, 16,  0,  0, 17,  0,  0,  8,  8,  1,  0, 12,  0,  0,  1, 16,
    11, 10, 17, 14,  0,  0,  5,  7, 14,  1, 11, 17,  0,  0,  0,  0,
     0, 10, 15, 17, 17, 10, 17,  0,  1,  0,  0,  0, 13, 17,  0, 14,
    14,  0,  0, 12,  1, 14,  0,  1,  1,  0, 17,  0, 10, 14, 14,  0,
     7, 17,  0, 11,  1,  0,  6, 14, 14,  2,  0, 10,  4, 15, 12,  0,
     0,  3,  0, 10, 11,  8,  7,  0, 12, 17,  2, 10,  0,  5,  6,  8,
    12,  0, 14, 11,  6,  7, 14,  1,  4, 15, 11, 12,  2, 15,  8,  0,
     0, 16, 12,  1,  2,  4,  3,  0, 13, 12, 11, 14, 12, 16,  5, 13,
    11,  8, 14,  2, 14, 14,  1,  1,  8, 14, 11,  0,  0,  2,  2,  0,
     8,  6,  1, 17, 17, 17, 17, 14,  0, 14,  0, 14,  3,  0,  0,  0,
    14, 14, 17,  0, 12, 17,  3, 14, 11, 13, 10,  1,  1,  5,  3, 17,
    17, 11, 12,  2,  6,  6, 16, 16,  5,  1,  1,  1, 12,  2,  4, 17,
     0, 17,  8, 15, 15,  7, 13, 15, 10,  7,  4, 14, 14,  8,  8,  0,
     2, 14, 16, 13, 10, 12, 12,  5,  3,  3,  8,  8,  5,  0,  5, 12,
     2,  0,  6, 13, 12, 11,  6,  6,  6,  5,  0, 16, 16, 14,  0, 10,
    17, 12,  7,  7,
};

static const s8 MMO_DISPLAY_SPECIES_TYPE1[MMO_DISPLAY_SPECIES_COUNT] = {
    -1, 12, 12, 12, 10, 10, 10, 11, 11, 11,  6,  6,  6,  6,  6,  6,
     0,  0,  0,  0,  0,  0,  0,  3,  3, 13, 13,  4,  4,  3,  3,  3,
     3,  3,  3,  0,  0, 10, 10,  0,  0,  3,  3, 12, 12, 12,  6,  6,
     6,  6,  4,  4,  0,  0, 11, 11,  1,  1, 10, 10, 11, 11, 11, 14,
    14, 14,  1,  1,  1, 12, 12, 12, 11, 11,  5,  5,  5, 10, 10, 11,
    11, 13, 13,  0,  0,  0, 11, 11,  3,  3, 11, 11,  7,  7,  7,  5,
    14, 14, 11, 11, 13, 13, 12, 12,  4,  4,  1,  1,  0,  3,  3,  4,
     4,  0, 12,  0, 11, 11, 11, 11, 11, 11, 14,  6, 15, 13, 10,  6,
     0, 11, 11, 11,  0,  0, 11, 13, 10,  0,  5,  5,  5,  5,  5,  0,
    15, 13, 10, 16, 16, 16, 14, 14, 12, 12, 12, 10, 10, 10, 11, 11,
    11,  0,  0,  0,  0,  6,  6,  6,  6,  3, 11, 11, 13,  0,  0,  0,
     0, 14, 14, 13, 13, 13, 12, 11, 11,  5, 11, 12, 12, 12,  0, 12,
    12,  6, 11, 11, 14, 17, 17, 11,  7, 14, 14,  0,  6,  6,  0,  4,
     8,  0,  0, 11,  6,  6,  6, 17,  0,  0, 10, 10, 15, 15, 11, 11,
    11, 15, 11,  8, 17, 17, 11,  4,  4,  0,  0,  0,  1,  1, 15, 13,
    10,  0,  0, 13, 10, 11,  5,  5,  5, 14, 10, 14, 12, 12, 12, 10,
    10, 10, 11, 11, 11, 17, 17,  0,  0,  6,  6,  6,  6,  6, 11, 11,
    11, 12, 12, 12,  0,  0, 11, 11, 14, 14, 14,  6,  6, 12, 12,  0,
     0,  0,  6,  6,  6,  0,  0,  0,  1,  1,  0,  5,  0,  0, 17,  8,
     8,  8,  8,  1,  1, 13, 13, 13, 13,  6,  6, 12,  3,  3, 11, 11,
    11, 11, 10, 10, 10, 14, 14,  0,  4,  4,  4, 12, 12,  0, 16,  0,
     3,  5,  5, 11, 11, 11, 11,  4,  4,  5,  5,  5,  5, 11, 11,  0,
     0,  7,  7,  7,  7, 12, 14, 17, 14, 15, 15, 15, 15, 15, 11, 11,
    11, 11, 11, 16, 16, 16,  8,  8,  8,  5, 15,  8, 16, 16, 11,  4,
    16,  8, 14, 12, 12, 12, 10, 10, 10, 11, 11, 11,  0,  0,  0,  0,
     0,  6,  6, 13, 13, 13, 12, 12,  5,  5,  5,  5,  6,  6,  6,  6,
     6, 13, 11, 11, 12, 12, 11, 11,  0,  7,  7,  0,  0,  7, 17,  0,
     0, 14,  3,  3,  8,  8,  5, 14,  0,  0,  7, 16, 16, 16,  0,  1,
     1,  4,  4,  3,  3,  3,  3, 12, 11, 11, 11, 12, 12, 17, 13,  0,
     4, 12, 13, 10,  0,  6, 12, 15,  4, 15,  0, 14,  5,  7, 15, 13,
    14, 14, 14,  8, 11, 10,  0,  7, 14, 11, 11, 17, 12,  0,
};

static const s8 MMO_DISPLAY_SPECIES_TYPE2[MMO_DISPLAY_SPECIES_COUNT] = {
    -1,  3,  3,  3, 10, 10,  2, 11, 11, 11,  6,  6,  2,  3,  3,  3,
     2,  2,  2,  0,  0,  2,  2,  3,  3, 13, 13,  4,  4,  3,  3,  4,
     3,  3,  4,  0,  0, 10, 10,  0,  0,  2,  2,  3,  3,  3, 12, 12,
     3,  3,  4,  4,  0,  0, 11, 11,  1,  1, 10, 10, 11, 11,  1, 14,
    14, 14,  1,  1,  1,  3,  3,  3,  3,  3,  4,  4,  4, 10, 10, 14,
    14,  8,  8,  2,  2,  2, 11, 15,  3,  3, 11, 15,  3,  3,  3,  4,
    14, 14, 11, 11, 13, 13, 14, 14,  4,  4,  1,  1,  0,  3,  3,  5,
     5,  0, 12,  0, 11, 11, 11, 11, 11, 14, 14,  2, 14, 13, 10,  6,
     0, 11,  2, 15,  0,  0, 11, 13, 10,  0, 11, 11, 11, 11,  2,  0,
     2,  2,  2, 16, 16,  2, 14, 14, 12, 12, 12, 10, 10, 10, 11, 11,
    11,  0,  0,  2,  2,  2,  2,  3,  3,  2, 13, 13, 13,  0,  0,  0,
     2,  2,  2, 13, 13, 13, 12, 11, 11,  5, 11,  2,  2,  2,  0, 12,
    12,  2,  4,  4, 14, 17,  2, 14,  7, 14, 14, 14,  6,  8,  0,  2,
     4,  0,  0,  3,  8,  5,  1, 15,  0,  0, 10,  5,  4,  4,  5, 11,
    11,  2,  2,  2, 10, 10, 16,  4,  4,  0,  0,  0,  1,  1, 14, 13,
    10,  0,  0, 13, 10, 11,  4,  4, 17,  2,  2, 12, 12, 12, 12, 10,
     1,  1, 11,  4,  4, 17, 17,  0,  0,  6,  6,  2,  6,  3, 12, 12,
    12, 12, 17, 17,  2,  2,  2,  2, 14, 14, 14, 11,  2, 12,  1,  0,
     0,  0,  4,  2,  7,  0,  0,  0,  1,  1,  0,  5,  0,  0,  7,  8,
     5,  5,  5, 14, 14, 13, 13, 13, 13,  6,  6,  3,  3,  3, 17, 17,
    11, 11,  4,  4, 10, 14, 14,  0,  4, 16, 16, 12, 17,  2,  2,  0,
     3, 14, 14,  4,  4, 11, 17, 14, 14, 12, 12,  6,  6, 11, 11,  0,
     0,  7,  7,  7,  7,  2, 14, 17, 14, 15, 15, 11, 11, 11, 11, 11,
    11,  5, 11, 16, 16,  2, 14, 14, 14,  5, 15,  8, 14, 14, 11,  4,
     2, 14, 14, 12, 12,  4, 10,  1,  1, 11, 11,  8,  2,  2,  2,  0,
    11,  6,  6, 13, 13, 13,  3,  3,  5,  5,  8,  8,  6, 12,  2,  2,
     2, 13, 11, 11, 12, 12, 11,  4,  0,  2,  2,  0,  0,  7,  2,  0,
     0, 14, 17, 17, 14, 14,  5, 14,  0,  2, 17,  4,  4,  4,  0,  1,
     8,  4,  4,  6, 17,  1,  1, 12, 11, 11,  2, 15, 15, 15,  8,  0,
     5, 12, 13, 10,  2,  2, 12, 15,  2,  4,  0,  1,  8,  7,  7,  7,
    14, 14, 14, 16, 16,  8,  0, 16, 14, 11, 11, 17, 12,  0,
};

