/* Generated by tools/gen_idmap_items.py; Do not edit. */

static const u16 MMO_ITEM_SHARED[] = {
       1, /* Master Ball; gba 1 */
       2, /* Ultra Ball; gba 2 */
       3, /* Great Ball; gba 3 */
       4, /* Poke Ball; gba 4 */
       5, /* Safari Ball; gba 5 */
       6, /* Net Ball; gba 6 */
       7, /* Dive Ball; gba 7 */
       8, /* Nest Ball; gba 8 */
       9, /* Repeat Ball; gba 9 */
      10, /* Timer Ball; gba 10 */
      11, /* Luxury Ball; gba 11 */
      12, /* Premier Ball; gba 12 */
      13, /* Dusk Ball; no gba */
      14, /* Heal Ball; no gba */
      15, /* Quick Ball; no gba */
      16, /* Cherish Ball; no gba */
      17, /* Potion; gba 13 */
      18, /* Antidote; gba 14 */
      19, /* Burn Heal; gba 15 */
      20, /* Ice Heal; gba 16 */
      21, /* Awakening; gba 17 */
      22, /* Parlyz Heal; gba 18 */
      23, /* Full Restore; gba 19 */
      24, /* Max Potion; gba 20 */
      25, /* Hyper Potion; gba 21 */
      26, /* Super Potion; gba 22 */
      27, /* Full Heal; gba 23 */
      28, /* Revive; gba 24 */
      29, /* Max Revive; gba 25 */
      30, /* Fresh Water; gba 26 */
      31, /* Soda Pop; gba 27 */
      32, /* Lemonade; gba 28 */
      33, /* Moomoo Milk; gba 29 */
      34, /* EnergyPowder; gba 30 */
      35, /* Energy Root; gba 31 */
      36, /* Heal Powder; gba 32 */
      37, /* Revival Herb; gba 33 */
      38, /* Ether; gba 34 */
      39, /* Max Ether; gba 35 */
      40, /* Elixir; gba 36 */
      41, /* Max Elixir; gba 37 */
      42, /* Lava Cookie; gba 38 */
      43, /* Berry Juice; gba 44 */
      44, /* Sacred Ash; gba 45 */
      45, /* HP Up; gba 63 */
      46, /* Protein; gba 64 */
      47, /* Iron; gba 65 */
      48, /* Carbos; gba 66 */
      49, /* Calcium; gba 67 */
      50, /* Rare Candy; gba 68 */
      51, /* PP Up; gba 69 */
      52, /* Zinc; gba 70 */
      53, /* PP Max; gba 71 */
      54, /* Old Gateau; no gba */
      55, /* Guard Spec.; gba 73 */
      56, /* Dire Hit; gba 74 */
      57, /* X Attack; gba 75 */
      58, /* X Defend; gba 76 */
      59, /* X Speed; gba 77 */
      60, /* X Accuracy; gba 78 */
      61, /* X Special; gba 79 */
      62, /* X Sp. Def; no gba */
      63, /* Poke Doll; gba 80 */
      64, /* Fluffy Tail; gba 81 */
      65, /* Blue Flute; gba 39 */
      66, /* Yellow Flute; gba 40 */
      67, /* Red Flute; gba 41 */
      68, /* Black Flute; gba 42 */
      69, /* White Flute; gba 43 */
      70, /* Shoal Salt; gba 46 */
      71, /* Shoal Shell; gba 47 */
      72, /* Red Shard; gba 48 */
      73, /* Blue Shard; gba 49 */
      74, /* Yellow Shard; gba 50 */
      75, /* Green Shard; gba 51 */
      76, /* Super Repel; gba 83 */
      77, /* Max Repel; gba 84 */
      78, /* Escape Rope; gba 85 */
      79, /* Repel; gba 86 */
      80, /* Sun Stone; gba 93 */
      81, /* Moon Stone; gba 94 */
      82, /* Fire Stone; gba 95 */
      83, /* Thunderstone; gba 96 */
      84, /* Water Stone; gba 97 */
      85, /* Leaf Stone; gba 98 */
      86, /* TinyMushroom; gba 103 */
      87, /* Big Mushroom; gba 104 */
      88, /* Pearl; gba 106 */
      89, /* Big Pearl; gba 107 */
      90, /* Stardust; gba 108 */
      91, /* Star Piece; gba 109 */
      92, /* Nugget; gba 110 */
      93, /* Heart Scale; gba 111 */
      94, /* Honey; no gba */
      95, /* Growth Mulch; no gba */
      96, /* Damp Mulch; no gba */
      97, /* Stable Mulch; no gba */
      98, /* Gooey Mulch; no gba */
      99, /* Root Fossil; gba 286 */
     100, /* Claw Fossil; gba 287 */
     101, /* Helix Fossil; gba 357 */
     102, /* Dome Fossil; gba 358 */
     103, /* Old Amber; gba 354 */
     104, /* Armor Fossil; no gba */
     105, /* Skull Fossil; no gba */
     106, /* Rare Bone; no gba */
     107, /* Shiny Stone; no gba */
     108, /* Dusk Stone; no gba */
     109, /* Dawn Stone; no gba */
     110, /* Oval Stone; no gba */
     111, /* Odd Keystone; no gba */
     112, /* Griseous Orb; no gba */
     135, /* Adamant Orb; no gba */
     136, /* Lustrous Orb; no gba */
     137, /* engine Grass Mail / server Greet Mail; no gba */
     138, /* engine Flame Mail / server Favored Mail; no gba */
     139, /* engine Bubble Mail / server RSVP Mail; no gba */
     140, /* engine Bloom Mail / server Thanks Mail; no gba */
     141, /* engine Tunnel Mail / server Inquiry Mail; no gba */
     142, /* engine Steel Mail / server Like Mail; no gba */
     143, /* engine Heart Mail / server Reply Mail; no gba */
     144, /* engine Snow Mail / server BridgeMail S; no gba */
     145, /* engine Space Mail / server BridgeMail D; no gba */
     146, /* engine Air Mail / server BridgeMail T; no gba */
     147, /* engine Mosaic Mail / server BridgeMail V; no gba */
     148, /* engine Brick Mail / server BridgeMail M; no gba */
     149, /* Cheri Berry; gba 133 */
     150, /* Chesto Berry; gba 134 */
     151, /* Pecha Berry; gba 135 */
     152, /* Rawst Berry; gba 136 */
     153, /* Aspear Berry; gba 137 */
     154, /* Leppa Berry; gba 138 */
     155, /* Oran Berry; gba 139 */
     156, /* Persim Berry; gba 140 */
     157, /* Lum Berry; gba 141 */
     158, /* Sitrus Berry; gba 142 */
     159, /* Figy Berry; gba 143 */
     160, /* Wiki Berry; gba 144 */
     161, /* Mago Berry; gba 145 */
     162, /* Aguav Berry; gba 146 */
     163, /* Iapapa Berry; gba 147 */
     164, /* Razz Berry; gba 148 */
     165, /* Bluk Berry; gba 149 */
     166, /* Nanab Berry; gba 150 */
     167, /* Wepear Berry; gba 151 */
     168, /* Pinap Berry; gba 152 */
     169, /* Pomeg Berry; gba 153 */
     170, /* Kelpsy Berry; gba 154 */
     171, /* Qualot Berry; gba 155 */
     172, /* Hondew Berry; gba 156 */
     173, /* Grepa Berry; gba 157 */
     174, /* Tamato Berry; gba 158 */
     175, /* Cornn Berry; gba 159 */
     176, /* Magost Berry; gba 160 */
     177, /* Rabuta Berry; gba 161 */
     178, /* Nomel Berry; gba 162 */
     179, /* Spelon Berry; gba 163 */
     180, /* Pamtre Berry; gba 164 */
     181, /* Watmel Berry; gba 165 */
     182, /* Durin Berry; gba 166 */
     183, /* Belue Berry; gba 167 */
     184, /* Occa Berry; no gba */
     185, /* Passho Berry; no gba */
     186, /* Wacan Berry; no gba */
     187, /* Rindo Berry; no gba */
     188, /* Yache Berry; no gba */
     189, /* Chople Berry; no gba */
     190, /* Kebia Berry; no gba */
     191, /* Shuca Berry; no gba */
     192, /* Coba Berry; no gba */
     193, /* Payapa Berry; no gba */
     194, /* Tanga Berry; no gba */
     195, /* Charti Berry; no gba */
     196, /* Kasib Berry; no gba */
     197, /* Haban Berry; no gba */
     198, /* Colbur Berry; no gba */
     199, /* Babiri Berry; no gba */
     200, /* Chilan Berry; no gba */
     201, /* Liechi Berry; gba 168 */
     202, /* Ganlon Berry; gba 169 */
     203, /* Salac Berry; gba 170 */
     204, /* Petaya Berry; gba 171 */
     205, /* Apicot Berry; gba 172 */
     206, /* Lansat Berry; gba 173 */
     207, /* Starf Berry; gba 174 */
     208, /* Enigma Berry; gba 175 */
     209, /* Micle Berry; no gba */
     210, /* Custap Berry; no gba */
     211, /* Jaboca Berry; no gba */
     212, /* Rowap Berry; no gba */
     213, /* BrightPowder; gba 179 */
     214, /* White Herb; gba 180 */
     215, /* Macho Brace; gba 181 */
     216, /* Exp. Share; gba 182 */
     217, /* Quick Claw; gba 183 */
     218, /* Soothe Bell; gba 184 */
     219, /* Mental Herb; gba 185 */
     220, /* Choice Band; gba 186 */
     221, /* Kings Rock; gba 187 */
     222, /* SilverPowder; gba 188 */
     223, /* Amulet Coin; gba 189 */
     224, /* Cleanse Tag; gba 190 */
     225, /* Soul Dew; gba 191 */
     226, /* DeepSeaTooth; gba 192 */
     227, /* DeepSeaScale; gba 193 */
     228, /* Smoke Ball; gba 194 */
     229, /* Everstone; gba 195 */
     230, /* Focus Band; gba 196 */
     231, /* Lucky Egg; gba 197 */
     232, /* Scope Lens; gba 198 */
     233, /* Metal Coat; gba 199 */
     234, /* Leftovers; gba 200 */
     235, /* Dragon Scale; gba 201 */
     236, /* Light Ball; gba 202 */
     237, /* Soft Sand; gba 203 */
     238, /* Hard Stone; gba 204 */
     239, /* Miracle Seed; gba 205 */
     240, /* BlackGlasses; gba 206 */
     241, /* Black Belt; gba 207 */
     242, /* Magnet; gba 208 */
     243, /* Mystic Water; gba 209 */
     244, /* Sharp Beak; gba 210 */
     245, /* Poison Barb; gba 211 */
     246, /* NeverMeltIce; gba 212 */
     247, /* Spell Tag; gba 213 */
     248, /* TwistedSpoon; gba 214 */
     249, /* Charcoal; gba 215 */
     250, /* Dragon Fang; gba 216 */
     251, /* Silk Scarf; gba 217 */
     252, /* Up-Grade; gba 218 */
     253, /* Shell Bell; gba 219 */
     254, /* Sea Incense; gba 220 */
     255, /* Lax Incense; gba 221 */
     256, /* Lucky Punch; gba 222 */
     257, /* Metal Powder; gba 223 */
     258, /* Thick Club; gba 224 */
     259, /* Stick; gba 225 */
     260, /* Red Scarf; gba 254 */
     261, /* Blue Scarf; gba 255 */
     262, /* Pink Scarf; gba 256 */
     263, /* Green Scarf; gba 257 */
     264, /* Yellow Scarf; gba 258 */
     265, /* Wide Lens; no gba */
     266, /* Muscle Band; no gba */
     267, /* Wise Glasses; no gba */
     268, /* Expert Belt; no gba */
     269, /* Light Clay; no gba */
     270, /* Life Orb; no gba */
     271, /* Power Herb; no gba */
     272, /* Toxic Orb; no gba */
     273, /* Flame Orb; no gba */
     274, /* Quick Powder; no gba */
     275, /* Focus Sash; no gba */
     276, /* Zoom Lens; no gba */
     277, /* Metronome; no gba */
     278, /* Iron Ball; no gba */
     279, /* Lagging Tail; no gba */
     280, /* Destiny Knot; no gba */
     281, /* Black Sludge; no gba */
     282, /* Icy Rock; no gba */
     283, /* Smooth Rock; no gba */
     284, /* Heat Rock; no gba */
     285, /* Damp Rock; no gba */
     286, /* Grip Claw; no gba */
     287, /* Choice Scarf; no gba */
     288, /* Sticky Barb; no gba */
     289, /* Power Bracer; no gba */
     290, /* Power Belt; no gba */
     291, /* Power Lens; no gba */
     292, /* Power Band; no gba */
     293, /* Power Anklet; no gba */
     294, /* Power Weight; no gba */
     295, /* Shed Shell; no gba */
     296, /* Big Root; no gba */
     297, /* Choice Specs; no gba */
     298, /* Flame Plate; no gba */
     299, /* Splash Plate; no gba */
     300, /* Zap Plate; no gba */
     301, /* Meadow Plate; no gba */
     302, /* Icicle Plate; no gba */
     303, /* Fist Plate; no gba */
     304, /* Toxic Plate; no gba */
     305, /* Earth Plate; no gba */
     306, /* Sky Plate; no gba */
     307, /* Mind Plate; no gba */
     308, /* Insect Plate; no gba */
     309, /* Stone Plate; no gba */
     310, /* Spooky Plate; no gba */
     311, /* Draco Plate; no gba */
     312, /* Dread Plate; no gba */
     313, /* Iron Plate; no gba */
     314, /* Odd Incense; no gba */
     315, /* Rock Incense; no gba */
     316, /* Full Incense; no gba */
     317, /* Wave Incense; no gba */
     318, /* Rose Incense; no gba */
     319, /* Luck Incense; no gba */
     320, /* Pure Incense; no gba */
     321, /* Protector; no gba */
     322, /* Electirizer; no gba */
     323, /* Magmarizer; no gba */
     324, /* Dubious Disc; no gba */
     325, /* Reaper Cloth; no gba */
     326, /* Razor Claw; no gba */
     327, /* Razor Fang; no gba */
     328, /* TM01; gba 289 */
     329, /* TM02; gba 290 */
     330, /* TM03; gba 291 */
     331, /* TM04; gba 292 */
     332, /* TM05; gba 293 */
     333, /* TM06; gba 294 */
     334, /* TM07; gba 295 */
     335, /* TM08; gba 296 */
     336, /* TM09; gba 297 */
     337, /* TM10; gba 298 */
     338, /* TM11; gba 299 */
     339, /* TM12; gba 300 */
     340, /* TM13; gba 301 */
     341, /* TM14; gba 302 */
     342, /* TM15; gba 303 */
     343, /* TM16; gba 304 */
     344, /* TM17; gba 305 */
     345, /* TM18; gba 306 */
     346, /* TM19; gba 307 */
     347, /* TM20; gba 308 */
     348, /* TM21; gba 309 */
     349, /* TM22; gba 310 */
     350, /* TM23; gba 311 */
     351, /* TM24; gba 312 */
     352, /* TM25; gba 313 */
     353, /* TM26; gba 314 */
     354, /* TM27; gba 315 */
     355, /* TM28; gba 316 */
     356, /* TM29; gba 317 */
     357, /* TM30; gba 318 */
     358, /* TM31; gba 319 */
     359, /* TM32; gba 320 */
     360, /* TM33; gba 321 */
     361, /* TM34; gba 322 */
     362, /* TM35; gba 323 */
     363, /* TM36; gba 324 */
     364, /* TM37; gba 325 */
     365, /* TM38; gba 326 */
     366, /* TM39; gba 327 */
     367, /* TM40; gba 328 */
     368, /* TM41; gba 329 */
     369, /* TM42; gba 330 */
     370, /* TM43; gba 331 */
     371, /* TM44; gba 332 */
     372, /* TM45; gba 333 */
     373, /* TM46; gba 334 */
     374, /* TM47; gba 335 */
     375, /* TM48; gba 336 */
     376, /* TM49; gba 337 */
     377, /* TM50; gba 338 */
     378, /* TM51; no gba */
     379, /* TM52; no gba */
     380, /* TM53; no gba */
     381, /* TM54; no gba */
     382, /* TM55; no gba */
     383, /* TM56; no gba */
     384, /* TM57; no gba */
     385, /* TM58; no gba */
     386, /* TM59; no gba */
     387, /* TM60; no gba */
     388, /* TM61; no gba */
     389, /* TM62; no gba */
     390, /* TM63; no gba */
     391, /* TM64; no gba */
     392, /* TM65; no gba */
     393, /* TM66; no gba */
     394, /* TM67; no gba */
     395, /* TM68; no gba */
     396, /* TM69; no gba */
     397, /* TM70; no gba */
     398, /* TM71; no gba */
     399, /* TM72; no gba */
     400, /* TM73; no gba */
     401, /* TM74; no gba */
     402, /* TM75; no gba */
     403, /* TM76; no gba */
     404, /* TM77; no gba */
     405, /* TM78; no gba */
     406, /* TM79; no gba */
     407, /* TM80; no gba */
     408, /* TM81; no gba */
     409, /* TM82; no gba */
     410, /* TM83; no gba */
     411, /* TM84; no gba */
     412, /* TM85; no gba */
     413, /* TM86; no gba */
     414, /* TM87; no gba */
     415, /* TM88; no gba */
     416, /* TM89; no gba */
     417, /* TM90; no gba */
     418, /* TM91; no gba */
     419, /* TM92; no gba */
     420, /* HM01; gba 339 */
     421, /* HM02; gba 340 */
     422, /* HM03; gba 341 */
     423, /* HM04; gba 342 */
     424, /* HM05; gba 343 */
     425, /* HM06; gba 344 */
     428, /* Explorer Kit; no gba */
     429, /* Loot Sack; no gba */
     430, /* Rule Book; no gba */
     431, /* Poke Radar; no gba */
     432, /* Point Card; no gba */
     433, /* Journal; no gba */
     434, /* Seal Case; no gba */
     435, /* Fashion Case; no gba */
     436, /* Seal Bag; no gba */
     437, /* Pal Pad; no gba */
     438, /* Works Key; no gba */
     439, /* Old Charm; no gba */
     440, /* Galactic Key; no gba */
     441, /* Red Chain; no gba */
     442, /* Town Map; gba 361 */
     443, /* Vs. Seeker; gba 362 */
     444, /* Coin Case; gba 260 */
     445, /* Old Rod; gba 262 */
     446, /* Good Rod; gba 263 */
     447, /* Super Rod; gba 264 */
     448, /* Sprayduck; no gba */
     449, /* Poffin Case; no gba */
     450, /* Bicycle; gba 360 */
     451, /* Suite Key; no gba */
     452, /* Oaks Letter; no gba */
     453, /* Lunar Wing; no gba */
     454, /* Member Card; no gba */
     455, /* Azure Flute; no gba */
     456, /* S.S. Ticket; gba 265 */
     457, /* Contest Pass; gba 266 */
     458, /* Magma Stone; no gba */
     459, /* Parcel; gba 349 */
     460, /* Coupon 1; no gba */
     461, /* Coupon 2; no gba */
     462, /* Coupon 3; no gba */
     463, /* Storage Key; gba 285 */
     464, /* SecretPotion; no gba */
     465, /* Vs. Recorder; no gba */
     466, /* Gracidea; no gba */
     467, /* Secret Key; gba 351 */
};

#define MMO_ITEM_SHARED_COUNT 443

/* Three numberings, one Potion. Wire is region-5 + engine id.
 * gba 13 is a Dusk Ball in this engine. */
#define MMO_ITEM_WITNESS_POTION_WIRE      5017
#define MMO_ITEM_WITNESS_POTION_ENGINE    17
#define MMO_ITEM_WITNESS_POTION_GBA       13
#define MMO_ITEM_WITNESS_DUSKBALL_ENGINE  13
#define MMO_ITEM_WITNESS_DUSKBALL_GBA     0
#define MMO_ITEM_GBA_SET_COUNT            257
#define MMO_ITEM_GBA_NE_ENGINE_COUNT      245
