/* Generated by tools/portmoves.py --header; Do not edit. */

#define MMO_PORTED_MOVE_FIRST   468
#define MMO_PORTED_MOVE_LAST    559
#define MMO_PORTED_MOVE_SHARED  467  /* the last move both games have */

/* One donor per move from MMO_PORTED_MOVE_FIRST, in order. */
static const unsigned short MMO_PORTED_MOVE_ANIM[] = {
    14, 182, 385, 384, 433, 326, 124, 97, 78, 95, 433, 317, 233, 436,
    188, 349, 442, 296, 84, 392, 172, 349, 280, 51, 389, 388, 285, 226,
    304, 304, 290, 123, 60, 182, 100, 362, 187, 105, 247, 19, 97, 69,
    52, 259, 365, 160, 290, 120, 271, 436, 352, 52, 345, 85, 318, 89,
    181, 337, 74, 451, 344, 32, 337, 428, 202, 327, 401, 172, 75, 205,
    178, 399, 94, 154, 177, 36, 232, 436, 449, 161, 396, 62, 344, 126,
    436, 59, 59, 399, 8, 394, 126, 344,
};

/* What the shared range is allowed to disagree about, field by field. */
#define MMO_PORTED_MOVE_DIFF_ACCURACY     19
#define MMO_PORTED_MOVE_DIFF_CHANCE       10
#define MMO_PORTED_MOVE_DIFF_CLASS        0
#define MMO_PORTED_MOVE_DIFF_EFFECT       2
#define MMO_PORTED_MOVE_DIFF_FLAG_CONTACT 0
#define MMO_PORTED_MOVE_DIFF_FLAG_MAGIC_COAT 16
#define MMO_PORTED_MOVE_DIFF_FLAG_MIRROR_MOVE 0
#define MMO_PORTED_MOVE_DIFF_FLAG_PROTECT 4
#define MMO_PORTED_MOVE_DIFF_FLAG_SNATCH  12
#define MMO_PORTED_MOVE_DIFF_POWER        21
#define MMO_PORTED_MOVE_DIFF_PP           8
#define MMO_PORTED_MOVE_DIFF_PRIORITY     5
#define MMO_PORTED_MOVE_DIFF_RANGE        10
#define MMO_PORTED_MOVE_DIFF_TYPE         1
