/* Generated by tools/portspecies.py --header; Do not edit. */

#define MMO_PORTED_FIRST          494  /* first species a fill appends */
#define MMO_PORTED_LAST           649  /* last one */
/* pl_personal, wotbl and evo all held 508, so one base serves all three. */
#define MMO_PORTED_SPECIES_BASE   508
#define MMO_PORTED_ICON_BASE      547
/* The name bank keeps its egg names at 494 and 495, so names start after them. */
#define MMO_PORTED_NAME_BASE      496

/* One per species from MMO_PORTED_FIRST, in order. */
static const unsigned char MMO_PORTED_ICON_PALETTE[] = {
    0, 1, 1, 1, 0, 0, 0, 0, 0, 2, 2, 2, 2, 2, 2, 0, 0, 1, 1, 2, 2, 0, 0, 0, 0,
    0, 0, 0, 2, 2, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 2, 2, 0, 1, 0, 1, 1, 1, 1,
    0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 2, 1, 0, 0, 1, 0, 2, 2, 0, 0, 1,
    1, 0, 0, 0, 0, 2, 2, 2, 1, 1, 1, 0, 2, 0, 0, 0, 1, 1, 0, 0, 0, 2, 0, 0, 0,
    0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 2, 2, 2, 2, 1, 1, 2, 0, 0, 0, 0, 1, 2,
    0, 2, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 2, 0, 2, 2, 2, 0, 0, 0, 2, 1, 1, 0, 0,
    0, 0, 0, 0, 1, 2,
};


/*
 * This game's 100 machine bits against the cartridge's, matched by the move each teaches. -1
 * is one of ours the cartridge has no machine for, and its bit stays zero in a synthesised
 * entry, there is nothing on a Black cartridge to read it from.
 */
#define MMO_PORTED_MACHINES       100
static const signed char MMO_PORTED_MACHINE_BIT[MMO_PORTED_MACHINES] = {
    -1, 1, -1, 3, 4, 5, 6, 7, -1, 9, 10, 11, 12, 13, 14, 15, 16, 17, -1, 19,
    20, 21, -1, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, -1, 34, 35, 36, 37,
    38, 39, 40, 41, -1, 43, 44, 45, -1, -1, -1, 49, -1, 51, 52, 53, -1, 55,
    56, -1, -1, -1, 60, -1, 62, 63, 64, 65, -1, 67, 68, 69, 70, -1, 72, 73,
    74, -1, 76, -1, -1, 79, 80, -1, -1, 83, 84, 85, 86, 87, 88, 89, 90, 91,
    95, 96, 97, 98, -1, 93, 99, -1,
};

/*
 * Ours with no counterpart there, and the move each teaches: TM01(264) TM03(352) TM09(331)
 * TM19(202) TM23(231) TM34(351) TM43(290) TM47(211) TM48(285) TM49(289) TM51(355) TM55(362)
 * TM58(203) TM59(406) TM60(409) TM62(318) TM67(278) TM72(419) TM76(446) TM78(445) TM79(399)
 * TM82(214) TM83(363) HM05(432) HM08(431)
 */
