/* Generated by tools/gen_sprite_index.py; Do not edit. */

#define MMO_SPRITE_SPECIES_MAX       493  /* last species pl_pokegra holds */
#define MMO_SPRITE_EGG               494
#define MMO_SPRITE_BAD_EGG           495
#define MMO_SPRITE_POKEGRA_STRIDE    6
#define MMO_SPRITE_POKEGRA_MEMBERS   2964
#define MMO_SPRITE_OTHERPOKE_MEMBERS 253
#define MMO_SPRITE_GENDER_FEMALE     1  /* the id the default arm compares against */
#define MMO_SPRITE_FACE_BACK         0
#define MMO_SPRITE_FACE_FRONT        2
#define MMO_SPRITE_SPINDA            327  /* the one front sprite drawn from personality */

/* species -> how many forms the engine will draw for it */
static const struct {
    short species;
    short forms;
} MMO_SPRITE_FORMS[] = {
    { 201, 28 },
    { 351,  4 },
    { 386,  4 },
    { 412,  3 },
    { 413,  3 },
    { 421,  2 },
    { 422,  2 },
    { 423,  2 },
    { 479,  6 },
    { 487,  2 },
    { 492,  2 },
    { 493, 18 },
    { 494,  2 },
};
#define MMO_SPRITE_FORMS_COUNT 13

/* The pl_otherpoke cases:
 *   character = char_base + char_face * (face / char_face_div) + char_form * form
 *   palette   = pal_base  + pal_shiny * shiny                  + pal_form  * form */
static const struct {
    short species;
    short char_base, char_face, char_face_div, char_form;
    short pal_base, pal_shiny, pal_form;
} MMO_SPRITE_OTHERPOKE[] = {
    { 201,   8, 1, 2, 2, 156, 1, 0 }, /* SPECIES_UNOWN     */
    { 351,  64, 2, 1, 1, 158, 4, 1 }, /* SPECIES_CASTFORM  */
    { 386,   0, 1, 2, 2, 154, 1, 0 }, /* SPECIES_DEOXYS    */
    { 412,  72, 1, 2, 2, 166, 1, 2 }, /* SPECIES_BURMY     */
    { 413,  78, 1, 2, 2, 172, 1, 2 }, /* SPECIES_WORMADAM  */
    { 421,  92, 1, 1, 1, 186, 2, 1 }, /* SPECIES_CHERRIM   */
    { 422,  84, 1, 1, 1, 178, 1, 2 }, /* SPECIES_SHELLOS   */
    { 423,  88, 1, 1, 1, 182, 1, 2 }, /* SPECIES_GASTRODON */
    { 479, 138, 1, 2, 2, 232, 1, 2 }, /* SPECIES_ROTOM     */
    { 487, 150, 1, 2, 2, 244, 1, 2 }, /* SPECIES_GIRATINA  */
    { 492, 134, 1, 2, 2, 228, 1, 2 }, /* SPECIES_SHAYMIN   */
    { 493,  96, 1, 2, 2, 190, 1, 2 }, /* SPECIES_ARCEUS    */
    { 494, 132, 0, 1, 1, 226, 0, 1 }, /* SPECIES_EGG       */
    { 495, 132, 0, 1, 0, 226, 0, 0 }, /* SPECIES_BAD_EGG   */
};
#define MMO_SPRITE_OTHERPOKE_COUNT 14
