-- The shelf grows the official client's economics.
ALTER TABLE gtl_listings ADD COLUMN remaining INT NOT NULL DEFAULT 0;
ALTER TABLE gtl_listings ADD COLUMN unclaimed_units INT NOT NULL DEFAULT 0;
ALTER TABLE gtl_listings ADD COLUMN fee INT NOT NULL DEFAULT 0;
ALTER TABLE gtl_listings ADD COLUMN last_price_change TIMESTAMP;

-- [jooq ignore start]
-- Standing rows predate unit fills: everything active still holds its whole
-- quantity. The generator does not need the backfill, only the columns.
UPDATE gtl_listings SET remaining = quantity WHERE state = 0;
-- [jooq ignore stop]

CREATE TABLE gtl_sales (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  listing_id  BIGINT      NOT NULL,
  seller_id   BIGINT      NOT NULL,
  seller_name VARCHAR(32) NOT NULL,
  buyer_id    BIGINT      NOT NULL,
  buyer_name  VARCHAR(32) NOT NULL,
  -- 0 a monster, 1 an item stack; a snapshot, so the log survives the listing.
  kind        SMALLINT    NOT NULL,
  item_id     INT,
  mon_dex_id  INT,
  mon_level   SMALLINT,
  quantity    INT         NOT NULL,
  unit_price  INT         NOT NULL,
  sold_at     TIMESTAMP   NOT NULL
);

CREATE INDEX idx_gtl_sales_seller ON gtl_sales (seller_id, sold_at);
CREATE INDEX idx_gtl_sales_buyer ON gtl_sales (buyer_id, sold_at);
