-- The player mailbox, which until now lived in a map and died with the server.
CREATE TABLE mail_messages (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_id       BIGINT        NOT NULL REFERENCES characters (id) ON DELETE CASCADE,
  -- 0 the owner's inbox, 1 the owner's sent box.
  box            SMALLINT      NOT NULL,
  -- 0 is the system, which has no character row of its own.
  sender_id      BIGINT        NOT NULL,
  sender_name    VARCHAR(32)   NOT NULL,
  recipient_id   BIGINT        NOT NULL,
  recipient_name VARCHAR(32)   NOT NULL,
  subject        VARCHAR(64)   NOT NULL,
  body           VARCHAR(2048) NOT NULL,
  sent_at        TIMESTAMP     NOT NULL,
  unread         BOOLEAN       NOT NULL DEFAULT TRUE
);

CREATE INDEX idx_mail_box ON mail_messages (owner_id, box, id);
