-- Friends, blocked players and guilds, which until now lived in maps and died with the process.
CREATE TABLE social_contacts (
  id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  -- Account id from the login database. That is another database, so no FK.
  user_id INT         NOT NULL,
  -- 0 a friend, 1 a blocked player.
  kind    SMALLINT    NOT NULL,
  -- The name as it was typed. A contact may name a character that has not been
  -- made yet, so this is a name and not a reference.
  name    VARCHAR(32) NOT NULL
);

-- The list is drawn in the order names were added, which is the id order.
CREATE UNIQUE INDEX idx_social_contact ON social_contacts (user_id, kind, name);

-- One team. Founding one costs the founder money, so it has to outlive the
-- session that founded it.
CREATE TABLE guilds (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name       VARCHAR(24)  NOT NULL,
  tag        VARCHAR(8)   NOT NULL,
  message    VARCHAR(200) NOT NULL,
  -- A field of the profile the client is sent whose meaning is not established
  -- by a capture. Carried verbatim rather than given a name it may not have.
  unknown    INT          NOT NULL DEFAULT 0,
  -- Unix seconds, which is how both of these sit on the wire.
  founded_at INT          NOT NULL,
  expiry     INT          NOT NULL DEFAULT 0
);

CREATE TABLE guild_members (
  id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  guild_id     BIGINT      NOT NULL REFERENCES guilds (id) ON DELETE CASCADE,
  -- A character is in at most one guild, so the roster is unique across every
  -- guild rather than within one. That uniqueness is the membership lookup.
  character_id BIGINT      NOT NULL UNIQUE REFERENCES characters (id) ON DELETE CASCADE,
  -- Kept beside the id because the roster is drawn for members who are offline,
  -- whose character row is not loaded.
  name         VARCHAR(32) NOT NULL,
  rank_ordinal SMALLINT    NOT NULL,
  leader       BOOLEAN     NOT NULL DEFAULT FALSE
);

CREATE INDEX idx_guild_members_guild ON guild_members (guild_id);

-- One row per rank ordinal: the label the leader gave that seat, and the permission mask the seat
-- carries. The Boss holds the guild and is not permissioned, so its mask is unused rather than
-- absent.
CREATE TABLE guild_ranks (
  guild_id     BIGINT      NOT NULL REFERENCES guilds (id) ON DELETE CASCADE,
  rank_ordinal SMALLINT    NOT NULL,
  label        VARCHAR(16) NOT NULL DEFAULT '',
  perm_mask    SMALLINT    NOT NULL DEFAULT 0,
  PRIMARY KEY (guild_id, rank_ordinal)
);

-- What the team has done, which its activity page reads back.
CREATE TABLE guild_activity (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  guild_id    BIGINT      NOT NULL REFERENCES guilds (id) ON DELETE CASCADE,
  entry_type  SMALLINT    NOT NULL,
  actor       VARCHAR(32) NOT NULL,
  target      VARCHAR(32) NOT NULL,
  happened_at INT         NOT NULL
);

CREATE INDEX idx_guild_activity_guild ON guild_activity (guild_id, id);
