-- The global trade link's shelf.
CREATE TABLE gtl_listings (
  id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  seller_id      BIGINT      NOT NULL REFERENCES characters (id) ON DELETE CASCADE,
  seller_name    VARCHAR(32) NOT NULL,
  -- 0 a monster, 1 an item stack; GtlListKind's own ids.
  kind           SMALLINT    NOT NULL,
  item_id        INT,
  quantity       INT         NOT NULL DEFAULT 1,
  price          INT         NOT NULL,
  -- 0 active, 1 sold and unpaid, 2 closed (paid out, taken back, or returned).
  state          SMALLINT    NOT NULL DEFAULT 0,
  buyer_id       BIGINT,
  buyer_name     VARCHAR(32),
  listed_at      TIMESTAMP   NOT NULL,
  expires_at     TIMESTAMP   NOT NULL,
  sold_at        TIMESTAMP,

  -- The escrowed monster, column for column what a pokemon row holds. Null for an item listing.
  mon_id                   BIGINT,
  mon_dex_id               INT,
  mon_seed                 INT,
  mon_ot                   VARCHAR(32),
  mon_nickname             VARCHAR(32),
  mon_level                SMALLINT,
  mon_hp                   SMALLINT,
  mon_xp                   INT,
  mon_ev_hp                SMALLINT,
  mon_ev_atk               SMALLINT,
  mon_ev_def               SMALLINT,
  mon_ev_sp_atk            SMALLINT,
  mon_ev_sp_def            SMALLINT,
  mon_ev_spd               SMALLINT,
  mon_iv_hp                SMALLINT,
  mon_iv_atk               SMALLINT,
  mon_iv_def               SMALLINT,
  mon_iv_sp_atk            SMALLINT,
  mon_iv_sp_def            SMALLINT,
  mon_iv_spd               SMALLINT,
  mon_move1_id             SMALLINT,
  mon_move1_pp             SMALLINT,
  mon_move2_id             SMALLINT,
  mon_move2_pp             SMALLINT,
  mon_move3_id             SMALLINT,
  mon_move3_pp             SMALLINT,
  mon_move4_id             SMALLINT,
  mon_move4_pp             SMALLINT,
  mon_is_shiny             BOOLEAN,
  mon_has_hidden_ability   BOOLEAN,
  mon_is_alpha             BOOLEAN,
  mon_is_secret            BOOLEAN,
  mon_is_fateful_encounter BOOLEAN,
  mon_is_raid_encounter    BOOLEAN,
  mon_is_egg               BOOLEAN,
  mon_caught_at            TIMESTAMP
);

CREATE INDEX idx_gtl_listings_shelf ON gtl_listings (state, kind, mon_dex_id);
CREATE INDEX idx_gtl_listings_item ON gtl_listings (state, kind, item_id);
CREATE INDEX idx_gtl_listings_seller ON gtl_listings (seller_id, state);
