package de.fiereu.openmmo.launcher.launch

import java.io.StringReader
import java.nio.file.Files
import java.nio.file.Path
import java.security.KeyFactory
import java.security.PrivateKey
import java.security.PublicKey
import java.security.spec.PKCS8EncodedKeySpec
import java.security.spec.X509EncodedKeySpec
import kotlin.io.encoding.Base64
import org.bouncycastle.util.io.pem.PemReader

private const val PACKAGED_RESOURCES = "compose.application.resources.dir"

// Generated by :keys, so a manifest names them with replace_ref instead of carrying the values.
object GeneratedKeys {

  const val GAME_PUBLIC = "key.game.public"
  const val CHAT_PUBLIC = "key.chat.public"
  const val FEED_PUBLIC = "key.feed.public"

  fun publicKeyBase64(resource: String): String = Base64.Default.encode(readPem(resource))

  fun privateKey(resource: String): PrivateKey =
      KeyFactory.getInstance("RSA").generatePrivate(PKCS8EncodedKeySpec(readPem(resource)))

  /** The one key a build pins, so everything the feed origin serves is checked against it. */
  fun feedPublicKey(): PublicKey =
      KeyFactory.getInstance("RSA").generatePublic(X509EncodedKeySpec(readPem("/feed.public.pem")))

  fun values(): Map<String, String> =
      mapOf(
          GAME_PUBLIC to publicKeyBase64("/game.public.pem"),
          CHAT_PUBLIC to publicKeyBase64("/chat.public.pem"),
          FEED_PUBLIC to publicKeyBase64("/feed.public.pem"),
      )

  // Jars exclude *.pem, so a packaged build finds keys beside the binary.
  fun readPem(path: String): ByteArray {
    val pem =
        fromClasspath(path)
            ?: fromResourcesDir(path)
            ?: throw IllegalArgumentException(
                "Key not found at path: $path. Run :keys:generate or ship the keys beside the " +
                    "launcher, because jars carry none.")
    return PemReader(StringReader(pem)).readPemObject().content
  }

  private fun fromClasspath(path: String): String? =
      GeneratedKeys::class.java.getResourceAsStream(path)?.use { it.readBytes().decodeToString() }

  private fun fromResourcesDir(path: String): String? {
    val directory = System.getProperty(PACKAGED_RESOURCES) ?: return null
    val file = Path.of(directory).resolve(path.removePrefix("/"))
    return if (Files.isRegularFile(file)) Files.readString(file) else null
  }
}
