# OpenMMO website.

<VirtualHost *:80>
    ServerName openmmo.dev
    ServerAlias www.openmmo.dev

    Include /etc/apache2/openmmo-body.conf

    ErrorLog ${APACHE_LOG_DIR}/openmmo-error.log
    CustomLog ${APACHE_LOG_DIR}/openmmo-access.log combined
</VirtualHost>

<IfModule ssl_module>
<IfFile /etc/ssl/openmmo/origin.pem>
<VirtualHost *:443>
    ServerName openmmo.dev
    ServerAlias www.openmmo.dev

    SSLEngine on
    SSLCertificateFile /etc/ssl/openmmo/origin.pem
    SSLCertificateKeyFile /etc/ssl/openmmo/origin.key

    Include /etc/apache2/openmmo-body.conf

    ErrorLog ${APACHE_LOG_DIR}/openmmo-error.log
    CustomLog ${APACHE_LOG_DIR}/openmmo-access.log combined
</VirtualHost>
</IfFile>
</IfModule>
