package de.fiereu.openmmo.server.game.services.command

import de.fiereu.openmmo.common.enums.Direction
import de.fiereu.openmmo.common.enums.Region
import de.fiereu.openmmo.server.game.script.Badge
import de.fiereu.openmmo.story.generated.sinnoh.SinnohFlags
import de.fiereu.openmmo.story.generated.sinnoh.SinnohVars

private val TURTWIG = CheckpointMon(dexId = 387, level = 5, moveIds = listOf(33, 110))

/** One Empoleon that knows every HM wall this server can still see. */
private val WALL_WALKER = CheckpointMon(dexId = 395, level = 40, moveIds = listOf(57, 70, 127, 431))

private val OPENING = SinnohFlags.initiallySet

private val ALL_BADGES = Badge.entries.map { it.keyIn("sinnoh") }.toSet()

/** Skip the "walk in and slam the door" frame script so A still faces the fighter. */
private val LEAGUE_ROOM = mapOf(SinnohVars.VAR_MAP_LOCAL_0x01 to 1)
private val CYNTHIA_ROOM = mapOf(SinnohVars.VAR_MAP_LOCAL_0x03 to 1)

private val AFTER_STARTER = OPENING - setOf(SinnohFlags.FLAG_HIDE_ROUTE_201_BRIEFCASE)

val SINNOH_CHECKPOINTS: List<StoryCheckpoint> =
    listOf(
        StoryCheckpoint(
            name = "twinleaf-rival",
            description = "the bedroom bed, one step from the rival's four-tile trigger",
            region = Region.SINNOH,
            bankId = 1,
            mapId = 159,
            x = 4,
            y = 6,
            facing = Direction.DOWN,
            storyFlags = OPENING,
            storyVars =
                mapOf(
                    SinnohVars.VAR_TWINLEAF_TOWN_GUITARIST_TRIGGER_STATE to 1,
                    SinnohVars.VAR_OREBURGH_GATE_1F_HIKER_STATE to 1,
                    SinnohVars.VAR_CONSECUTIVE_BONUS_ROUND_WINS to 9,
                ),
        ),
        StoryCheckpoint(
            name = "route-201-starter",
            description = "south of Route 201's four-tile briefcase trigger",
            region = Region.SINNOH,
            bankId = 1,
            mapId = 86,
            x = 112,
            y = 858,
            facing = Direction.UP,
            storyFlags = OPENING,
        ),
        StoryCheckpoint(
            name = "route-201-briefcase",
            description = "south of the briefcase, the approach already spent",
            region = Region.SINNOH,
            bankId = 1,
            mapId = 86,
            x = 112,
            y = 855,
            facing = Direction.UP,
            storyFlags =
                OPENING -
                    setOf(
                        SinnohFlags.FLAG_HIDE_ROUTE_201_BRIEFCASE,
                        SinnohFlags.FLAG_HIDE_ROUTE_201_PROF_ROWAN,
                    ),
            storyVars = mapOf(SinnohVars.VAR_FOLLOWER_RIVAL_STATE to 1),
        ),
        StoryCheckpoint(
            name = "route-201-grass",
            description = "Route 201 tall grass, with a party so an encounter can roll",
            region = Region.SINNOH,
            bankId = 1,
            mapId = 86,
            x = 138,
            y = 842,
            facing = Direction.UP,
            storyFlags = AFTER_STARTER,
            storyVars = mapOf(SinnohVars.VAR_FOLLOWER_RIVAL_STATE to 1),
            party = listOf(TURTWIG),
        ),
        StoryCheckpoint(
            name = "gym-roark",
            description = "in front of Roark, Coal Badge not yet held",
            region = Region.SINNOH,
            bankId = 0,
            mapId = 47,
            x = 5,
            y = 4,
            facing = Direction.UP,
            storyFlags = AFTER_STARTER,
            party = listOf(TURTWIG),
        ),
        StoryCheckpoint(
            name = "gym-gardenia",
            description = "in front of Gardenia, Forest Badge not yet held",
            region = Region.SINNOH,
            bankId = 0,
            mapId = 67,
            x = 11,
            y = 4,
            facing = Direction.UP,
            storyFlags = AFTER_STARTER - setOf(SinnohFlags.FLAG_HIDE_ETERNA_CITY_GYM_GARDENIA),
            party = listOf(TURTWIG),
        ),
        StoryCheckpoint(
            name = "gym-maylene",
            description = "in front of Maylene, Cobble Badge not yet held",
            region = Region.SINNOH,
            bankId = 0,
            mapId = 133,
            x = 12,
            y = 5,
            facing = Direction.UP,
            storyFlags = AFTER_STARTER - setOf(SinnohFlags.FLAG_HIDE_VEILSTONE_CITY_GYM_MAYLENE),
            party = listOf(TURTWIG),
        ),
        StoryCheckpoint(
            name = "gym-wake",
            description = "in front of Crasher Wake, Fen Badge not yet held",
            region = Region.SINNOH,
            bankId = 0,
            mapId = 122,
            x = 13,
            y = 5,
            facing = Direction.UP,
            storyFlags =
                AFTER_STARTER - setOf(SinnohFlags.FLAG_HIDE_PASTORIA_CITY_GYM_CRASHER_WAKE),
            party = listOf(TURTWIG),
        ),
        StoryCheckpoint(
            name = "gym-fantina",
            description = "in front of Fantina, Relic Badge not yet held",
            region = Region.SINNOH,
            bankId = 0,
            mapId = 91,
            x = 4,
            y = 11,
            facing = Direction.UP,
            storyFlags = AFTER_STARTER,
            party = listOf(TURTWIG),
        ),
        StoryCheckpoint(
            name = "gym-byron",
            description = "in front of Byron, Mine Badge not yet held",
            region = Region.SINNOH,
            bankId = 0,
            mapId = 35,
            x = 16,
            y = 4,
            facing = Direction.UP,
            storyFlags = AFTER_STARTER,
            party = listOf(TURTWIG),
        ),
        StoryCheckpoint(
            name = "gym-candice",
            description = "in front of Candice, Icicle Badge not yet held",
            region = Region.SINNOH,
            bankId = 0,
            mapId = 167,
            x = 11,
            y = 4,
            facing = Direction.UP,
            storyFlags = AFTER_STARTER,
            party = listOf(TURTWIG),
        ),
        StoryCheckpoint(
            name = "gym-volkner",
            description = "in front of Volkner, Beacon Badge not yet held",
            region = Region.SINNOH,
            bankId = 0,
            mapId = 156,
            x = 11,
            y = 4,
            facing = Direction.UP,
            storyFlags = AFTER_STARTER,
            party = listOf(TURTWIG),
        ),
        StoryCheckpoint(
            name = "hm-surf",
            description = "Twinleaf's southern shore, Fen Badge and Surf in the party",
            region = Region.SINNOH,
            bankId = 1,
            mapId = 155,
            x = 112,
            y = 890,
            facing = Direction.DOWN,
            storyFlags = AFTER_STARTER + Badge.FEN.keyIn("sinnoh"),
            party = listOf(WALL_WALKER),
        ),
        StoryCheckpoint(
            name = "hm-strength",
            description = "west of Oreburgh Gate B1F's (8, 12) boulder, Mine Badge and Strength",
            region = Region.SINNOH,
            bankId = 1,
            mapId = 3,
            x = 7,
            y = 12,
            facing = Direction.RIGHT,
            storyFlags = AFTER_STARTER + Badge.MINE.keyIn("sinnoh"),
            party = listOf(WALL_WALKER),
        ),
        StoryCheckpoint(
            name = "hm-waterfall",
            description = "facing a waterfall tile, Beacon Badge and Waterfall in the party",
            region = Region.SINNOH,
            bankId = 0,
            mapId = 172,
            x = 842,
            y = 570,
            facing = Direction.UP,
            storyFlags = AFTER_STARTER + Badge.BEACON.keyIn("sinnoh"),
            party = listOf(WALL_WALKER),
        ),
        StoryCheckpoint(
            name = "hm-rock-climb",
            description = "facing a rock face, Icicle Badge and Rock Climb in the party",
            region = Region.SINNOH,
            bankId = 0,
            mapId = 132,
            x = 691,
            y = 614,
            facing = Direction.DOWN,
            storyFlags = AFTER_STARTER + Badge.ICICLE.keyIn("sinnoh"),
            party = listOf(WALL_WALKER),
        ),
        StoryCheckpoint(
            name = "league-aaron",
            description = "in front of Aaron",
            region = Region.SINNOH,
            bankId = 0,
            mapId = 177,
            x = 8,
            y = 6,
            facing = Direction.UP,
            storyFlags = AFTER_STARTER + ALL_BADGES,
            storyVars = LEAGUE_ROOM,
            party = listOf(WALL_WALKER),
        ),
        StoryCheckpoint(
            name = "league-bertha",
            description = "in front of Bertha",
            region = Region.SINNOH,
            bankId = 0,
            mapId = 179,
            x = 8,
            y = 6,
            facing = Direction.UP,
            storyFlags = AFTER_STARTER + ALL_BADGES,
            storyVars = LEAGUE_ROOM,
            party = listOf(WALL_WALKER),
        ),
        StoryCheckpoint(
            name = "league-flint",
            description = "in front of Flint",
            region = Region.SINNOH,
            bankId = 0,
            mapId = 181,
            x = 8,
            y = 6,
            facing = Direction.UP,
            storyFlags = AFTER_STARTER + ALL_BADGES,
            storyVars = LEAGUE_ROOM,
            party = listOf(WALL_WALKER),
        ),
        StoryCheckpoint(
            name = "league-lucian",
            description = "in front of Lucian",
            region = Region.SINNOH,
            bankId = 0,
            mapId = 183,
            x = 8,
            y = 6,
            facing = Direction.UP,
            storyFlags = AFTER_STARTER + ALL_BADGES,
            storyVars = LEAGUE_ROOM,
            party = listOf(WALL_WALKER),
        ),
        StoryCheckpoint(
            name = "league-cynthia",
            description = "in front of Cynthia",
            region = Region.SINNOH,
            bankId = 0,
            mapId = 185,
            x = 8,
            y = 12,
            facing = Direction.UP,
            storyFlags = AFTER_STARTER + ALL_BADGES,
            storyVars = CYNTHIA_ROOM,
            party = listOf(WALL_WALKER),
        ),
        StoryCheckpoint(
            name = "hall-of-fame",
            description = "the Hall of Fame entrance, frame script about to record the party",
            region = Region.SINNOH,
            bankId = 0,
            mapId = 187,
            x = 8,
            y = 14,
            facing = Direction.UP,
            storyFlags = AFTER_STARTER + ALL_BADGES,
            party = listOf(WALL_WALKER),
        ),
    )
