package de.fiereu.openmmo.codegen.pokemon

data class ParsedSpecies(
    val id: Int,
    val name: String,
    val baseHp: Int,
    val baseAttack: Int,
    val baseDefense: Int,
    val baseSpeed: Int,
    val baseSpAttack: Int,
    val baseSpDefense: Int,
    val type1: String,
    val type2: String,
    val catchRate: Int,
    val expYield: Int,
    val evYieldHp: Int,
    val evYieldAttack: Int,
    val evYieldDefense: Int,
    val evYieldSpeed: Int,
    val evYieldSpAttack: Int,
    val evYieldSpDefense: Int,
    val itemCommon: Int,
    val itemRare: Int,
    val genderRatio: Int,
    val eggCycles: Int,
    val friendship: Int,
    val growthRate: String,
    val eggGroup1: String,
    val eggGroup2: String,
    val ability1: String,
    val ability2: String,
    val safariZoneFleeRate: Int,
    val bodyColor: String,
    val flipSprite: Boolean,
)
