#!/usr/bin/env python3
"""Stage the APK's resource tree with an optional name and icon."""

import argparse
import shutil
import sys
from pathlib import Path

# density directory, legacy icon side, adaptive layer side. The legacy icon is
# 48dp and the adaptive layers are 108dp; every row below is those two figures
# at that density's scale, which is what the committed art already measures.
DENSITIES = [
    ("mipmap-mdpi", 48, 108),
    ("mipmap-hdpi", 72, 162),
    ("mipmap-xhdpi", 96, 216),
    ("mipmap-xxhdpi", 144, 324),
    ("mipmap-xxxhdpi", 192, 432),
]

# The fraction of an adaptive layer a launcher's mask is guaranteed to show,
# 72dp of 108dp, which is Android's own figure. A person handing over one
# square logo means "use this", so the art is scaled into the safe zone and the
# ground behind it comes from --icon-bg, rather than letting a round mask eat
# its corners.
SAFE_ZONE = 2.0 / 3.0

STRINGS = """<?xml version="1.0" encoding="utf-8"?>
<!--
  GENERATED by mmo/tools/apkbrand.py into the build tree. The copy under
  mmo/android/res is the default and the one to edit; this one is overwritten
  on every build from APK_LABEL.
-->
<resources>
  <string name="app_name">%s</string>
</resources>
"""


def android_string(text):
    """Escape one label for a string resource.

    Two rules apply at once. The file is XML, so & < > are markup. The value is
    also an Android string, where a bare apostrophe or quote is an error, a
    leading @ or ? means a resource reference, and leading or trailing
    whitespace is stripped unless the whole value is quoted.
    """
    out = text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
    out = out.replace("\\", "\\\\").replace("'", "\\'").replace('"', "\\&quot;")
    if out[:1] in ("@", "?"):
        out = "\\" + out
    if text != text.strip():
        out = '"%s"' % out
    return out


def parse_colour(spec):
    """#rgb, #rrggbb or #aarrggbb into an RGBA tuple."""
    digits = spec.lstrip("#")
    if len(digits) == 3:
        digits = "".join(c * 2 for c in digits)
    if len(digits) == 6:
        digits = "ff" + digits
    if len(digits) != 8:
        raise SystemExit(
            "apkbrand: --icon-bg %s is neither a colour (#rrggbb) nor a file" % spec
        )
    try:
        value = int(digits, 16)
    except ValueError:
        raise SystemExit("apkbrand: --icon-bg %s is not a hex colour" % spec)
    return (
        (value >> 16) & 0xFF,
        (value >> 8) & 0xFF,
        value & 0xFF,
        (value >> 24) & 0xFF,
    )


def fit(image, side, inset=1.0):
    """The source, centred on a transparent square of `side`, at `inset` of it.

    Aspect ratio is kept, so a tall logo and a wide one both land centred with
    the spare axis transparent rather than stretched to the tile.
    """
    from PIL import Image

    box = max(1, int(round(side * inset)))
    art = image.copy()
    art.thumbnail((box, box), Image.LANCZOS)
    tile = Image.new("RGBA", (side, side), (0, 0, 0, 0))
    tile.paste(art, ((side - art.width) // 2, (side - art.height) // 2), art)
    return tile


def write_icons(res, icon_path, bg_spec):
    try:
        from PIL import Image
    except ImportError:
        raise SystemExit(
            "apkbrand: --icon needs Pillow (pip install --user Pillow), which\n"
            "apkbrand: the rest of mmo/tools already depends on"
        )

    # The ground first, so a misspelt colour fails before any note about the
    # source is printed. A picture wins over a colour, and the leading # is
    # optional because a `#` in a makefile starts a comment, so the default in
    # Makefile.android is written bare and both spellings have to work.
    ground = None
    colour = None
    if Path(bg_spec).is_file():
        ground = Image.open(bg_spec).convert("RGBA")
    else:
        colour = parse_colour(bg_spec)

    source = Image.open(icon_path).convert("RGBA")
    if source.width != source.height:
        print(
            "  BRAND   note: %s is %dx%d, not square; it is centred, not stretched"
            % (Path(icon_path).name, source.width, source.height)
        )

    for name, legacy, adaptive in DENSITIES:
        out = res / name
        out.mkdir(parents=True, exist_ok=True)
        # The legacy icon fills its tile: it is masked by nobody. Nothing this
        # app ships to reads it as the launcher icon any more, but a share
        # sheet, a notification and `aapt dump badging` still reach for it, and
        # leaving the old art there is how a rebranded build keeps answering
        # with the name it used to have.
        fit(source, legacy).save(out / "ic_launcher.png")
        # The foreground is held inside the safe zone so a round mask cannot
        # bite the art.
        fit(source, adaptive, SAFE_ZONE).save(out / "ic_launcher_fg.png")
        if ground is not None:
            # A background is scaled to the whole square, not the safe zone: a
            # mask is supposed to crop one.
            fit(ground, adaptive).save(out / "ic_launcher_bg.png")
        else:
            Image.new("RGBA", (adaptive, adaptive), colour).save(
                out / "ic_launcher_bg.png"
            )


def main():
    ap = argparse.ArgumentParser(description="stage the APK resource tree")
    ap.add_argument("--res", required=True, help="the committed res tree")
    ap.add_argument("--out", required=True, help="where to stage it")
    ap.add_argument("--label", required=True, help="the name a launcher shows")
    ap.add_argument("--icon", default="", help="one square image, the whole icon")
    ap.add_argument(
        "--icon-bg",
        default="#191F28",
        help="the adaptive icon's ground: rrggbb, #rrggbb or an image "
        "(default: the committed icon's own ground)",
    )
    args = ap.parse_args()

    src = Path(args.res)
    if not src.is_dir():
        raise SystemExit("apkbrand: no resource tree at %s" % src)
    if args.icon and not Path(args.icon).is_file():
        raise SystemExit("apkbrand: no icon at %s" % args.icon)

    # A staged tree rather than a second -R overlay: overlay precedence is per
    # resource and per qualifier, so an override that supplies only one density
    # leaves the other four and the adaptive XML pointing at the old art, and
    # the icon comes out rebranded on one device and original on the next.
    out = Path(args.out)
    if out.exists():
        shutil.rmtree(out)
    shutil.copytree(src, out)

    (out / "values").mkdir(parents=True, exist_ok=True)
    (out / "values" / "strings.xml").write_text(
        STRINGS % android_string(args.label), encoding="utf-8"
    )

    if args.icon:
        write_icons(out, args.icon, args.icon_bg)
        print("  BRAND   %s, icon %s" % (args.label, Path(args.icon).name))
    else:
        print("  BRAND   %s" % args.label)
    return 0


if __name__ == "__main__":
    sys.exit(main())
