#!/usr/bin/env python3
"""Freeze a file into a C array the build compiles in."""

import sys


def main(argv):
    if len(argv) != 4:
        sys.stderr.write("usage: bin2c.py INPUT OUTPUT.c SYMBOL\n")
        return 2
    src, dst, sym = argv[1], argv[2], argv[3]
    with open(src, "rb") as f:
        data = f.read()
    name = src.replace("\\", "/").rsplit("/", 1)[-1]
    out = ["/* Generated by mmo/tools/bin2c.py from %s. Do not edit,\n"
           " * do not commit: the Makefile rebuilds it from the file itself. */\n"
           "#include <stddef.h>\n\n"
           "const unsigned char %s[] = {" % (name, sym)]
    for i, b in enumerate(data):
        out.append("\n    " if i % 16 == 0 else "")
        out.append("%d," % b)
    out.append("\n};\n\nconst size_t %s_len = %d;\n" % (sym, len(data)))
    with open(dst, "w") as f:
        f.write("".join(out))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
