#!/usr/bin/env python3
"""Generate the table that says what a HeartGold hidden item is."""
from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

MMO = Path(__file__).resolve().parent.parent

HIDDEN_ITEM_BASE = 8000        # _std_hidden_item
ROW = re.compile(r"\{\s*(ITEM_\w+)\s*,\s*(\d+)\s*,\s*(\d+)\s*,\s*(\d+)\s*,"
                 r"\s*(\d+)\s*\}")


def die(msg: str) -> None:
    print("gen_hidden_items: " + msg, file=sys.stderr)
    raise SystemExit(2)


def decomp_dir(name: str) -> Path | None:
    try:
        out = subprocess.run([str(MMO / "tools" / "decomp_dir.sh"), name],
                             capture_output=True, text=True, check=True)
    except (OSError, subprocess.CalledProcessError):
        return None
    return Path(out.stdout.strip())


def defines(path: Path, prefix: str) -> dict[str, int]:
    out: dict[str, int] = {}
    if not path.is_file():
        return out
    for line in path.read_text().splitlines():
        m = re.match(r"#define (%s\w+)\s+(0x[0-9A-Fa-f]+|\d+)\b" % prefix, line)
        if m:
            out[m.group(1)] = int(m.group(2), 0)
    return out


def main(argv: list[str]) -> int:
    hg = Path(argv[1]) if len(argv) > 1 else decomp_dir("pokeheartgold")
    out = Path(argv[2]) if len(argv) > 2 else MMO / "HIDDEN_ITEMS"
    if hg is None:
        die("need a heartgold checkout; pass one or set DECOMP_DIR")

    items = defines(hg / "include/constants/items.h", "ITEM_")
    names = defines(hg / "include/constants/std_script.h", "std_hiddenitem_")
    table = hg / "src/data/fieldmap/hidden_items.h"
    if not items or not names or not table.is_file():
        die("need items.h, std_script.h and %s under %s" % (table.name, hg))
    by_index = {v - HIDDEN_ITEM_BASE: k for k, v in names.items()}

    rows = []
    seen: set[int] = set()
    for m in ROW.finditer(table.read_text()):
        item, qty, rng, _pad, index = m.groups()
        index = int(index)
        if item not in items:
            die("row %d names %s, which items.h does not define" % (index, item))
        if index in seen:
            die("index %d appears twice in %s" % (index, table.name))
        seen.add(index)
        name = by_index.get(index)
        if name is None:
            die("index %d has a row and no std_hiddenitem_ name" % index)
        # The name ends in the item, in lower case with the game's own
        # spelling (tm26, pp_max, heart_scale), then a number when one map
        # buries the same item twice; the row has to say the same item.
        want = item[len("ITEM_"):].lower()
        base = re.sub(r"_\d+$", "", name)
        if not base.endswith("_" + want):
            die("index %d: the table says %s and the name is %s"
                % (index, item, name))
        rows.append((index, items[item], int(qty), int(rng), item))
    missing = sorted(set(by_index) - seen)
    if missing:
        die("named hidden items with no table row: %s"
            % ", ".join(by_index[i] for i in missing))
    rows.sort()

    lines = [
        "# HIDDEN_ITEMS, GENERATED by tools/gen_hidden_items.py; DO NOT EDIT.",
        "#",
        "# HeartGold's hidden items: the index a bg event's script names",
        "# (script id minus 8000) -> the item and count that game's compiled",
        "# table hands its pickup routine. tools/portmap.py writes a ported",
        "# hidden item a stub of its own from this row, because the table is",
        "# in the game and not on the cartridge.",
        "#",
        "# Two oracles agree on every row: the C table",
        "# (src/data/fieldmap/hidden_items.h) and the script's own name in",
        "# constants/std_script.h, which ends in the item. The range column",
        "# is the dowsing search radius and nothing here reads it.",
        "#",
        "# The flag is not a column: it is 800 + index in that game",
        "# (HiddenItemScriptNoToFlagId), and the porter's band keeps the",
        "# same arithmetic.",
        "#",
        "# %d hidden items." % len(rows),
        "#",
        "# Rows: <index> <item id> <count> <range> <item>",
        "",
    ]
    for index, item, qty, rng, item_name in rows:
        lines.append("%4d  %4d  %2d  %d  %s" % (index, item, qty, rng, item_name))
    lines.append("")
    out.write_text("\n".join(lines))
    print("gen_hidden_items: %d hidden items -> %s" % (len(rows), out))
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
