#!/usr/bin/env python3
"""Generate the trainer-front member table both sides of an import need."""

from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

MMO = Path(__file__).resolve().parent.parent

ENGINE_NAIX = (
    "build/rom/res/trainers/classes/trfgra.naix",
    "build/pc/geninclude/res/trainers/classes/trfgra.naix",
)

# The five a class occupies, in the order both games write them.
SUFFIXES = ("_NCGR", "_NCLR", "_cell_NCER", "_anim_NANR", "_scan_NCGR")
STRIDE = len(SUFFIXES)


def die(msg: str) -> None:
    print("gen_trainer_gfx: " + msg, file=sys.stderr)
    raise SystemExit(2)


def decomp_dir(name: str) -> Path | None:
    try:
        out = subprocess.run([str(MMO / "tools" / "decomp_dir.sh"), name],
                             capture_output=True, text=True, check=True)
    except (OSError, subprocess.CalledProcessError):
        return None
    return Path(out.stdout.strip())


def platinum_rows(engine: Path) -> list[tuple[str, int]]:
    naix = None
    for rel in ENGINE_NAIX:
        if (engine / rel).is_file():
            naix = engine / rel
            break
    if naix is None:
        die("no trfgra.naix under %s (it is generated by an engine build; "
            "this table is committed so a fill never needs one)" % engine)

    at: dict[int, str] = {}
    for m in re.finditer(r"#define\s+(\w+)\s+(\d+)", naix.read_text()):
        at[int(m.group(2))] = m.group(1)
    if not at:
        die("%s defines nothing" % naix)

    rows: list[tuple[str, int]] = []
    for base in range(0, max(at) + 1, STRIDE):
        names = [at.get(base + i) for i in range(STRIDE)]
        if any(n is None for n in names):
            # The tail of the file is the archive's own COUNT define, not a
            # class. Anything else missing is a layout this cannot read.
            if names[0] is not None and names[0].endswith("_COUNT"):
                break
            die("%s: member %d begins a group that is not five" % (naix, base))
        roots = {n[:-len(s)] for n, s in zip(names, SUFFIXES) if n.endswith(s)}
        if len(roots) != 1:
            die("%s: members %d..%d are not one class (%s)"
                % (naix, base, base + STRIDE - 1, ", ".join(names)))
        root = roots.pop()
        rows.append((root[:-len("_front")] if root.endswith("_front") else root,
                     base))
    return rows


def heartgold_rows(hg: Path) -> list[tuple[str, int]]:
    header = hg / "include" / "constants" / "trainer_class.h"
    if not header.is_file():
        die("no %s, HeartGold's class ids are what its own `class * 5` "
            "indexing takes" % header)
    rows: list[tuple[str, int]] = []
    for m in re.finditer(r"#define\s+TRAINERCLASS_(\w+)\s+(\d+)",
                         header.read_text()):
        rows.append((m.group(1).lower(), int(m.group(2)) * STRIDE))
    if not rows:
        die("%s names no trainer class" % header)
    return rows


def emit(pl: list, hg: list) -> str:
    out = [
        "# TRAINER_GFX, GENERATED by tools/gen_trainer_gfx.py; DO NOT EDIT.",
        "#",
        "# Where a trainer class's picture starts, on each side of an import.",
        "# A class is FIVE consecutive members, character sheet, palette,",
        "# cell bank, animation bank, scan sheet, and both games index them",
        "# at `class * 5`, so one number per row is the whole answer.",
        "#",
        "# The two columns of names are DIFFERENT SPACES and are tagged so.",
        "# `pl` names come from the engine's own trfgra.naix, with the _front",
        "# and the five suffixes stripped. `hg` names are HeartGold's own",
        "# TRAINERCLASS_ constants. Platinum has %d classes and HeartGold %d;"
        % (len(pl), len(hg)),
        "# they agree only where both inherited one from Diamond.",
        "#",
        "# Every TRAINERCLASS_ constant is listed, including the phone-contact",
        "# ids that share the namespace and index past the archive (its 645",
        "# members are 129 classes, measured 2026-08-21). A line naming one is",
        "# refused at fill time by the porter's own bound, naming both numbers;",
        "# dropping the rows here would refuse it as a name that does not exist,",
        "# which is a different and false thing to say.",
        "#",
        "# Rows: <side> <class> <first member>  (that member plus four)",
        "#",
        "# Read from, in whichever checkout of each the machine has:",
        "#   pl  build/.../res/trainers/classes/trfgra.naix",
        "#   hg  include/constants/trainer_class.h",
        "",
    ]
    for name, base in pl:
        out.append("pl  %-28s %4d" % (name, base))
    out.append("")
    for name, base in hg:
        out.append("hg  %-28s %4d" % (name, base))
    out.append("")
    return "\n".join(out)


def main(argv: list[str]) -> int:
    engine = Path(argv[1]) if len(argv) > 1 else None
    hgdir = Path(argv[2]) if len(argv) > 2 else None
    out = Path(argv[3]) if len(argv) > 3 else MMO / "TRAINER_GFX"

    if engine is None:
        env = subprocess.run(["sh", "-c", 'echo "${ENGINE_DIR:-}"'],
                             capture_output=True, text=True).stdout.strip()
        engine = Path(env) if env else decomp_dir("pokeplatinum")
    if hgdir is None:
        hgdir = decomp_dir("pokeheartgold")
    if engine is None or hgdir is None:
        die("need an engine checkout and a HeartGold one; pass them, or set "
            "ENGINE_DIR / DECOMP_DIR")

    pl = platinum_rows(engine)
    hg = heartgold_rows(hgdir)
    out.write_text(emit(pl, hg))
    print("gen_trainer_gfx: %d platinum, %d heartgold -> %s"
          % (len(pl), len(hg), out))
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
