#!/usr/bin/env python3
"""Generate the table that turns a HeartGold object-event sprite id into art."""

from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

MMO = Path(__file__).resolve().parent.parent


def die(msg: str) -> None:
    print("gen_sprites: " + msg, file=sys.stderr)
    raise SystemExit(2)


def decomp_dir(name: str) -> Path | None:
    try:
        out = subprocess.run([str(MMO / "tools" / "decomp_dir.sh"), name],
                             capture_output=True, text=True, check=True)
    except (OSError, subprocess.CalledProcessError):
        return None
    return Path(out.stdout.strip())


STATIC_PREFIX = "FOLLOWER_MON_STATIC_"
# The parameter word's top bits in the sprite table: 19 and 20 are what every
# follower row carries (591 and 37 rows), 63 the placeholder rows.
FOLLOWER_KINDS = {19, 20}


def sprite_table(path: Path) -> dict[str, tuple[str, int, int]]:
    """HeartGold's own sprite table: name -> (mmodel name, flags, kind)."""
    if not path.is_file():
        return {}
    out: dict[str, tuple[str, int, int]] = {}
    for m in re.finditer(r"\.short\s+SPRITE_(\w+),\s*MMODEL_(\w+),\s*"
                         r"(0x[0-9A-Fa-f]+|\d+)\s*\|\s*\((\d+)\s*<<\s*10\)",
                         path.read_text()):
        out.setdefault(m.group(1), (m.group(2), int(m.group(3), 0),
                                    int(m.group(4))))
    return out


def defines(path: Path, prefix: str) -> dict[str, int]:
    out: dict[str, int] = {}
    for m in re.finditer(r"#define\s+%s(\w+)\s+(\d+)" % prefix,
                         path.read_text()):
        out.setdefault(m.group(1), int(m.group(2)))
    return out


def main(argv: list[str]) -> int:
    hg = Path(argv[1]) if len(argv) > 1 else decomp_dir("pokeheartgold")
    out = Path(argv[2]) if len(argv) > 2 else MMO / "SPRITES"
    if hg is None:
        die("need a heartgold checkout; pass one or set DECOMP_DIR")

    sprites = defines(hg / "include/constants/sprites.h", "SPRITE_")
    models = defines(hg / "include/constants/mmodel.h", "MMODEL_")
    if not sprites or not models:
        die("no SPRITE_/MMODEL_ constants in %s/include/constants" % hg)
    table = sprite_table(hg / "asm/overlay_01_sprite_data.s")
    if not table:
        die("no sprite rows in %s/asm/overlay_01_sprite_data.s" % hg)

    rows = []
    static = 0
    for name, sid in sorted(sprites.items(), key=lambda kv: kv[1]):
        mid = models.get(name)
        row = table.get(name)
        if mid is not None and row is not None and models.get(row[0]) != mid:
            die("sprite %s: its name pairs with member %d and the sprite table "
                "sends it to MMODEL_%s" % (name, mid, row[0]))
        if mid is None and row is not None and name.startswith(STATIC_PREFIX):
            if row[2] not in FOLLOWER_KINDS:
                die("sprite %s is a static follower and the sprite table gives "
                    "it kind %d, not a follower kind" % (name, row[2]))
            mid = models.get(row[0])
            if mid is None:
                die("sprite %s: the sprite table names MMODEL_%s and no such "
                    "member is defined" % (name, row[0]))
            static += 1
        rows.append((sid, mid, name))
    named = sum(1 for _, mid, _ in rows if mid is not None)

    lines = [
        "# SPRITES, GENERATED by tools/gen_sprites.py; DO NOT EDIT.",
        "#",
        "# HeartGold's object-event sprite id -> the mmodel.narc member that",
        "# draws it, by the name both of that game's own headers give it.",
        "#",
        "# The member is where the ART is. tools/portmap.py appends it to this",
        "# game's own data/mmodel/mmodel.narc and gives it an appended",
        "# OBJ_EVENT_GFX id, because the two games number their people",
        "# differently and a carried number draws the wrong person.",
        "#",
        "# A row is only half an answer, so the porter checks the other half:",
        "# an mmodel member's TEX0 names its palette after the sprite, and a",
        "# member whose palette disagrees with the name here is refused rather",
        "# than carried. Both ends have to say the same thing.",
        "#",
        "# A FOLLOWER_MON_STATIC_* sprite, a Pokemon standing on a map --",
        "# has no member of its own name; its member is the species' follower",
        "# sheet, read off HeartGold's own sprite table",
        "# (asm/overlay_01_sprite_data.s), which agrees with the name pairing",
        "# on every sprite both answer. The porter accepts the follower",
        "# palette for these and draws them on the follower walk.",
        "#",
        "# `-` in the member column is a sprite id with no art: the",
        "# BABYBOY1_2-style variants and the gate shutters, which that table",
        "# sends to BABYBOY1 as a placeholder. A port that meets one refuses.",
        "#",
        "# %d sprite ids, %d with a member (%d static followers)."
        % (len(rows), named, static),
        "#",
        "# Rows: <sprite id> <mmodel member> <name>",
        "",
    ]
    for sid, mid, name in rows:
        lines.append("%4d  %5s  %s" % (sid, mid if mid is not None else "-", name))
    lines.append("")
    out.write_text("\n".join(lines))
    print("gen_sprites: %d sprite ids, %d with an mmodel member -> %s"
          % (len(rows), named, out))
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
