#!/usr/bin/env python3
"""Generate the table that turns a HeartGold object-event sprite id into art."""

from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

MMO = Path(__file__).resolve().parent.parent


def die(msg: str) -> None:
    print("gen_sprites: " + msg, file=sys.stderr)
    raise SystemExit(2)


def decomp_dir(name: str) -> Path | None:
    try:
        out = subprocess.run([str(MMO / "tools" / "decomp_dir.sh"), name],
                             capture_output=True, text=True, check=True)
    except (OSError, subprocess.CalledProcessError):
        return None
    return Path(out.stdout.strip())


def defines(path: Path, prefix: str) -> dict[str, int]:
    out: dict[str, int] = {}
    for m in re.finditer(r"#define\s+%s(\w+)\s+(\d+)" % prefix,
                         path.read_text()):
        out.setdefault(m.group(1), int(m.group(2)))
    return out


def main(argv: list[str]) -> int:
    hg = Path(argv[1]) if len(argv) > 1 else decomp_dir("pokeheartgold")
    out = Path(argv[2]) if len(argv) > 2 else MMO / "SPRITES"
    if hg is None:
        die("need a heartgold checkout; pass one or set DECOMP_DIR")

    sprites = defines(hg / "include/constants/sprites.h", "SPRITE_")
    models = defines(hg / "include/constants/mmodel.h", "MMODEL_")
    if not sprites or not models:
        die("no SPRITE_/MMODEL_ constants in %s/include/constants" % hg)

    rows = []
    for name, sid in sorted(sprites.items(), key=lambda kv: kv[1]):
        mid = models.get(name)
        rows.append((sid, mid, name))
    named = sum(1 for _, mid, _ in rows if mid is not None)

    lines = [
        "# SPRITES, GENERATED by tools/gen_sprites.py; DO NOT EDIT.",
        "#",
        "# HeartGold's object-event sprite id -> the mmodel.narc member that",
        "# draws it, by the name both of that game's own headers give it.",
        "#",
        "# The member is where the ART is. tools/portmap.py appends it to this",
        "# game's own data/mmodel/mmodel.narc and gives it an appended",
        "# OBJ_EVENT_GFX id, because the two games number their people",
        "# differently and a carried number draws the wrong person.",
        "#",
        "# A row is only half an answer, so the porter checks the other half:",
        "# an mmodel member's TEX0 names its palette after the sprite, and a",
        "# member whose palette disagrees with the name here is refused rather",
        "# than carried. Both ends have to say the same thing.",
        "#",
        "# `-` in the member column is a sprite id with no member of its own",
        "# name: the BABYBOY1_2-style variants and the FOLLOWER_MON_STATIC_*",
        "# set. Nothing places one on a map, and a port that meets one refuses.",
        "#",
        "# %d sprite ids, %d with a member." % (len(rows), named),
        "#",
        "# Rows: <sprite id> <mmodel member> <name>",
        "",
    ]
    for sid, mid, name in rows:
        lines.append("%4d  %5s  %s" % (sid, mid if mid is not None else "-", name))
    lines.append("")
    out.write_text("\n".join(lines))
    print("gen_sprites: %d sprite ids, %d with an mmodel member -> %s"
          % (len(rows), named, out))
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
