#!/usr/bin/env python3
"""Generate the table of HeartGold maps a recipe may ask for."""

from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

MMO = Path(__file__).resolve().parent.parent

# The overworld matrix, by the name HeartGold's own header table gives it.
OVERWORLD = "map_matrix_0000"


def die(msg: str) -> None:
    print("gen_maps: " + msg, file=sys.stderr)
    raise SystemExit(2)


def decomp_dir(name: str) -> Path | None:
    try:
        out = subprocess.run([str(MMO / "tools" / "decomp_dir.sh"), name],
                             capture_output=True, text=True, check=True)
    except (OSError, subprocess.CalledProcessError):
        return None
    return Path(out.stdout.strip())


def main(argv: list[str]) -> int:
    hg = Path(argv[1]) if len(argv) > 1 else decomp_dir("pokeheartgold")
    out = Path(argv[2]) if len(argv) > 2 else MMO / "MAPS"
    if hg is None:
        die("need a heartgold checkout; pass one or set DECOMP_DIR")

    ids: dict[str, int] = {}
    for m in re.finditer(r"#define\s+MAP_(\w+)\s+(\d+)",
                         (hg / "include/constants/maps.h").read_text()):
        ids.setdefault(m.group(1), int(m.group(2)))

    text = (hg / "src/data/map_headers.h").read_text()
    rows = []
    for m in re.finditer(r"\[MAP_(\w+)\]\s*=\s*\{(.*?)\n\s*\}", text, re.S):
        name, body = m.group(1), m.group(2)
        bank = re.search(r"\.areaDataBank\s*=\s*(\d+)", body)
        matrix = re.search(r"\.matrixId\s*=\s*NARC_map_matrix_map_matrix_(\d+)_", body)
        kind = re.search(r"\.mapType\s*=\s*MAP_TYPE_(\w+)", body)
        bgm = re.search(r"\.dayMusicId\s*=\s*(\w+)", body)
        events = re.search(r"\.eventsBank\s*=\s*NARC_zone_event_(\d+)_", body)
        if not bank or not matrix or not events or name not in ids:
            continue
        mid = int(matrix.group(1))
        # The overworld is matrix 0 and is the one a port cuts; every other
        # matrix belongs to one map and is carried whole.
        rows.append((name.lower(), ids[name], int(bank.group(1)), mid,
                     int(events.group(1)),
                     (kind.group(1).lower() if kind else "unknown"),
                     bgm.group(1) if bgm else "-"))
    if not rows:
        die("no map rows found in %s/src/data/map_headers.h" % hg)
    rows.sort(key=lambda r: r[1])

    lines = [
        "# MAPS, GENERATED by tools/gen_maps.py; DO NOT EDIT.",
        "#",
        "# The HeartGold maps a `map` recipe line may name.",
        "#",
        "# MATRIX 0 is the shared 47x17 overworld: such a map is the set of",
        "# cells that name its header, and tools/portmap.py cuts the bounding",
        "# rectangle of them into a matrix of its own, so no import ever",
        "# approaches the engine's matrix bound. Any other matrix belongs to",
        "# one map, an interior, usually 1x1, and is carried whole.",
        "#",
        "# No destination member is named here: a package must append",
        "# CONTIGUOUSLY with the built image (pc_modfs refuses an append",
        "# hole), so a package starts at the vanilla count and portmap.py",
        "# allocates from there for every map it is asked for at once.",
        "#",
        "# BGM is the source cartridge's own sequence NAME, which is what",
        "# tools/portmusic.py takes; the number it lands on is the porter's.",
        "#",
        "# Rows: hg <name> <header id> <area bank> <matrix> <events> <kind> <bgm>",
        "",
    ]
    over = sum(1 for r in rows if r[3] == 0)
    for name, hid, bank, mid, ev, kind, bgm in rows:
        lines.append("hg  %-38s %4d %4d %4d %4d  %-14s %s"
                     % (name, hid, bank, mid, ev, kind, bgm))
    lines.append("")
    out.write_text("\n".join(lines))
    print("gen_maps: %d maps (%d on the overworld matrix) -> %s"
          % (len(rows), over, out))
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
