#!/usr/bin/env python3
"""Generate the item-icon member table both sides of an import need."""

from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path

MMO = Path(__file__).resolve().parent.parent

# The engine writes its naix into whichever tree it built. Both are the same
# file; take the first that exists rather than insisting on a ROM build.
ENGINE_NAIX = (
    "build/rom/res/items/item_icon.naix",
    "build/pc/geninclude/res/items/item_icon.naix",
)


def die(msg: str) -> None:
    print("gen_item_icons: " + msg, file=sys.stderr)
    raise SystemExit(2)


def decomp_dir(name: str) -> Path | None:
    try:
        out = subprocess.run([str(MMO / "tools" / "decomp_dir.sh"), name],
                             capture_output=True, text=True, check=True)
    except (OSError, subprocess.CalledProcessError):
        return None
    return Path(out.stdout.strip())


def find(base: Path, rels) -> Path | None:
    for rel in rels:
        if (base / rel).is_file():
            return base / rel
    return None


def platinum_rows(engine: Path) -> list[tuple[str, int, int]]:
    """Item -> its two members, through the table the game itself indexes."""
    naix = find(engine, ENGINE_NAIX)
    idmap = find(engine, [r.replace("item_icon.naix", "item_id_map.h")
                          for r in ENGINE_NAIX])
    if naix is None or idmap is None:
        die("no item_icon.naix / item_id_map.h under %s (both are generated "
            "by an engine build; this table is committed so a fill never "
            "needs one)" % engine)
    define: dict[str, int] = {}
    for m in re.finditer(r"#define\s+(\w+)\s+(\d+)", naix.read_text()):
        define[m.group(1)] = int(m.group(2))
    rows: list[tuple[str, int, int]] = []
    pat = re.compile(r"\[(\d+)\]\s*=\s*\{[^}]*?"
                     r"\.iconID\s*=\s*(\w+)\s*,[^}]*?"
                     r"\.paletteID\s*=\s*(\w+)\s*,", re.S)
    for m in pat.finditer(idmap.read_text()):
        icon, pal = m.group(2), m.group(3)
        if icon not in define or pal not in define:
            die("%s names %s / %s, which %s does not define"
                % (idmap, icon, pal, naix))
        name = icon[:-len("_NCGR")] if icon.endswith("_NCGR") else icon
        rows.append((name, define[icon], define[pal]))
    if not rows:
        die("%s holds no item rows this can read" % idmap)
    return rows


def heartgold_rows(hg: Path) -> list[tuple[str, int, int]]:
    src = hg / "src" / "item.c"
    if not src.is_file():
        die("no %s, the HeartGold item table is where its icon members are "
            "named" % src)
    rows: list[tuple[str, int, int]] = []
    pat = re.compile(
        r"\[ITEM_(\w+)\]\s*=\s*\{[^}]*?"
        r"NARC_item_icon_item_icon_(\d+)_NCGR\s*,\s*"
        r"NARC_item_icon_item_icon_(\d+)_NCLR", re.S)
    for m in pat.finditer(src.read_text()):
        rows.append((m.group(1).lower(), int(m.group(2)), int(m.group(3))))
    if not rows:
        die("%s holds no sItemNarcIds rows this can read" % src)
    return rows


def with_palette_users(rows):
    """Each row plus how many items draw from its palette member."""
    users: dict[int, int] = {}
    for _, _, nclr in rows:
        users[nclr] = users.get(nclr, 0) + 1
    return [(n, ncgr, nclr, users[nclr]) for n, ncgr, nclr in rows]


def emit(pl: list, hg: list) -> str:
    out = [
        "# ITEM_ICONS, GENERATED by tools/gen_item_icons.py; DO NOT EDIT.",
        "#",
        "# Which two members of an item-icon archive hold one item's picture,",
        "# on each side of an import. A `item_icon` recipe line names a source",
        "# item and a destination item; this is what turns those two names into",
        "# four member numbers.",
        "#",
        "# The two columns of names are DIFFERENT SPACES and are tagged so.",
        "# `pl` names come from the engine's own item_icon.naix, where the",
        "# define IS the name. `hg` names come from the item constants in",
        "# HeartGold's sItemNarcIds, whose members are numbered only. An item",
        "# on one side and not the other is the normal case and the reason a",
        "# cartridge is worth importing from.",
        "#",
        "# Rows: <side> <item> <ncgr member> <nclr member> <items sharing",
        "# that palette>. A destination whose palette is shared is a line that",
        "# repaints every other item using it, which is why the count is here",
        "# and not something a fill discovers.",
        "#",
        "# Read from, in whichever checkout of each the machine has (the paths",
        "# themselves are not recorded: a table that changed every time an",
        "# engine tree moved would fail its own regeneration check for a",
        "# reason that is not the data):",
        "#   pl  build/.../res/items/item_id_map.h + item_icon.naix",
        "#   hg  src/item.c (sItemNarcIds)",
        "",
    ]
    for name, ncgr, nclr, users in with_palette_users(pl):
        out.append("pl  %-26s %4d %4d %2d" % (name, ncgr, nclr, users))
    out.append("")
    for name, ncgr, nclr, users in with_palette_users(hg):
        out.append("hg  %-26s %4d %4d %2d" % (name, ncgr, nclr, users))
    out.append("")
    return "\n".join(out)


def main(argv: list[str]) -> int:
    engine = Path(argv[1]) if len(argv) > 1 else None
    hgdir = Path(argv[2]) if len(argv) > 2 else None
    out = Path(argv[3]) if len(argv) > 3 else MMO / "ITEM_ICONS"

    if engine is None:
        env = subprocess.run(["sh", "-c", 'echo "${ENGINE_DIR:-}"'],
                             capture_output=True, text=True).stdout.strip()
        engine = Path(env) if env else decomp_dir("pokeplatinum")
    if hgdir is None:
        hgdir = decomp_dir("pokeheartgold")
    if engine is None or hgdir is None:
        die("need an engine checkout and a HeartGold one; pass them, or set "
            "ENGINE_DIR / DECOMP_DIR")

    pl = platinum_rows(engine)
    hg = heartgold_rows(hgdir)
    out.write_text(emit(pl, hg))
    print("gen_item_icons: %d platinum, %d heartgold -> %s"
          % (len(pl), len(hg), out))
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
