#!/usr/bin/env python3
"""Generate the client's type display table from the engine's own data."""
import json
import os
import re
import sys

REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
ENGINE = os.environ.get(
    "ENGINE_DIR", os.path.join(REPO, "engine", "pokeplatinum")
)

TYPES_TXT = "generated/pokemon_types.txt"
NAMES_JSON = "res/text/pokemon_type_names.json"
BATTLE_H = "include/constants/battle.h"
BATTLE_C = "src/battle/battle_lib.c"

NEUTRAL = 10  # the multiplier the sparse table omits, in the same tenths


def die(msg):
    sys.stderr.write("gen_display_types: %s\n" % msg)
    sys.exit(1)


def read_type_ids(path):
    """generated/pokemon_types.txt, one TYPE_* constant per line in id order."""
    ids = {}
    order = []
    with open(path) as fh:
        for line in fh:
            name = line.strip()
            if not name or name.startswith("#"):
                continue
            if name == "NUM_POKEMON_TYPES":
                break
            if not name.startswith("TYPE_"):
                die("%s: unexpected constant %r" % (path, name))
            ids[name] = len(order)
            order.append(name)
    if not order:
        die("%s: no types" % path)
    return ids, order


def read_display_names(path, order):
    """res/text/pokemon_type_names.json, the engine's own on-screen spelling."""
    with open(path) as fh:
        messages = json.load(fh)["messages"]
    names = [m["en_US"] for m in messages]
    if len(names) != len(order):
        die(
            "%s holds %d names for %d types, the bank is not the type table"
            % (path, len(names), len(order))
        )
    for i, (name, const) in enumerate(zip(names, order)):
        if const == "TYPE_MYSTERY":
            if name != "???":
                die("type %d: TYPE_MYSTERY is spelled %r, not '???'" % (i, name))
            continue
        if name.replace(" ", "_") != const[len("TYPE_") :]:
            die("type %d: %s is spelled %r" % (i, const, name))
    return names


def read_multipliers(path):
    """The three TYPE_MULTI_* values the matchup table's third column uses."""
    wanted = ("TYPE_MULTI_IMMUNE", "TYPE_MULTI_NOT_VERY_EFF", "TYPE_MULTI_SUPER_EFF")
    out = {}
    with open(path) as fh:
        for line in fh:
            m = re.match(r"\s*#define\s+(TYPE_MULTI_\w+)\s+(\d+)", line)
            if m and m.group(1) in wanted:
                out[m.group(1)] = int(m.group(2))
    missing = [w for w in wanted if w not in out]
    if missing:
        die("%s: no value for %s" % (path, ", ".join(missing)))
    return out


def read_chart(path, ids, multi):
    """sTypeMatchupMultipliers, flattened.

    Returns (dense, foresight): dense[att][def] in tenths, and the (att, def)
    pairs listed after the 0xFE row, which Foresight clears."""
    src = open(path).read()
    start = src.index("static const u8 sTypeMatchupMultipliers[][3] = {")
    end = src.index("\n};", start)
    body = src[start:end]

    n = len(ids)
    dense = [[NEUTRAL] * n for _ in range(n)]
    foresight = []
    after_split = False
    seen = set()

    for att, dfn, mul in re.findall(r"\{\s*(\w+),\s*(\w+),\s*(\w+)\s*\}", body):
        if att == "0xFF":
            break
        if att == "0xFE":
            if after_split:
                die("%s: two 0xFE rows" % path)
            after_split = True
            continue
        if att not in ids or dfn not in ids:
            die("%s: unknown type in row {%s, %s}" % (path, att, dfn))
        if mul not in multi:
            die("%s: unknown multiplier %s" % (path, mul))
        pair = (ids[att], ids[dfn])
        if pair in seen:
            die("%s: %s vs %s listed twice" % (path, att, dfn))
        seen.add(pair)
        dense[pair[0]][pair[1]] = multi[mul]
        if after_split:
            foresight.append(pair)

    if not after_split:
        die("%s: no 0xFE row, the Foresight split is how the table is read" % path)
    if not foresight:
        die("%s: the 0xFE row separates nothing" % path)
    return dense, foresight


def emit(names, dense, foresight, mystery, out):
    width = max(len(n) for n in names)
    w = out.write
    w(
        """/* display_types.gen.h, GENERATED by tools/gen_display_types.py; DO NOT EDIT.
 *
 * The pokeplatinum engine's type table, flattened for a screen to read.
 * %d slots: %d types plus TYPE_MYSTERY at %d, the ??? placeholder, numbered by
 * the engine's generated/pokemon_types.txt and spelled by its own
 * res/text/pokemon_type_names.json.
 *
 * MMO_TYPE_MATCHUP[attacker][defender] is the multiplier in tenths, so %d is
 * neutral, 5 is resisted, 20 is super effective and 0 is immune. The engine
 * stores the same numbers, its TYPE_MULTI_* constants are tenths against a
 * base of 10, in a sparse list that omits every neutral pair; this is that
 * list flattened, with nothing else applied. Abilities, items and Foresight are
 * the server's rules and none of them are in here.
 *
 * MMO_TYPE_FORESIGHT_IMMUNITY is the pairs the engine lists after its 0xFE row:
 * the immunities Foresight removes. They are in the grid above as well. */

#define MMO_TYPE_COUNT   %d
#define MMO_TYPE_MYSTERY %d  /* the ??? slot: neutral both ways, drawn by nothing */
#define MMO_TYPE_NEUTRAL %d  /* the multiplier the engine's sparse table omits */

static const char *const MMO_TYPE_NAME[MMO_TYPE_COUNT] = {
"""
        % (
            len(names),
            len(names) - 1,
            mystery,
            NEUTRAL,
            len(names),
            mystery,
            NEUTRAL,
        )
    )
    for i, name in enumerate(names):
        w('    "%s",%s /* %d */\n' % (name, " " * (width - len(name)), i))
    w("};\n\nstatic const u8 MMO_TYPE_MATCHUP[MMO_TYPE_COUNT][MMO_TYPE_COUNT] = {\n")
    for i, row in enumerate(dense):
        cells = ", ".join("%2d" % v for v in row)
        w("    { %s }, /* %s */\n" % (cells, names[i]))
    w("};\n\n#define MMO_TYPE_FORESIGHT_IMMUNITY_COUNT %d\n" % len(foresight))
    w("static const u8 MMO_TYPE_FORESIGHT_IMMUNITY[MMO_TYPE_FORESIGHT_IMMUNITY_COUNT][2] = {\n")
    for att, dfn in foresight:
        w("    { %2d, %2d }, /* %s vs %s */\n" % (att, dfn, names[att], names[dfn]))
    w("};\n")


def main(argv):
    engine = argv[1] if len(argv) > 1 else ENGINE
    out_path = argv[2] if len(argv) > 2 else os.path.join(
        REPO, "mmo", "src", "display_types.gen.h"
    )

    ids, order = read_type_ids(os.path.join(engine, TYPES_TXT))
    names = read_display_names(os.path.join(engine, NAMES_JSON), order)
    multi = read_multipliers(os.path.join(engine, BATTLE_H))
    dense, foresight = read_chart(os.path.join(engine, BATTLE_C), ids, multi)
    if "TYPE_MYSTERY" not in ids:
        die("%s has no TYPE_MYSTERY" % TYPES_TXT)

    with open(out_path, "w") as fh:
        emit(names, dense, foresight, ids["TYPE_MYSTERY"], fh)
    sys.stderr.write(
        "gen_display_types: %d types, %d non-neutral cells, %d Foresight -> %s\n"
        % (
            len(names),
            sum(1 for row in dense for v in row if v != NEUTRAL),
            len(foresight),
            out_path,
        )
    )
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
