#!/usr/bin/env python3
"""SOUNDTRACKS + SOUNDFONTS -> src/soundtables.gen.h."""
import sys
from pathlib import Path


def fnv64(data: bytes) -> int:
    h = 0xCBF29CE484222325
    for b in data:
        h = ((h ^ b) * 0x100000001B3) & 0xFFFFFFFFFFFFFFFF
    return h


def parse_tracks(path):
    rows = []
    for raw in path.read_text().splitlines():
        line = raw.split("#", 1)[0].strip()
        if not line:
            continue
        parts = line.split()
        cells = dict(c.split("=", 1) for c in parts[1:])
        rows.append((parts[0], cells.get("heartgold", ""),
                     cells.get("blackwhite", "")))
    return rows


def parse_fonts(path):
    rows = []
    for raw in path.read_text().splitlines():
        line = raw.split("#", 1)[0].strip()
        if not line:
            continue
        parts = line.split()
        cells = dict(c.split("=", 1) for c in parts[1:])
        def cell(v):
            pct = 100
            if "/" in v:
                v, spct = v.split("/", 1)
                pct = int(spct)
            if v == "keep":
                return -1, -1, 100
            if "@" in v:
                q, bank = v.split("@", 1)
                return int(q), int(bank), pct
            return int(v), -1, pct
        hgq, hgb, hgp = cell(cells.get("heartgold", "keep"))
        bwq, bwb, bwp = cell(cells.get("blackwhite", "keep"))
        rows.append((int(parts[0]), hgq, hgb, hgp, bwq, bwb, bwp))
    return rows


def main(argv):
    root = Path(argv[1]) if len(argv) > 1 else Path(__file__).resolve().parents[1]
    out = Path(argv[2]) if len(argv) > 2 else root / "src" / "soundtables.gen.h"
    tr = root / "SOUNDTRACKS"
    fo = root / "SOUNDFONTS"
    tracks = parse_tracks(tr)
    fonts = parse_fonts(fo)
    h = fnv64(tr.read_bytes() + fo.read_bytes())

    L = []
    L.append("/* soundtables.gen.h, GENERATED by tools/gen_soundtables.py; DO NOT EDIT.")
    L.append(" *")
    L.append(" * mmo/SOUNDTRACKS and mmo/SOUNDFONTS compiled in, so the launcher can")
    L.append(" * compose a player's sound packages from their own cartridges without")
    L.append(" * carrying the tables as files. The hash names the rows a cached package")
    L.append(" * was composed under; a package stamped differently recomposes. */")
    L.append("#ifndef MMO_SOUNDTABLES_GEN_H")
    L.append("#define MMO_SOUNDTABLES_GEN_H")
    L.append("")
    L.append("#define MMO_SOUNDTABLES_HASH 0x%016XULL" % h)
    L.append("")
    L.append("/* One row per replaced Platinum track: its SEQ name and the donor")
    L.append(" * SEQ name per game; \"\" where a game has no cell. */")
    L.append("typedef struct { const char *pt, *hg, *bw; } mmo_soundtrack_row;")
    L.append("#define MMO_SOUNDTRACK_ROWS %d" % len(tracks))
    L.append("static const mmo_soundtrack_row MMO_SOUNDTRACKS[MMO_SOUNDTRACK_ROWS] = {")
    for (pt, hg, bw) in tracks:
        L.append('    { "%s", "%s", "%s" },' % (pt, hg, bw))
    L.append("};")
    L.append("")
    L.append("/* One row per mapped Platinum master program: each game's donor as")
    L.append(" * program@bank (-1 program = keep; -1 bank = the canonical variant),")
    L.append(" * and the percent its sustain levels are scaled by so it sits where")
    L.append(" * the instrument it replaces sat (100 = untouched). */")
    L.append("typedef struct { int pt, hg, hg_bank, hg_pct, bw, bw_bank, bw_pct; }")
    L.append("        mmo_soundfont_row;")
    L.append("#define MMO_SOUNDFONT_ROWS %d" % len(fonts))
    L.append("static const mmo_soundfont_row MMO_SOUNDFONTS[MMO_SOUNDFONT_ROWS] = {")
    for (p, hgq, hgb, hgp, bwq, bwb, bwp) in fonts:
        L.append("    { %d, %d, %d, %d, %d, %d, %d },"
                 % (p, hgq, hgb, hgp, bwq, bwb, bwp))
    L.append("};")
    L.append("")
    L.append("#endif")
    out.write_text("\n".join(L) + "\n")
    print("gen_soundtables: %d track rows, %d font rows -> %s" %
          (len(tracks), len(fonts), out))
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
