#!/usr/bin/env python3
"""Render mmo/CARTRIDGES into the table the client compiles."""

from __future__ import annotations

import re
import sys
from pathlib import Path

STATUSES = {
    "host": "MMO_CART_HOST",
    "read": "MMO_CART_READ",
    "extracts": "MMO_CART_EXTRACTS",
    "refuses": "MMO_CART_REFUSES",
    "unread": "MMO_CART_UNREAD",
}


def die(msg: str) -> None:
    print("gen_cartridges: " + msg, file=sys.stderr)
    raise SystemExit(2)


def parse(path: Path):
    carts: list[dict] = []
    langs: list[tuple[str, str, bool]] = []
    slots: dict[str, str] = {}
    scramble: dict[str, int] = {}
    for n, raw in enumerate(path.read_text().splitlines(), 1):
        line = raw.strip()
        if not line or line.startswith("#"):
            continue
        if line.split()[0] == "slot":
            m = re.match(r'^slot\s+(\S+)\s+"([^"]+)"\s*$', line)
            if not m:
                die('%s:%d: a slot row is `slot <id> "<display name>"`' % (path, n))
            slots[m.group(1)] = m.group(2)
            continue
        if line.split()[0] == "sprite":
            parts = line.split()
            if len(parts) != 3 or not parts[2].isdigit():
                die("%s:%d: a sprite row is `sprite <code> <mode>`" % (path, n))
            scramble[parts[1]] = int(parts[2])
            continue
        if line.split()[0] == "lang":
            parts = line.split()
            if len(parts) not in (3, 4):
                die("%s:%d: a lang row is `lang <char> <name> [read]`" % (path, n))
            langs.append((parts[1], parts[2], len(parts) == 4))
            continue
        # Four plain columns, then the title, quoted, because a header title
        # has a space in it, then the note, which is prose and may hold an
        # apostrophe, so it is never tokenized.
        m = re.match(r"^(\S+)\s+(\S+)\s+(\S+)\s+(\S+)\s+"
                     r"(?:\"([^\"]*)\"|(\S+))\s+(.*\S)\s*$", line)
        if not m:
            die("%s:%d: a cartridge row is code, slot, status, kinds, "
                "\"title\" and a note, cannot read %r" % (path, n, line))
        code, slot, status, kinds = m.group(1, 2, 3, 4)
        title = m.group(5) if m.group(5) is not None else m.group(6)
        note = m.group(7)
        if len(code) != 4 or not code.isalnum() or not code.isupper():
            die("%s:%d: '%s' is not a four-character game code" % (path, n, code))
        if status not in STATUSES:
            die("%s:%d: '%s' is not a status CARTRIDGES defines (%s)"
                % (path, n, status, ", ".join(sorted(STATUSES))))
        carts.append({
            "code": code,
            "slot": slot,
            "status": status,
            "kinds": [] if kinds == "-" else kinds.split(","),
            "title": "" if title == "-" else title,
            "note": note,
        })
    if not carts:
        die("%s names no cartridge" % path)
    if not langs:
        die("%s names no language" % path)
    for code in scramble:
        if code not in {c["code"] for c in carts}:
            die("%s: sprite row names %s, which is not a cartridge here"
                % (path, code))
    for c in carts:
        c["scramble"] = scramble.get(c["code"], 0)
        if c["slot"] not in slots:
            die("%s: %s is in slot '%s', which no slot row names"
                % (path, c["code"], c["slot"]))
        c["name"] = slots[c["slot"]]

    # A code is one row. Two rows for one code would make the lookup's answer
    # depend on which one it reached first, which is the class of bug this
    # table exists to remove.
    seen: dict[str, int] = {}
    for i, c in enumerate(carts):
        if c["code"] in seen:
            die("%s: %s is listed twice" % (path, c["code"]))
        seen[c["code"]] = i
    for c in carts:
        if c["code"][3] not in {ch for ch, _, _ in langs}:
            die("%s: %s ends in '%s', which no lang row names"
                % (path, c["code"], c["code"][3]))
    return carts, langs


def emit(carts, langs, registry: Path) -> str:
    out: list[str] = []
    w = out.append
    w("/* Generated by tools/gen_cartridges.py; Do not edit. */")
    w("")
    w("#define MMO_CARTRIDGE_COUNT %d" % len(carts))
    w("#define MMO_CARTRIDGE_LANG_COUNT %d" % len(langs))
    w("")
    w("static const MmoCartridge MMO_CARTRIDGES[MMO_CARTRIDGE_COUNT] = {")
    for c in carts:
        kinds = ",".join(c["kinds"]) if c["kinds"] else ""
        w('    { "%s", "%s", "%s", %s, "%s", "%s", "%s", %d }, /* %s */'
          % (c["code"], c["slot"], c["name"], STATUSES[c["status"]], kinds,
             c["title"], c["note"].replace('"', "'"), c["scramble"],
             c["status"]))
    w("};")
    w("")
    w("static const MmoCartridgeLang MMO_CARTRIDGE_LANGS[MMO_CARTRIDGE_LANG_COUNT] = {")
    for ch, name, read in langs:
        w('    { \'%s\', "%s", %d },' % (ch, name, 1 if read else 0))
    w("};")
    w("")
    return "\n".join(out) + "\n"


def main(argv: list[str]) -> int:
    root = Path(__file__).resolve().parent.parent
    registry = Path(argv[1]) if len(argv) > 1 else root / "CARTRIDGES"
    out = Path(argv[2]) if len(argv) > 2 else root / "src" / "cartridges.gen.h"
    if not registry.is_file():
        die("no registry at %s" % registry)
    carts, langs = parse(registry)
    out.write_text(emit(carts, langs, registry))
    print("gen_cartridges: %d cartridge(s), %d language(s) -> %s"
          % (len(carts), len(langs), out))
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
