#!/usr/bin/env python3
"""Generate the pinned keypair fixtures for the mock server double."""
import re
import subprocess
import sys
import tempfile
from pathlib import Path

HERE = Path(__file__).resolve().parent
OUT = HERE.parent / "src" / "mock_keys.gen.h"

# The one ClientHello timestamp the mock can answer, and the profiles it can
# offer. The timestamp matches the ClientHello vector session_test pins, so a
# seeded client speaks the same millisecond the fixture was signed for.
HELLO_TS = 1700000000000
# 2 is below the client's keyed minimum on purpose: it is how a test drives a
# correctly signed ServerHello that still has to be refused.
SIZES = (2, 4, 8, 16, 32)
MAX_SIG = 72  # MMO_HS_MAX_SIG: a DER ECDSA-P256 signature at its widest


def openssl(*args, **kw):
    return subprocess.run(["openssl", *args], check=True,
                          capture_output=True, **kw)


def gen_key(path):
    openssl("ecparam", "-name", "prime256v1", "-genkey", "-noout", "-out", str(path))


def hexblock(text, label):
    """Pull the colon-separated hex block that follows `label:` in -text output."""
    m = re.search(label + r":\s*\n((?:\s+[0-9a-f:]+\n)+)", text)
    if not m:
        raise SystemExit(f"could not find {label} in openssl -text output")
    return bytes(int(b, 16) for b in m.group(1).replace(":", " ").split())


def key_parts(path):
    text = openssl("ec", "-in", str(path), "-text", "-noout").stdout.decode()
    priv = hexblock(text, "priv")
    pub = hexblock(text, "pub")
    # priv is big-endian and may carry a leading 0x00 sign byte; normalise to 32.
    priv = priv.lstrip(b"\x00").rjust(32, b"\x00")
    if len(pub) != 65 or pub[0] != 0x04:
        raise SystemExit(f"unexpected public point ({len(pub)} bytes)")
    return priv, pub


def c_array(name, data):
    lines = [f"static const u8 {name}[{len(data)}] = {{"]
    for i in range(0, len(data), 12):
        chunk = ", ".join(f"0x{b:02x}" for b in data[i:i + 12])
        lines.append(f"    {chunk},")
    lines.append("};")
    return "\n".join(lines)


def main():
    with tempfile.TemporaryDirectory() as td:
        td = Path(td)
        root, eph = td / "root.pem", td / "eph.pem"
        gen_key(root)
        gen_key(eph)
        _, root_pub = key_parts(root)
        eph_priv, eph_pub = key_parts(eph)

        sigs = []
        for size in SIZES:
            signed = eph_pub + bytes([size]) + HELLO_TS.to_bytes(8, "big")
            (td / "msg.bin").write_bytes(signed)
            openssl("dgst", "-sha256", "-sign", str(root), "-out", str(td / "sig.der"),
                    str(td / "msg.bin"))
            sig = (td / "sig.der").read_bytes()
            if len(sig) > MAX_SIG:
                raise SystemExit(f"signature for size {size} is {len(sig)} bytes")
            sigs.append(sig)

    banner = "/* Generated by mmo/tools/gen_mock_keys.py, do not edit by hand.\n" \
             " * Pinned test keypairs for the mock server double (mmo/src/mockserver.c).\n" \
             " * These are throwaway TEST keys, never the real server's root. */\n"
    rows = []
    for size, sig in zip(SIZES, sigs):
        rows.append(f"    /* checksum size {size} */ {{")
        for i in range(0, len(sig), 12):
            rows.append("        " + ", ".join(f"0x{b:02x}" for b in sig[i:i + 12]) + ",")
        rows.append("    },")
    table = "\n".join(
        ["static const u8 MOCK_HELLO_SIGS[%d][%d] = {" % (len(SIZES), MAX_SIG)]
        + rows + ["};"])
    body = "\n\n".join([
        c_array("MOCK_ROOT_PUB", root_pub),
        c_array("MOCK_EPH_PRIV", eph_priv),
        c_array("MOCK_EPH_PUB", eph_pub),
        f"#define MOCK_HELLO_TS ((s64){HELLO_TS}LL)",
        c_array("MOCK_HELLO_SIZES", SIZES),
        "static const u8 MOCK_HELLO_SIGLEN[%d] = { %s };"
        % (len(SIZES), ", ".join(str(len(s)) for s in sigs)),
        table,
    ])
    OUT.write_text(f"{banner}\n{body}\n")
    print(f"wrote {OUT} ({len(SIZES)} signatures)", file=sys.stderr)


if __name__ == "__main__":
    main()
