#!/usr/bin/env python3
"""Generate the table of text banks the engine can resolve a server text id in."""
import json
import os
import sys

REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
ENGINE = os.environ.get(
    "ENGINE_DIR", os.path.join(REPO, "engine", "pokeplatinum")
)

PREFIX = "TEXT_BANK_"


def arg(n, default):
    return sys.argv[n] if len(sys.argv) > n else default


BANKS_TXT = arg(1, os.path.join(ENGINE, "generated/text_banks.txt"))
TEXT_DIR = arg(2, os.path.join(ENGINE, "res/text"))
OUT = arg(3, os.path.join(REPO, "mmo/src/idmap_text.gen.h"))


def bank_order(banks_txt):
    """Bank name in archive order. The line number is the bank index."""
    names = []
    with open(banks_txt) as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            if not line.startswith(PREFIX):
                sys.exit("%s: line %r is not a %s constant" % (banks_txt, line, PREFIX))
            names.append(line[len(PREFIX) :].lower())
    return names


def bank_sizes(names, text_dir):
    """Bank index -> (name, message count). A bank with no JSON here counts 0."""
    out = []
    for name in names:
        path = os.path.join(text_dir, name + ".json")
        if not os.path.isfile(path):
            out.append((name, 0))
            continue
        with open(path) as f:
            messages = json.load(f)["messages"]
        if not messages:
            sys.exit("%s: bank %s is empty, which 0 already means" % (path, name))
        if len(messages) > 0xFFFF:
            sys.exit("%s: bank %s has more messages than an id can name" % (path, name))
        out.append((name, len(messages)))
    return out


def main():
    names = bank_order(BANKS_TXT)
    if len(names) > 0xFFF:
        sys.exit("%s: more banks than an id can name" % BANKS_TXT)
    rows = bank_sizes(names, TEXT_DIR)
    authored = sum(1 for _, n in rows if n)
    messages = sum(n for _, n in rows)

    body = [
        "/* Generated by tools/gen_idmap_text.py; Do not edit. */",
        "",
        "#define MMO_TEXT_BANK_COUNT %d" % len(rows),
        "",
        "static const u16 MMO_TEXT_BANK_SIZE[MMO_TEXT_BANK_COUNT] = {",
    ]
    for name, count in rows:
        note = "" if count else ", built with the ROM"
        body.append("    %5d, /* %s%s */" % (count, name, note))
    body.append("};")
    body.append("")

    with open(OUT, "w") as f:
        f.write("\n".join(body))
    print(
        "wrote %s: %d banks, %d authored, %d messages"
        % (OUT, len(rows), authored, messages),
        file=sys.stderr,
    )


if __name__ == "__main__":
    main()
