#!/usr/bin/env python3
"""Generate the pinned keypair fixtures for the mock server double."""
import re
import subprocess
import sys
import tempfile
from pathlib import Path

HERE = Path(__file__).resolve().parent
OUT = HERE.parent / "src" / "mock_keys.gen.h"


def openssl(*args, **kw):
    return subprocess.run(["openssl", *args], check=True,
                          capture_output=True, **kw)


def gen_key(path):
    openssl("ecparam", "-name", "prime256v1", "-genkey", "-noout", "-out", str(path))


def hexblock(text, label):
    """Pull the colon-separated hex block that follows `label:` in -text output."""
    m = re.search(label + r":\s*\n((?:\s+[0-9a-f:]+\n)+)", text)
    if not m:
        raise SystemExit(f"could not find {label} in openssl -text output")
    return bytes(int(b, 16) for b in m.group(1).replace(":", " ").split())


def key_parts(path):
    text = openssl("ec", "-in", str(path), "-text", "-noout").stdout.decode()
    priv = hexblock(text, "priv")
    pub = hexblock(text, "pub")
    # priv is big-endian and may carry a leading 0x00 sign byte; normalise to 32.
    priv = priv.lstrip(b"\x00").rjust(32, b"\x00")
    if len(pub) != 65 or pub[0] != 0x04:
        raise SystemExit(f"unexpected public point ({len(pub)} bytes)")
    return priv, pub


def c_array(name, data):
    lines = [f"static const u8 {name}[{len(data)}] = {{"]
    for i in range(0, len(data), 12):
        chunk = ", ".join(f"0x{b:02x}" for b in data[i:i + 12])
        lines.append(f"    {chunk},")
    lines.append("};")
    return "\n".join(lines)


def main():
    with tempfile.TemporaryDirectory() as td:
        td = Path(td)
        root, eph = td / "root.pem", td / "eph.pem"
        gen_key(root)
        gen_key(eph)
        _, root_pub = key_parts(root)
        eph_priv, eph_pub = key_parts(eph)

        (td / "msg.bin").write_bytes(eph_pub)
        openssl("dgst", "-sha256", "-sign", str(root), "-out", str(td / "sig.der"),
                str(td / "msg.bin"))
        sig = (td / "sig.der").read_bytes()

    banner = "/* Generated by mmo/tools/gen_mock_keys.py, do not edit by hand.\n" \
             " * Pinned test keypairs for the mock server double (mmo/src/mockserver.c).\n" \
             " * These are throwaway TEST keys, never the real server's root. */\n"
    body = "\n\n".join([
        c_array("MOCK_ROOT_PUB", root_pub),
        c_array("MOCK_EPH_PRIV", eph_priv),
        c_array("MOCK_EPH_PUB", eph_pub),
        c_array("MOCK_HELLO_SIG", sig),
    ])
    OUT.write_text(f"{banner}\n{body}\n")
    print(f"wrote {OUT} (sig {len(sig)} bytes)", file=sys.stderr)


if __name__ == "__main__":
    main()
