#!/usr/bin/env python3
"""mmo/CAMERAS, HeartGold's seventeen field camera templates, out of its decomp."""
import re
import struct
import sys
from pathlib import Path

ROWS = 17
ROW = 36
TABLE = "ov01_02206478"
ASM = "asm/overlay_01_021EABA8.s"


def die(msg):
    print("gen_cameras: " + msg, file=sys.stderr)
    raise SystemExit(2)


def read_rows(hg: Path) -> list[bytes]:
    lines = (hg / ASM).read_text().split("\n")
    at = [i for i, l in enumerate(lines) if l.startswith(TABLE + ":")]
    if len(at) != 1:
        die("%s: %s not found once in %s" % (hg, TABLE, ASM))
    rows = []
    for l in lines[at[0] + 1:at[0] + 1 + ROWS]:
        b = bytes(int(x, 16) for x in re.findall(r"0x([0-9A-Fa-f]{2})", l))
        if len(b) != ROW:
            die("row %d of %s is %d bytes, not %d" % (len(rows), TABLE, len(b), ROW))
        rows.append(b)
    return rows


def decode(b: bytes) -> dict:
    dist, = struct.unpack_from("<i", b, 0)
    ax, ay, az = struct.unpack_from("<HHH", b, 4)
    proj = b[12]
    fov, = struct.unpack_from("<H", b, 14)
    near, far = struct.unpack_from("<ii", b, 16)
    ox, oy, oz = struct.unpack_from("<iii", b, 24)
    return dict(dist=dist, ax=ax, ay=ay, az=az, proj=proj, fov=fov, near=near,
                far=far, ox=ox, oy=oy, oz=oz)


def c_block(rows: list[bytes]) -> str:
    out = []
    for i, b in enumerate(rows):
        d = decode(b)
        out.append("    [OPENMMO_PORTED_CAMERA_FIRST + %d] = { %d, { 0x%04X, 0x%04X, 0x%04X }, %s, 0x%04X, %d, %d },"
                   % (i, d["dist"], d["ax"], d["ay"], d["az"],
                      "CAMERA_PROJECTION_ORTHOGRAPHIC" if d["proj"] else "CAMERA_PROJECTION_PERSPECTIVE",
                      d["fov"], d["near"], d["far"]))
    out.append("};")
    out.append("")
    out.append("/* The look-at offset each of those carries, applied to the camera and its")
    out.append(" * target alike; this engine's own templates have none. */")
    out.append("static const VecFx32 sPortedCameraOffsets[OPENMMO_PORTED_CAMERA_COUNT] = {")
    for i, b in enumerate(rows):
        d = decode(b)
        out.append("    { %d, %d, %d }," % (d["ox"], d["oy"], d["oz"]))
    return "\n".join(out)


def main(argv):
    if len(argv) != 3:
        die(__doc__)
    hg = Path(argv[1])
    rows = read_rows(hg)
    if argv[2] == "--c":
        print(c_block(rows))
        return 0
    lines = ["# CAMERAS, GENERATED by tools/gen_cameras.py; DO NOT EDIT.",
             "#",
             "# HeartGold's seventeen field camera templates (overlay 1, %s)," % TABLE,
             "# one per cameraType a header may name; mmo/MAPS's CAM column is the",
             "# index. Fixed-point as the cartridge holds it: distance and planes",
             "# and the offset in 1/4096 units, angles and the fov as 1/65536 turn.",
             "#",
             "# Rows: hg <type> <distance> <angle x y z> <projection> <fov> <near> <far>",
             "#          <offset x y z>",
             ""]
    for i, b in enumerate(rows):
        d = decode(b)
        lines.append("hg %2d %8d %6d %6d %6d %s %6d %8d %8d %8d %8d %8d"
                     % (i, d["dist"], d["ax"], d["ay"], d["az"],
                        "ortho" if d["proj"] else "persp", d["fov"], d["near"],
                        d["far"], d["ox"], d["oy"], d["oz"]))
    lines.append("")
    Path(argv[2]).write_text("\n".join(lines))
    print("gen_cameras: %d templates -> %s" % (len(rows), argv[2]))
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
