#!/usr/bin/env bash
# Regenerates apache/cloudflare-remoteip.conf from Cloudflare's published ranges.
#
# Every request arrives from Cloudflare, so without this every visitor looks like
# the same handful of addresses: in the logs, and to the registration rate limit.
# Cloudflare adds ranges from time to time; rerun this and redeploy when they do.
set -euo pipefail

here="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
out="$here/apache/cloudflare-remoteip.conf"
tmp="$(mktemp)"
trap 'rm -f "$tmp"' EXIT

{
  echo "# Generated by web/update-cloudflare-ips.sh on $(date -u +%Y-%m-%d). Do not edit by hand."
  echo "# Source: https://www.cloudflare.com/ips-v4 and /ips-v6"
  echo "#"
  echo "# Trusts the visitor address Cloudflare forwards, and only from Cloudflare."
  echo "<IfModule remoteip_module>"
  echo "    RemoteIPHeader CF-Connecting-IP"
  for url in https://www.cloudflare.com/ips-v4 https://www.cloudflare.com/ips-v6; do
    curl -fsS "$url" | tr -d '\r' | while read -r range; do
      [ -n "$range" ] && echo "    RemoteIPTrustedProxy $range"
    done
  done
  echo "</IfModule>"
} >"$tmp"

grep -q RemoteIPTrustedProxy "$tmp" || {
  echo "refusing to write a list with no ranges in it" >&2
  exit 1
}
mv "$tmp" "$out"
echo "wrote $out ($(grep -c RemoteIPTrustedProxy "$out") ranges)"
